### ISSUE TITLE
Regent inline mapping analysis incorrect

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#103]
Looks like the Regent compiler inline mapping analysis isn't quite behaving as expect.  Attached is the first time step of Pennant run with the following command line.

./regent.py -mg examples/pennant.rg -fbounds-checks 1 examples/pennant.tests/sedov/sedov.pnt -npieces 3 -compact 0 -absolute 2e-6 -relative 1e-8 -relative_absolute 1e-10 -level 2 -cat legion_spy -logfile spy.log

Clearly there are many more inline mappings there than there should be after the inline mapping analysis is run.
[dataflow_simulate_333.pdf](https://github.com/StanfordLegion/legion/files/35138/dataflow_simulate_333.pdf)

**Comment by magnatelee** [comment]
Commit 395b6a3 closed this issue.

**Comment by magnatelee** [comment]
Commit 395b6a3 has been revoked as of commit 9d5bdbf because the additional inline mappings were simply due to the Legion runtime turning off the inner optimization when Legion Spy is turned on (note that the runtime overrides 'options.inner' with false when Legion Spy is on: https://github.com/StanfordLegion/legion/blob/master/runtime/legion/runtime.cc#L15663-L15665).

**Comment by lightsighter** [comment]
This issue is back so I am re-opening it.  It doesn't have anything to do with the inner task optimization.

**Comment by magnatelee** [comment]
Closed by commit 6a6d241
