### ISSUE TITLE
Legion GPU saxpy example

### ISSUE THREAD

**Issue by MiZhangWhuer** [StanfordLegion/legion#1050]
I've read the example code for GPU version realm_saxpy. Is there any example for Legion GPU saxpy? I still can not figure out how to implement a gpu function using the Legion high-level API.

Looking forward to your reply.

**Comment by lightsighter** [comment]
I'd recommend looking at the Thrust interop example which happens to implement Saxpy in Legion:
https://gitlab.com/StanfordLegion/legion/-/tree/master/examples/thrust_interop
If you wanted to do it with plain CUDA instead of Thrust, all the Legion code would be identical and you would just replace the `thrust::transform` call with CUDA kernel launch:
https://gitlab.com/StanfordLegion/legion/-/blob/master/examples/thrust_interop/thrust_shim.cu#L73

**Comment by MiZhangWhuer** [comment]
> I'd recommend looking at the Thrust interop example which happens to implement Saxpy in Legion:
> https://gitlab.com/StanfordLegion/legion/-/tree/master/examples/thrust_interop
> If you wanted to do it with plain CUDA instead of Thrust, all the Legion code would be identical and you would just replace the `thrust::transform` call with CUDA kernel launch:
> https://gitlab.com/StanfordLegion/legion/-/blob/master/examples/thrust_interop/thrust_shim.cu#L73

Thanks for the repaid replay! Close this issue because I forget to set -ll:gpu parameter in my program. I have successfully implemented the example and will share it in the next few days.
Best regards!
