### ISSUE TITLE
legion_prof: >100% memory allocation reported when instances are GC'd

### ISSUE THREAD

**Issue by rohany** [StanfordLegion/legion#1109]
In cases where instances are GC'd and then re-used, legion prof seems to get confused:
![image](https://user-images.githubusercontent.com/15331872/123043065-9bffcb80-d3ac-11eb-9f8f-539c7f512dc0.png)

A set of files to reproduce output like this are on sapling in `/home/rohany/manolis-repro`. Run the program with arguments `-ll:gpu 4 -ll:ocpu 1 -ll:othr 1 -ll:fsize 25 -ll:cpu 1 -ll:csize 5000 -gx 2 -gy 2 -n 2048 -tm:fill_cpu -tm:disable_mapping_cache -tm:untrack_valid_regions -dm:exact_region`. This behavior was reported on the `control_replication` branch, on commit `93553261e0bd93fd3db7dc677d9d827a4383f781`.

**Comment by rohany** [comment]
cc @seemamirch

**Comment by lightsighter** [comment]
It's likely that Legion Prof isn't accurately modeling Realm's deferred allocations/deletions accurately.

**Comment by eddy16112** [comment]
I added the following code into `legion_prof.py` to calculate the memory utilization for each Memory.
```
diff --git a/tools/legion_prof.py b/tools/legion_prof.py
index 5e2838319..dbd0e939e 100755
--- a/tools/legion_prof.py
+++ b/tools/legion_prof.py
@@ -846,6 +846,24 @@ class Memory(object):
                 trimmed_instances.add(inst)
         self.instances = trimmed_instances
 
+    def check_time_points(self):
+        if len(self.time_points) == 0:
+            return
+        count = 0
+        idx = 0
+        for point in self.time_points:
+            # print(point.time, point.first)
+            if point.first:
+                count += point.thing.size
+            else:
+                count -= point.thing.size
+            if count > self.capacity:
+                print("!!Wrong, Memory:", self, ", Capacity:", self.capacity, " < allocated:", count)
+                for i in range(idx+1):
+                    print("point: ", self.time_points[i].time, "size:", self.time_points[i].thing.size, point.first)
+                assert 0
+            idx += 1
+
     def sort_time_range(self):
         self.max_live_instances = 0
         for inst in self.instances:
@@ -853,6 +871,7 @@ class Memory(object):
             self.time_points.append(TimePoint(inst.stop, inst, False, 0))
         # Keep track of which levels are free
         self.time_points.sort(key=lambda p: p.time_key)
+        self.check_time_points()
         free_levels = set()
         # Iterate over all the points in sorted order
         for point in self.time_points:
```
 and her is the output:
```
!!Wrong, Memory: Framebuffer Memory 0x1e00000000000002 , Capacity: 81788928000  < allocated: 96242432064
point:  7386690.006 size: 10696172288 True
point:  7386874.603 size: 10696172288 True
point:  7389195.24 size: 10696172288 True
point:  7407521.574 size: 21384638400 True
point:  7407581.257 size: 21384638400 True
point:  7410429.274 size: 21384638400 True
```
So I think @lightsighter is right, the data indicated we have allocated 96242432064 bytes for the above 6 instances, but actually Realm defers the allocation.

**Comment by streichler** [comment]
If you only want to show instances when they really exist, you should probably be using `ready_time` here:
https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion/legion_profiling.cc#L703

**Comment by eddy16112** [comment]
@streichler Does deferred allocation only happens on GPU memory?

**Comment by streichler** [comment]
Deferred allocation is possible on most memories.  And for memories that don't do deferred allocation, the "create" and "ready" times ought to be nearly coincident, so "ready" would still be representative there too.

**Comment by eddy16112** [comment]
@manopapad I have pushed a fix into a new branch https://gitlab.com/StanfordLegion/legion/-/commits/cr_fix_utilization. It is based on the control replication branch, so you should be able to test in with legate. If it works, I will cherry-pick the commit into the master branch. 
Instead of assigning `ready` to `create`, I record both of them just in case we want to render the deferred allocation in the future.

**Comment by eddy16112** [comment]
I think there is a bug in the search feature. Here is the snapshot of searching "375". It shows Task 375 with a wrong instance. The initiator of the instance is "851". The data in the tsv files are correct, so I guess the bug is in the js file. Here is the code of the search feature https://gitlab.com/StanfordLegion/legion/-/blob/master/tools/legion_prof_files/js/timeline.js#L2143-2173, but I do not quite understand how it works. 
![Screen Shot 2022-09-14 at 12 35 27 PM](https://user-images.githubusercontent.com/7025793/190241052-e3346a5f-fde0-4d99-a9ef-94368b6ebfeb.png)

@manopapad would you please share the original gz file dumped by legion. I will try to render the deferred allocation.

**Comment by eddy16112** [comment]
I have pushed another commit for rendering the deferred allocation. Here is an example:
![Screen Shot 2022-09-14 at 1 45 41 PM](https://user-images.githubusercontent.com/7025793/190248343-a6dbd730-ca6e-4b5e-a68d-33264cc42569.png)
Now an instance will have two boxes, the first one is the deferred allocation, which uses timestamp from `create` to `ready` and is rendered using a lighter shade. The second one is the actually instance which uses timestamp from `ready` to `create`. I am thinking about adding a threshold for deferred allocation: if the cost of the deferred allocation is less than the threshold, we do not render it, in order to minimize the size of tsv files.

**Comment by manopapad** [comment]
Here's the original .gz file, sorry it took a while, had to rebuild 
[131503.tar.gz](https://github.com/StanfordLegion/legion/files/9569752/131503.tar.gz)

**Comment by manopapad** [comment]
This is what it looks like with the latest changes to legion_prof.py. It looks very pretty, but the latest instance's "deferred" section is drawn over all the previous instances, so I can't see anything about those instances anymore. Ideally all the "deferred" sections would be rendered below any "live" sections (even if belonging to other instances), and possibly we can (later) highlight an instance's deferred region on mouseover (or click). There is a deeper discussion to be had here, about how to visualize the "deferred" section in a non-intrusive way.

<img width="1904" alt="Screen Shot 2022-09-14 at 2 40 08 PM" src="https://user-images.githubusercontent.com/215728/190267709-826ef72e-8b4a-4628-97a0-5e92f28555bf.png">

**Comment by eddy16112** [comment]
@manopapad there was a bug in my previous commit, the instances are overlapped. Now it has been fixed. Here is the new result of your file. Now I divided original instance box (from `start` to `stop`) into two, so the total length is the same, but now you can see a shaded box and a solid box.  
![Screen Shot 2022-09-14 at 4 10 28 PM](https://user-images.githubusercontent.com/7025793/190272159-5132ea9c-a8bf-4996-88e7-e5639a74a684.png)

**Comment by manopapad** [comment]
Worked for me as well, great work!

**Comment by elliottslaughter** [comment]
Is this a `legion_prof.py` change and if so does it require something to be done in Rust?

**Comment by eddy16112** [comment]
> Is this a `legion_prof.py` change and if so does it require something to be done in Rust?

I have updated the Rust accordingly.
