### ISSUE TITLE
idx_imp.cc uses deprecated version of FileMemory::create_instance

### ISSUE THREAD

**Issue by aritpaul** [StanfordLegion/legion#117]
When executing the `09_custom_mappers` tutorial code, I hit an assertion:
```
Running daxpy for 1024 elements...
Partitioning data into 1 sub-regions...
Mapped region 0 of task unnamed_task_1 (ID 13) to memory 60000000
Initializing field 0 for block 0...
Mapped region 0 of task unnamed_task_1 (ID 16) to memory 60000000
Initializing field 1 for block 0...
custom_mapper: /home/cs144/legion/runtime/lowlevel_disk.cc:138: virtual Realm::RegionInstance Realm::FileMemory::create_instance(Realm::IndexSpace, const int*, size_t, size_t, size_t, const std::vector<long unsigned int>&, Realm::ReductionOpID, off_t, const Realm::ProfilingRequestSet&, Realm::RegionInstance): Assertion `0' failed
```

I verified that I hit this assertion on the `master` branch. It seems like at `idx_imp.cc:442`, we call a deprecated version of `create_instance` in `lowlevel_disk.cc:138`. Seems like we need to just update to use the newer API.

Here is the [backtrace output from gdb](https://github.com/StanfordLegion/legion/files/88281/legion_create_instance_backtrace.txt).

I have not tested if the same thing exists with HDFMemory.

**Comment by jiazhihao** [comment]
Thanks for pointing out a bug here, I could reproduce the failure case on my machine. 

The issue is that Legion mapper are not supposed to map a region to FileMemory or HDFMemory. Instances in them should be external normal or HDF files that have been attached to some logical regions. I would suggest that we change machine.get_visible_memoris() so that it won't return FileMemory or HDFMemory.

**Comment by lightsighter** [comment]
I agree.  Go ahead Zhihao, you know how to make that change.

**Comment by streichler** [comment]
Zhihao, when you make this change, please don't base the condition on the memory kind, because then it'll just break for the next "external" memory we create.  Instead, use the `capacity()` method (https://github.com/StanfordLegion/legion/blob/master/runtime/realm/memory.h#L66) and if a memory reports that it has 0 capacity, that's an indication that a mapper shouldn't try to create instances there.

**Comment by jiazhihao** [comment]
The commit b636f75 fixes the issue.
