### ISSUE TITLE
Error when launching python tasks with legion_python -m

### ISSUE THREAD

**Issue by eddy16112** [StanfordLegion/legion#1199]
Here is a reproducer

#test_module.py
```
from pygion import task

@task
def hello():
    print("hello")

def main():
    print("main")
    hello()

if __name__ == "__main__":
    main()
```

If I run with legion_python ./test_module.py, then it works, but if I run with legion_python -m test_module, then I am having the following errors:
```
Traceback (most recent call last):
  File "/home/wwu/legion-python/bindings/python/legion_top.py", line 357, in legion_python_main
    run_path(module, run_name='__main__')
  File "/home/wwu/legion-python/bindings/python/legion_top.py", line 200, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "/vast/home/wwu/legion-python/jupyter_notebook/test_module.py", line 12, in <module>
    main()
  File "/vast/home/wwu/legion-python/jupyter_notebook/test_module.py", line 9, in main
    hello()
  File "/home/wwu/legion-python/bindings/python/pygion.py", line 1745, in __call__
    return self.spawn_task(*args, **kwargs)
  File "/home/wwu/legion-python/bindings/python/pygion.py", line 1748, in spawn_task
    if _my.ctx.current_launch:
AttributeError: '_thread._local' object has no attribute 'ctx'
```

**Comment by lightsighter** [comment]
I don't think this has anything to do with Legion Python. When I run this I get the following warning for Pygion:

```
WARNING: Executing Python modules via legion_python has been deprecated.
It is now recommended to run the script directly by passing the path
to legion_python.
```

@elliottslaughter can you say way that warning doesn't mention Pygion? As far as I can tell our code for running modules in `legion_python` should be working.

**Comment by lightsighter** [comment]
The relevant warning comes from here in `pygion.py`:

https://gitlab.com/StanfordLegion/legion/-/blob/master/bindings/python/pygion.py#L2541-2545

**Comment by lightsighter** [comment]
I also feel like this should just be a fatal error from Pygion so it makes it clear you can't run Pygion programs with module launch.

**Comment by elliottslaughter** [comment]
That warning doesn't apply to `legion_python -m <module>`. It applies to `legion_python <module>` (note: no `.py`!), a mode that I'm not sure even exists anymore.

To the best of my knowledge, when you run `legion_python -m <module>`, it finds `<module>.py`, but then loads it as `__main__`. So all the usual features that work when you do `legion_python <script.py>` should work with `legion_python -m <module>`.

It may be that the auto-detection is not working and it's kicking you into `legion_python <module>` mode even though it should really be processing it like a script.

**Comment by lightsighter** [comment]
@elliottslaughter as far as I can tell, `legion_python` is doing the right thing. Can you confirm that and that Pygion's detection mechanism for that case is not working correctly? At a minimum I do think you'll want to update the warning message to say that the warning applies specifically to Pygion.

**Comment by lightsighter** [comment]
As far as I can tell, when we run with `-m <module>` (no `.py` ending), we're going down this path in Pygion:

https://gitlab.com/StanfordLegion/legion/-/blob/master/bindings/python/pygion.py#L2541-2545

And that leads the `_my.ctx` not to be initialized, which then leads to the crash.

**Comment by elliottslaughter** [comment]
The functionality to import a module into Realm via `legion_python` was already removed:

https://github.com/StanfordLegion/legion/commit/de09c7f82ab566be78794f1615df09b82944e0fb#diff-e9b766997caa8676affa5902423fb661e3a6fd3b5dbfde5e4a7c1504b9b83480L217-L221

I think that means this detection logic is now broken:

https://github.com/StanfordLegion/legion/blob/master/bindings/python/pygion.py#L118-L130

Once we detect `legion_python`, we should simply set `is_script` to be unconditionally true.

However, we can't remove it outright because it is still possible to manually import a Python module with Realm via the C++ API:

https://github.com/StanfordLegion/legion/blob/master/examples/python_interop/python_interop.cc#L97

So there still does (unfortunately) need to be some sort of detection logic (although it can be simpler), unless we're willing to remove this capability outright.

**Comment by elliottslaughter** [comment]
@eddy16112 I pushed a fix to `master`, please pull and try again.

**Comment by lightsighter** [comment]
I pushed a few sanity checks for error checking some configurations for Pygion as well so we don't get random crashes.

**Comment by elliottslaughter** [comment]
@lightsighter Is there a way to check if we're running inside a task or not? I realized last night that all of this auto-detect logic is basically a fancy way of trying to answer that question: if we're in a task, we need to set up the implicit context, otherwise we skip it. If we could check directly then there wouldn't be a need to mess with the arguments.

**Comment by lightsighter** [comment]
The `has_context` method will do that:

https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion/legion_c.h#L4666-4670

If it's true, then you're inside a task. If not, then you're not inside a task.

**Comment by eddy16112** [comment]
@elliottslaughter The bug is fixed. Feel free to close the issue.

**Comment by elliottslaughter** [comment]
I pushed a second change that completely removes the argument parsing for script auto-detection, and switches to `legion_runtime_has_context`. Assuming it passes I will close this issue.
