### ISSUE TITLE
Realm: ib_alloc impossible

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1207]
I'm hitting this issue on both Perlmutter and Crusher when running without gasnet:

```[0 - 7f1c263d7700]    0.696958 {6}{ib_alloc}: impossible: op=0/0x7f1c108403a0 mem=1a00000000000001 needed=268566528 avail=268435456```

Running with `-ll:ib_fsize` does not do anything. There is log from running with `-level dma=2,xplan=1` here: http://sapling.stanford.edu/~seshu/run_0.log

**Comment by streichler** [comment]
So it looks like it's `-ll:ib_zsize` what you'd need, and it'd need to be big - at least 1088 (MB).  This would basically be working around the issue in #1070, which has been turned from a hang to a fatal error.

In this case here, what you probably actually want is these device->host copies to be performed directly instead of via an intermediate buffer, and it's the change made for #1081 that's getting in your way, so before messing with `-ll:ib_zsize`, I'd try instead `-cuda:hostreg 0`, which tells Realm it's allowed to try to register arbitrarily-large amount of host memory for direct host<->device copy goodness.  It'll increase the startup time, but for s3d, a few more seconds of startup time are a fine price to pay for faster iteration (or, you know, running at all).

**Comment by syamajala** [comment]
Adding `-cuda:hostreg 0` works on Perlmutter. I guess we dont have anyway to run on Crusher right now.

**Comment by eddy16112** [comment]
@syamajala You can try `-hip:hostreg 0` on Crusher.

**Comment by syamajala** [comment]
`-hip:hostreg 0` works after updating to the latest legion.
