### ISSUE TITLE
Reduction method for structured data is not exposed.

### ISSUE THREAD

**Issue by tjcorona** [StanfordLegion/legion#122]
This issue is in reference to the Stanford/LANL/Sandia/Utah/Kitware meeting on January 19. A reduction operation is available that takes a ptr_t as its target write location; a similar operation for domain points does not exist.

**Comment by lightsighter** [comment]
The reduction methods on accessors are templated so that they will work with both unstructured ptr_t and structured domain points:

https://github.com/StanfordLegion/legion/blob/stable/runtime/accessor.h#L317-L329

You can also opt to use the 'raw_rect_ptr' methods to directly get access to the physical instance and perform reductions directly.

**Comment by streichler** [comment]
TJ opened this at my request.  The problem with `raw_rect_ptr` here is that the task has to somehow know what kind of reduction instance (if any) it got.

**Comment by tjcorona** [comment]
I just wanted to ping this issue. FWIW, I have a small (~350 lines) test program that can reproduce this problem. The issue is apparent at compile time, where a ReductionFold object is trying to call the reduce function defined [here](https://github.com/StanfordLegion/legion/blob/stable/runtime/accessor.h#L915-L925), but with a `DomainPoint` instead of a `ptr_t`.

**Comment by streichler** [comment]
@lightsighter This is fixed with the new accessors in the deppart branch, right?

**Comment by lightsighter** [comment]
Yes, fixed with the deppart branch so I'm going to close the issue.
