### ISSUE TITLE
Change custom SerDez FIELD_TYPE to disambiguate with Legion #define FIELD_TYPE

### ISSUE THREAD

**Issue by abpoms** [StanfordLegion/legion#124]
The custom SerDez functionality for allowing user defined serialization and deserialization of fields requires specifying a typedef with the name FIELD_TYPE inside the custom serdez class.

The name chosen for the typedef conflicts with an existing Legion #define located here https://github.com/StanfordLegion/legion/blob/master/runtime/legion/legion_types.h#L734

As legion_types.h is included by legion.h, it's very easy to end up in a situation where all instances of FIELD_TYPE are replaced by uint64_t. Thus if a user is defining a custom serdez class and happens to have included legion.h, then their typedef will turn from 
``` typedef ... FIELD_TYPE ``` 
to
```typedef ... uint64_t``` 

which leads to confusing error messages.

As the serdez functionality is newer, I suggest changing the typedef name to something else to avoid the conflict.

**Comment by lightsighter** [comment]
If only C/C++ macros were hygenic...  In general I try to keep macros from showing through to the interface (as evidenced by the #undef statements in legion_types.h), however there are some macros that I do use inside the runtime and are not marked undefined again.  I've pushed a change to the master branch that renames most of those macros to something that is unlikely to conflict with any application level names.  If the issue is fixed go ahead and close it, otherwise let me know if there is still a problem.

**Comment by abpoms** [comment]
The joys of the C++ preprocessor... That fixes it!
