### ISSUE TITLE
32 rank run failure

### ISSUE THREAD

**Issue by cmelone** [StanfordLegion/legion#1263]
We've added a new test to our CI suite for HTR, targeting runs beyond a single node. We are able to run successfully on 8 ranks, 2 ranks per node. However, when we try to run on 32 ranks, the program works until we split into two directions. At this point, HTR does not produce any output and the program simply hangs until the queue kills the job.

We're running on Stanford HPCC (yellowstone) nodes, CPU. Using the latest version of control_replication

Please let me know if I can provide any output or details that would be helpful.

@mariodirenzo

**Comment by elliottslaughter** [comment]
Can you clarify how many nodes your 32 rank run is using? Is this 16 nodes (2 ranks per node) or something else?

One way to cause a freeze is if you run out of memory. This could happen if you're running a very large problem size or trying to run a high number of ranks per node.

Otherwise I'm guessing we'll want to see backtraces from a frozen set of processes with debug mode and `-ll:force_kthreads`.

**Comment by mariodirenzo** [comment]
> One way to cause a freeze is if you run out of memory. This could happen if you're running a very large problem size or trying to run a high number of ranks per node.

He is considering a constant problem size that is partitioned on an increasing number of ranks. For this reason, the 32 ranks execution has less memory per rank than the 8 ranks execution.

@cmelone will need to comment on the number of nodes because I cannot remember how many ranks per node he is considering

**Comment by lightsighter** [comment]
If you can do what @elliottslaughter says, also build it in debug mode and run with `-ll:force_kthreads` and `-lg:inorder` and then report backtraces from all frozen nodes using the `tools/print_backtraces.sh` script.
