### ISSUE TITLE
Inconsistent destruction behaviour, Lifetime of field and index spaces

### ISSUE THREAD

**Issue by rbberger** [StanfordLegion/legion#1301]
We've been seeing some inconsistent deletion behavior in Legion.

Attached is a reproducer which does basically the following:
- Create an index space
- Create a field space
- Create a logical region with these two and hold on to it
- Schedule deletion of index and field space (`recursive=false`). Our assumption is that the logical region would keep those two alive until it is destroyed itself.
- Create a second logical region with same index and field space
- Delete both logical regions at the end: one deletion order works, the other doesn't.

[test.tar.gz](https://github.com/StanfordLegion/legion/files/9162197/test.tar.gz)

```
mkdir build
cd build
cmake ..
make
./test_legion
```

**Comment by lightsighter** [comment]
Ok, so looking at this example that you have provided, I can now point out exactly where the illegal behavior is occurring: in this example, the creation of `no_clone_lr` using `typed_lr.get_field_space()` is not legal. If we were interpreting this program eagerly, then this would constitute a "use-after-free" bug because the "reference count" on the field space `fs` has gone to zero at that point in the program. When you create a field space it has a reference count of one. You can add references by calling `create_shared_ownership`. Each call to `destroy_field_space` removes a reference. Once the reference count goes to zero then it's not legal to use the resource anymore from the application.

I think where @opensdh and I had some confusion was around what the phrase "keeping a resource alive" means. I think @opensdh was interpreting this to mean that any dependent resources keep a reference (in the sense above) to the field space. My definition is weaker and simply means that the runtime will ensure that you can still refer to the resource (in this case the field space) in any asynchronous tasks or other operations launched *before* the reference count on a resource went to zero in program order. A long time ago, Legion used to make you synchronize before deleting a resource to ensure that any asynchronous tasks or operations that might refer to the resource were finished. Now we maintain the illusion of sequential semantics under asynchrony so that deletions do not require this synchronization. In that sense, internally the runtime is doing what it needs to to keep the meta-data structures that represent that field space alive until all asynchronous tasks and operations are done with it before reclaiming them. (The confusion probably comes from the fact that to do this the runtime is performing its own internal reference counting, different than the reference counting described above and there was ambiguity as to which one we were discussing.) 

That said, I think you should still stick with the sequential semantics interpretation of the program as the best way to understand how to think about things. If the reference count on a resource like a field space has gone to zero at some point in the program, then you can't use it to create new resources anymore like new logical regions. You can however continue to use logical regions that were made before their field space's reference count went to zero safely until their own reference counts go to zero.

**Comment by opensdh** [comment]
I'm still not sure I understand the model.  If we create a logical region `r` from a field space `f` and then "destroy" `f`, what does it mean that we can "continue to use" `r`?  Does calling `r.get_field_space()` constitute a use of `r`, of `f`, or both?

If it counts as a use of `f`, what else might count as such an invalid use?  (Would launching a task with a field on `r` be a use of `f`, since it involves a field ID given meaning by `f`?)

If it doesn't count as a use of `f`, is it the creation of another logical region from the return value that refers to a "non-existent" field space that is invalid?  What operations can be performed on such a dangling reference?

**Comment by lightsighter** [comment]
> I'm still not sure I understand the model. If we create a logical region r from a field space f and then "destroy" f, what does it mean that we can "continue to use" r?

You can't do any runtime calls that also take a `Legion::Context` and a handle to the resource. For example, `runtime->create_logical_region(ctx, is, fs)` would be illegal.

> Does calling r.get_field_space() constitute a use of r, of f, or both?

Neither of those constitute a use of `r` or `f` since you're just dealing with the handles in that expression and doesn't involve talking to the runtime at all. If you do `runtime->method(ctx, ...` then you're talking to the runtime and that's what you can't do with a resource after its reference count goes to zero.

> Would launching a task with a field on r be a use of f, since it involves a field ID given meaning by f?

No, because the handle you're actually using is the logical region handle `r`. Yes, implicitly there is a handle for `f` in the handle of `r`, but you don't need to worry about that. I promise that that will always work even if the reference count for `f` has gone to zero because `r` is still live.

> If it doesn't count as a use of f, is it the creation of another logical region from the return value that refers to a "non-existent" field space that is invalid?

Yes, that's right. It doesn't matter where you got the handle from. If the reference count to the resource that the handle represents is zero then you can't use it directly.

> What operations can be performed on such a dangling reference?

None really, other than maybe printing out the handle, it's a dangling reference to a resource that no longer exists. :)

**Comment by opensdh** [comment]
I guess this is a coherent model I can use: our handle is something like a `RealResource**` that points to a [tombstone](https://en.wikipedia.org/wiki/Tombstone_(programming)).  Once its reference count hits 0, we're pointing at the empty tombstone, which can still be identified but can't be given to anything that expects to dereference **it**.

Thanks for the explanation; we'll let you know if we see any behavior that seems inconsistent with it.  For the future, it would be nice if it appeared in the documentation, of course.

**Comment by lightsighter** [comment]
Do you think a different semantics would be more intuitive? What would it be?

**Comment by opensdh** [comment]
Well, I liked the one I thought was true: that the reference held by a logical region to its field space (which is already sufficient for launching tasks and the like) was exactly equivalent to the one produced by `create_field_space`, so that you could (if you wanted) do something like
```
const auto f=r.create_field_space(ctx);
const auto lr=r.create_logical_region(ctx,…,f);
r.destroy_field_space(ctx,f);
// …
r.create_shared_ownership(ctx,f);           // OK: f is still alive thanks to lr
r.destroy_logical_region(ctx,lr);
auto lr2=r.create_logical_region(ctx,…,f);  // OK: f is alive thanks to create_shared_ownership
```
That said, if this would be inefficient or somehow painful to implement, this isn't a request to change it.  (I already requested that the rules be written down, whatever they are.)

**Comment by lightsighter** [comment]
@opensdh Please try again with the most recent `control_replication` branch and see if the semantics match your expectation.

**Comment by rbberger** [comment]
I've retested our code changes based on the latest `control_replication` commit on GitLab and it does indeed close this issue. Should we find other places where it might still surprise us, we'll let you know. Thank you!
