### ISSUE TITLE
[Question] Legion + MPI Interop - Multiple MPI processes per node

### ISSUE THREAD

**Issue by brombaut** [StanfordLegion/legion#1306]
I'm wondering, when using Legion with MPI applications (e.g., the `examples/mpi_interop/mpi_interop.cc` example), whether it only makes sense to configure MPI to run with a single process per node.

For example, if I were to run the `mpi_interop` example only on my laptop (i.e., 1 node with multiple cores), should I be configuring MPI to only run with a single process so that the Legion runtime only starts the top level task once (from MPI rank 0)?

Otherwise (at least from my thinking) if I were to configure MPI to run with 2 processes on my laptop, the `top_level_task` will then be started from the Legion runtime twice (from rank 0 and rank 1), and then each of those top level tasks will spawn off 2 `mpi_interop_task`s (because the `MustEpochLauncher` has a launch bounds of the total number of MPI processes).

**Comment by eddy16112** [comment]
> Otherwise (at least from my thinking) if I were to configure MPI to run with 2 processes on my laptop, the top_level_task will then be started from the Legion runtime twice (from rank 0 and rank 1), and then each of those top level tasks will spawn off 2 mpi_interop_tasks (because the MustEpochLauncher has a launch bounds of the total number of MPI processes).

No, if you use the master branch, you will only see one `top_level_task` no matter how many processes you use. Here is the output of `mpi_interop`
```
(base) wwu@g0004:/scratch2/wwu/legion-master/examples/mpi_interop$ mpirun -np 2 ./mpi_interop
Hello from MPI process 0 of 2
Hello from MPI process 1 of 2
MPI Doing Work on rank 0
MPI Doing Work on rank 1
Hello from Legion Top-Level Task
MPI Rank 0 maps to Legion Address Space 0
MPI Rank 1 maps to Legion Address Space 1
Hello from Legion MPI-Interop Task 0
Legion Doing Work in Rank 0
Hello from Legion MPI-Interop Task 1
Legion Doing Work in Rank 1
MPI Doing Work on rank 0
MPI Doing Work on rank 1
Legion Doing Work in Rank 0
Legion Doing Work in Rank 1
...
```

**Comment by lightsighter** [comment]
@brombaut This is an inherent tension when interoperating Legion with MPI. Legion prefers to run in a single-process-per-node configuration so that the we can manage all the resources of the node with a single runtime, whereas most MPI programs prefer to run with multiple processes per node for simplicity. It's really up to you (the user) which configuration you're going to choose to use: either way you're going to pick something that is worse for either MPI or Legion, just matters which one is more important to you. 

Aside: if you want to run in the single-process-per-node configuration you might be able to make some progress using `MPI_THREAD_MULTIPLE` and then creating a communicator that has one participant for each core in a process.

If you do go with multiple-process-per-node configuration, just be aware that Legion (and the underlying Realm) runtime will have a separate instance in each process and there is some overhead to that.

**Comment by brombaut** [comment]
Thank you both for your replies! @eddy16112 after reading your reply, I did some more digging and came across this comment (https://github.com/StanfordLegion/legion/issues/569#issuecomment-517041173) which led be in the direction of realizing I hadn't built GASNet with `--enable-mpi-compat`. After building GASNet properly and rerunning `mpi_interop` with `-np` values of `2`, `4`, etc. it works as expected as you described. Thanks!

@lightsighter thanks for the explanation! I'll close this issue.
