### ISSUE TITLE
create_partition_by_restriction color_space type

### ISSUE THREAD

**Issue by ClProsser** [StanfordLegion/legion#1323]
I'm currently trying to create a parallel version of a 3d stencil using Legion and C++. As some operations at a specific point depend on other points, I'm using `create_partition_by_restriction` to create partitions with a specific extent similar to the Multiple Partitions tutorial. 

According to the Doxygen documentation, the function declaration is:
```
template<int DIM, int COLOR_DIM, typename COORD_T>
IndexPartitionT<DIM,COORD_T> create_partition_by_restriction(Context ctx,
                          IndexSpaceT<DIM,COORD_T> parent,
                          IndexSpaceT<COLOR_DIM,COORD_T> color_space,
                          Transform<DIM,COLOR_DIM,COORD_T> transform,
                          Rect<DIM,COORD_T> extent,
                          PartitionKind part_kind = LEGION_COMPUTE_KIND,
                          Color color = LEGION_AUTO_GENERATE_ID);
```

However, this declaration misses a typename (e.g. `COLOR_COORD_T`) for the `color_space`. Based on my understanding, the correct function declaration is:
```
template<int DIM, typename COORD_T, int COLOR_DIM, typename COLOR_COORD_T>
IndexPartitionT<DIM,COORD_T> create_partition_by_restriction(Context ctx,
                          IndexSpaceT<DIM,COORD_T> parent,
                          IndexSpaceT<COLOR_DIM,COLOR_COORD_T> color_space,
                          Transform<DIM,COLOR_DIM,COORD_T> transform,
                          Rect<DIM,COORD_T> extent,
                          PartitionKind part_kind = LEGION_COMPUTE_KIND,
                          Color color = LEGION_AUTO_GENERATE_ID);
```
**Notice**: I adjusted the template argument order.

Looks like this is a good first issue as well.
Thanks :)

**Comment by elliottslaughter** [comment]
I guess this is a question for @lightsighter because this is how it's represented in the code:

https://github.com/StanfordLegion/legion/blob/b853aa5d8623ff7a52a5a473593c06c7de2bea56/runtime/legion.h#L5035-L5042

So the code seems to assume the parent, color space, and transform all use the same `COORD_T`, but they don't necessarily have to.

**Comment by lightsighter** [comment]
This is the intended type signature for this function. The motivation being that the runtime is going to have to perform some arithmetic on the `color_space` using the `transform` and `extent` in order to compute the bounds for each subregion of the `parent`.  If the `parent`,`color_space`, `transform`, and `extent` had different coordinate type s(note you could conceivable give them all different coordinate types), it's not clear where the runtime should do the conversion of values: should all the coordinate math be done using the `COORD_T` type or the `COLOR_COORD_T` type? Depending on values and truncation/overflow/underflow semantics the results might be very different with different coordinate types or even undefined (stupid c++). So to make sure the semantics of the call are well-defined, we insist that in the case of this particular call the coordinate types are all the same so that it's obvious to users what's happening when the runtime performs its coordinate math.

**Comment by ClProsser** [comment]
Thanks for the clarification, this was not obvious to me. 
Thus, I'll either initialize two index spaces with different types or assume both `COLOR_COORD_T` and `COORD_T` are equal.

**Comment by lightsighter** [comment]
Or you can do the conversion yourself before calling the runtime. If you call the non-templated version of the function, then the runtime just promotes all math to signed 64-bit integer math. The templated version though will do the math with the right coordinate types.
