### ISSUE TITLE
Legion Spy: why does a fence register dependencies on dominated tasks?

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1335]
In the following program, I would expect the raw Legion Spy logs to contain event dependencies for `world` only on the last `hello` task. However, the raw logs contain dependencies on all three previous `hello` tasks.

It seems that `legion_spy.py` simplifies the event graph to remove dominating tasks itself. However, I do not see how I can do this in `legion_prof_rs` because connectivity in the event graph does not by itself indicate dominance. (I.e., I cannot safely cut out a transitive operation dependence because there may be a legitimate dependence on the prior task).

```
import "regent"

task hello(r : region(int))
where reads writes(r) do
end

task world()
end

task main()
  var r = region(ispace(ptr, 5), int)
  hello(r)
  hello(r)
  hello(r)
  -- The fence captures dependencies on ALL previous tasks.
  __fence(__execution)
  world()
end
regentlib.start(main)
```

`legion_spy.py` output (looks like what I'd expect):  [event_graph_main_2.pdf](https://github.com/StanfordLegion/legion/files/9641322/event_graph_main_2.pdf)

`legion_prof_rs` output (need to zoom in and click on `world` to see three dependencies on `hello`): http://sapling.stanford.edu/~eslaught/legion_prof_fence/legion_prof_spy_rs

Logs: 
[spy_0.log](https://github.com/StanfordLegion/legion/files/9641329/spy_0.log)
[prof_0.gz](https://github.com/StanfordLegion/legion/files/9641330/prof_0.gz)

**Comment by lightsighter** [comment]
> However, the raw logs contain dependencies on all three previous hello tasks.

Right, because the runtime records dependences from the fence on all prior tasks/ops since the previous fence. It's cheaper than doing the full physical analysis on all the logical regions. It adds some redundant dependences but not so many that it's overly expensive.

> It seems that legion_spy.py simplifies the event graph to remove dominating tasks itself.

Also correct. Legion Spy performs a transitive reduction on the Realm event graph to remove edges that are implied by other edges to make the graph simpler to view (for humans).

> However, I do not see how I can do this in legion_prof_rs because connectivity in the event graph does not by itself indicate dominance. (I.e., I cannot safely cut out a transitive operation dependence because there may be a legitimate dependence on the prior task).

It sounds like you're questioning whether its even safe to perform a transitive reduction or not. It should always be safe to perform a transitive reduction because it doesn't change the topology of the graph. For all pairs of nodes that had a path between them in the original graph, then after the transitive reduction, there must still exist a path between those pairs of nodes. It's probably not the same path, but it will still exist. The relationship between pairs of nodes therefore does not change.

**Comment by elliottslaughter** [comment]
Transitive reduction preserves all paths, but not all data flows. As long as we're aware that's a tradeoff we're making, then I'm fine with it. Just wanted to make sure we're on the same page.

**Comment by lightsighter** [comment]
That is the tradeoff that I made in Legion Spy and nobody has complained about it yet. ;) In my experience it is the best representation for the human visual system. FWIW, Legion Spy actually has a mode where it computes the "equivalence set flows" on the edges of the transitive reduction in order to perform the verification of the physical analysis, but that is a much more expensive construction.

**Comment by elliottslaughter** [comment]
I implemented this for Rust in a branch, and it seems to be working. Closing since my outstanding issues seem to be resolved.
