### ISSUE TITLE
Add support for splitting layout constraints

### ISSUE THREAD

**Issue by mpokorny** [StanfordLegion/legion#1365]
I'm working on an application that could really use splitting layout constraints. Unfortunately, I just encountered the following error (on control-replication branch)
`[0 - 7f990a5f3800]    0.061030 {6}{runtime}: [fatal 544] LEGION FATAL: Splitting layout constraints are not currently supported (from file runtime/legion/legion_instances.cc:4642)`
Is implementation of  splitting layout constraints on the roadmap? A critical third-party library that I'm trying to use has specific layouts that are required, at least one of which would be counter-productive to maintain outside of that library. Having this feature implemented would provide a real benefit for my application.

**Comment by lightsighter** [comment]
Yes, was just waiting for someone to come along and ask for it. Can you prototype a small test case that shows how you'd like to use the splitting constraints interface?

**Comment by mpokorny** [comment]
I'll see about pulling out a small test case from my application code. In the meantime, to get a sense of my use case, have a look at [this README](https://git.astron.nl/RD/tensor-core-correlator/-/blob/master/README.md), which shows the "time" axis of the `Samples` array split as `NR_SAMPLES_PER_CHANNEL / NR_TIMES_PER_BLOCK` and `NR_TIMES_PER_BLOCK`. In the rest of my application I don't want to carry around the extra dimension that I'd need without the splitting constraint because that's an implementation detail that has no fundamental reason to exist.

**Comment by mpokorny** [comment]
I think that my case here is simpler than what you described. What I need is more like splitting
```
A B C D
E F G H
I J K L
M N O P
```
in only the column dimension to create a layout in memory like
```
A B E F I J M N C D G H K L O P
```
In general terms, the region has dimensions T(ime), R(eceiver), C(hannel), P(olarization). When first materialized in host memory, the preferred layout would be something like (in short to long stride order) `T, P, C%N, R, C/N` for some value of `N`. Later, for the purposes of the library I want to use, the layout in GPU memory would have to be `T%128, P, R, T/128, C`. Am I mistaken that Legion layout splitting constraints would be applicable here?

**Comment by lightsighter** [comment]
I think you did almost the same layout as what I showed above, but you went column-major across the tiles, and then row-major within the tiles, but fundamentally it does seem like you do need this actual layout. For my understanding, do you need this layout for correctness, or is it for performance reasons?

**Comment by lightsighter** [comment]
Also, would this kind of layout be ok (column-major both across and within tiles)?

```
A E B F I M J N C G D H K O L P
```

**Comment by mpokorny** [comment]
As for whether the layout is needed for correctness or performance, it's a bit of both. The third-party library has no flexibility in terms of the layout, so that particular layout is required for correctness in that sense. From what I understand, the layout demanded by the library is needed for performance, so while in principle I might be able to change it -- the code is open source -- the functionality is definitely one of the top two bottlenecks in the application and is therefore a critical component in terms of overall performance, and I'm not sure I want to spend my time tinkering with it if I don't have to.

As for the alternative layout you suggested, it might work for the first of the two layouts I referenced previously (using `T, R, C, P`), but I'm not completely certain (there it's a question of performance only). However, it would not work for the second layout, i.e, the one required by the third-party library.

Finally, fyi, I had a few other bugs to fix at the time that I raised this issue, but I'm now done with those and I will work on getting you some sort of example code.

**Comment by mpokorny** [comment]
As for whether the layout is needed for correctness or performance, it's a bit of both. The third-party library has no flexibility in terms of the layout, so that particular layout is required for correctness in that sense. From what I understand, the layout demanded by the library is needed for performance, so while in principle I might be able to change it -- the code is open source -- the functionality is definitely one of the top two bottlenecks in the application and is therefore a critical component in terms of overall performance, and I'm not sure I want to spend my time tinkering with it if I don't have to.

As for the alternative layout you suggested, it might work for the first of the two layouts I referenced previously (using `T, R, C, P`), but I'm not completely certain (there it's a question of performance only). However, it would not work for the second layout, i.e, the one required by the third-party library.

Finally, fyi, I had a few other bugs to fix at the time that I raised this issue, but I'm now done with those and I will work on getting you some sort of example code.

**Comment by mpokorny** [comment]
Here's a real simple example that captures the essence of what I'm looking for using `SplittingConstraint`: https://gitlab.com/martin_pokorny/split. Let me know if you have any questions.

**Comment by lightsighter** [comment]
That's quite odd that they want column major across the tiles and row major within the tiles. Strange, but ok, I think our dimension ordering constraint is already general enough to handle that. 

I'll look at the code sample and try to prototype something before the end of the year when I go on vacation.

One more question: we've been doing these little examples in 2D, how many dimensions does the actual application need for this splitting?

**Comment by mpokorny** [comment]
I updated the example code to more accurately represent what I'd like to do, ultimately, in my application. You'll find that the example uses 4D arrays, same as my actual application. As for your comment about the tiling, the way we've discussed it here might be misleading, but the example I hope correctly represents the layout.

One thing that I haven't tried to represent is a variation with a splitting constraint on the "source" array in the example, but different than that on the "destination" array. I can easily provide that if you'd like.

Thanks for agreeing to work on this so quickly!

**Comment by lightsighter** [comment]
I'm slightly changing the interface for this to get rid of the "inner" and "outer" dimensions. Instead, we'll just specify they normal dimension ordering using ordering constraints (e.g. the ordering inside the tiles), and then any tiling occurs with the splitting constraints just naming normal dimensions that are being tiled. I'm probably also going to rename `SplittingConstraint` to `TilingConstraint`. Nobody has written any code to this API yet because it's unimplemented so that shouldn't break anything. 

In terms of your example, I made a couple of changes that I think reflect more accurately what you were trying to accomplish. Let's start with this statement:

> T(ime), R(eceiver), C(hannel), P(olarization)

I'm assuming those are the dimensions in order, so then we will have the following mapping:

```
DIM_X : Time
DIM_Y : Receiver
DIM_Z : Channel
DIM_W: Polarization
```

> the preferred layout would be something like (in short to long stride order) T, P, C%N, R, C/N for some value of N.

If that is the case, we'll now write the ordering constraint for each tile like this:

```
    OrderingConstraint order(true/*contiguous*/);
    order.ordering.push_back(LEGION_DIM_X); // Time has smallest stride
    order.ordering.push_back(LEGION_DIM_W); // Polarization has second smallest stride
    order.ordering.push_back(LEGION_DIM_Z); // Channel has third smallest stride
    order.ordering.push_back(LEGION_DIM_Y); // Receiver has largest stride
    order.ordering.push_back(LEGION_DIM_F); // You only have one field in this example so doesn't matter
```

And then in order to express the tiling along the channel dimension we'll add a tiling constraint just on that dimension:

```
   TilingConstraint split(LEGION_DIM_Z, BLOCK_SIZE); // Tiling on the Channel dimension (Z)
```

The whole code:

```
LayoutConstraintID xcorr_layout;
  {
    OrderingConstraint order(true/*contiguous*/);
    order.ordering.push_back(LEGION_DIM_X);
    order.ordering.push_back(LEGION_DIM_W);
    order.ordering.push_back(LEGION_DIM_Z);
    order.ordering.push_back(LEGION_DIM_Y);
    order.ordering.push_back(LEGION_DIM_F);
    TilingConstraint tilet(LEGION_DIM_Z, BLOCK_SIZE);
    LayoutConstraintRegistrar registrar;
    registrar.add_constraint(order).add_constraint(tile);
    xcorr_layout = Runtime::preregister_layout(registrar);
  }
```

This will produce an instance with tiles which are laid out with the ordering constraints above, with each tile handling a `BLOCK_SIZE` chunk of the channel dimension. Is that what you were going for? If so, do you mind updating the example code?

**Comment by lightsighter** [comment]
One other thing that you'll need to fix in your example is the use of the accessors in the `reformat_samples_task`. Currently you're just using a normal `AffineAccessor` in that task:

```
  const FieldAccessor<
    WRITE_DISCARD,value_t,4,coord_t,
    Realm::AffineAccessor<value_t,4,coord_t>>
    acc_out(regions[1], FID_VALUE);
```

Unfortunately, that will actually fail at runtime with an instance that is laid out using a tiling constraint because the data is most definitely not affine (it's tiled). 😉 To work around this you have two options. First, you can switch to using a `MultiAffineAccessor`. The interface for the `MultiAffineAccessor` is the same as a normal `AffineAccessor` so you can do all the same things with it (e.g. random accesses into the instance), but the performance properties are worse because it needs to search through all the tiles to figure out which one you're trying to access rather than just doing pointer arithmetic. The second option is to structure your loops in such a way as to explicitly loop over the tiles in the instance. You can use the Legion `PieceIterator` to iterator over the "pieces" (tiles) in your instance:

https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion.h#L3277-3332

And then for each piece, you can create a normal `AffineAccessor` and loop over all the points in that piece/tile and do you copies. A rough pseudo code:

```
PieceIterator pit(physical_region, field);
for (piece in pit)
    FieldAccessor<AffineAccessor> acc(physical_region, *pit);
    for (point in *pit)
        // do stuff
```

That approach will be much higher performance, but with the additional looping complexity.

**Comment by mpokorny** [comment]
As far as my one example is concerned, your proposed changes would be fine. However, I've got a different use case with a layout that I think could be expressed using the "old" `INNER` and `OUTER` dimensions, but not using the proposed API. 

The example is for a two-dimensional convolution function evaluation in which the convolution function kernel is over-sampled relative to the grid on which it is evaluated. I'll express this here in only one dimension, with an oversampling factor of 4, whereas in the real application there are two dimensions, both over-sampled equally by a factor of several tens. Let's say that the full support of the over-sampled function is {0, 1,...,11}. Then re-label the indices as follows
`0.0, 0.1, 0.2, 0.3, 1.0, 1.1, 1.2, 1.3, 2.0, 2.1, 2.2, 2.3, 3.0, 3.1, 3.2, 3.3`. The access pattern in the kernel that evaluates this function uses only those indices with a constant value to the right of the decimal point, so an optimized layout might be `0.0, 1.0, 2.0, 3.0, 0.1, 1.1, 2.1, 3.1, 0.2, 1.2, 2.2, 3.2, 0.3, 1.3, 2.3, 3.3` .

I think that in the old API, this layout could be written `{LEGION_OUTER_DIM_X, LEGION_INNER_DIM_X}` (with a `SplittingConstraint` value of 4), whereas in the new API, the order of `INNER` and `OUTER` is assumed to be the opposite. In the real use case, this would end up being something like `{LEGION_OUTER_DIM_X, LEGION_OUTER_DIM_Y, LEGION_INNER_DIM_X, LEGION_INNER_DIM_Y, LEGION_DIM_Z}` (`Z` representing yet more dimensions) and `SplittingConstraint` values of 30 in both `LEGION_DIM_X` and `LEGION_DIM_Y`. In this case, the order of `X` and `Y` might depend on GPU vs CPU. In previous work, I confirmed that this sort of layout is critical to achieve good performance in this kernel; if I have to, I'll construct this layout explicitly, but it would be great if Legion could do it for me.

**Comment by lightsighter** [comment]
The new interface I'm proposing is functionally equivalent to the old one. I think we might have a misunderstanding about what "inner" and "outer" dimensions mean and the semantics they would support are, which is understandable since I never bothered to actually write down what they mean and what you're allowed to do with them before. 😅 The way that "inner" and "outer" were meant to be interpreted are that "inner" dimension ordering specifies the order of a tiled dimensions inside a tile, and the "outer" dimension ordering specifies the order in which tiles are laid out with respect to each other. In particular, Legion would have always enforced that all inner and normal (un-tiled) dimensions come before all outer dimensions in the ordering. That way you get the layout of all the dimensions inside a tile, followed by a description of how to layout the tiles themselves. In the new version of the interface, the `OrderingConstraint` will just capture the order of dimensions inside a tile, while the order in which you specify the `TilingConstraints` will specify the order we walk over dimensions for laying out the tiles.

In the case of your example, you're effectively trying to express a "transpose" on what Legion thinks is a 1-D index space. Unfortunately, Legion (and more importantly Realm) currently doesn't have any machinery for actually being able to describe that kind of a layout inside of a dimension at the moment; we assume you always want to layout all the elements inside of a dimension in order currently. In your example you want a permutation of those elements even inside a single dimension (a structured permutation, but a permutation nonetheless). Now, if you actually did tell Legion that those indices are organized as a 2-D index space, then we can definitely achieve the layout that you're looking for since it's easy to express whether we layout dimension X or Y first with the current constraints. 

As an alternative, one thing you can do with Legion to access a 1-D index space as though it is a 2-D layout, is to specify an [affine transform when you create the field accessor](https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion.h#L2629). That will allow you to index into the accessor using 2-D points that are then mapped down to the 1-D index space of the instance using the transform that you provide (importantly we'll fold that transform into the strides of the accessor inside the constructor so you don't pay for evaluating the affine transform on every access). I think this should provide the functionality that you're looking for, but it might not generate the pattern of memory accesses that you were originally trying to achieve since the elements are still laid out in their 1-D order.

**Comment by mpokorny** [comment]
Understood --- I figured that inferring semantics for an API without an implementation was risky, so your comments are no real surprise. I think that your new API is a bit clearer in this regard, as well. Overall, then, your changes look good to me. Thanks for the hints on the accessors and/or iterators that I'll need to use, too.

In other projects I've added dimensions to the convolution kernel arrays to get the desired layout, so that shouldn't present me with any significant issues. The only downside is the growth in the number of dimensions, where in this case the number of dimensions will go from 4 to 6, but that's still well within the range of what Legion can express.

**Comment by mpokorny** [comment]
How would tiling in multiple dimensions work under the new API? For my previous example, let's say that both the `Time` and `Channel` dimensions are tiled
```c++
LayoutConstraintID xcorr_layout;
  {
    OrderingConstraint order(true/*contiguous*/);
    order.ordering.push_back(LEGION_DIM_X);
    order.ordering.push_back(LEGION_DIM_W);
    order.ordering.push_back(LEGION_DIM_Z);
    order.ordering.push_back(LEGION_DIM_Y);
    order.ordering.push_back(LEGION_DIM_F);
    TilingConstraint tile_z(LEGION_DIM_Z, BLOCK_SIZE_Z);
    TilingConstraint tile_x(LEGION_DIM_Y, BLOCK_SIZE_X);
    LayoutConstraintRegistrar registrar;
    registrar.add_constraint(order).add_constraint(tile_z).add_constraint(tile_x);
    xcorr_layout = Runtime::preregister_layout(registrar);
  }
```
Whereas in the old API the "outer" dimensions were explicit, since they no longer appear, is there a rule for the ordering of tiles in multiple tiled dimensions? In other words, previously I could write `{LEGION_INNER_DIM_X, LEGION_INNER_DIM_Z, LEGION_DIM_Y, LEGION_OUTER_DIM_X, LEGION_OUTER_DIM_Z}` or `{LEGION_INNER_DIM_X, LEGION_INNER_DIM_Z, LEGION_DIM_Y, LEGION_OUTER_DIM_Z, LEGION_OUTER_DIM_X}`, but that choice would not exist in the new API, right? Also, it's unclear to me where the "outer" dimensions go relative to other un-tiled dimensions (for example, `Y` above).

**Comment by mpokorny** [comment]
How would tiling in multiple dimensions work under the new API? For my previous example, let's say that both the `Time` and `Channel` dimensions are tiled
```c++
LayoutConstraintID xcorr_layout;
  {
    OrderingConstraint order(true/*contiguous*/);
    order.ordering.push_back(LEGION_DIM_X);
    order.ordering.push_back(LEGION_DIM_W);
    order.ordering.push_back(LEGION_DIM_Z);
    order.ordering.push_back(LEGION_DIM_Y);
    order.ordering.push_back(LEGION_DIM_F);
    TilingConstraint tile_z(LEGION_DIM_Z, BLOCK_SIZE_Z);
    TilingConstraint tile_x(LEGION_DIM_Y, BLOCK_SIZE_X);
    LayoutConstraintRegistrar registrar;
    registrar.add_constraint(order).add_constraint(tile_z).add_constraint(tile_x);
    xcorr_layout = Runtime::preregister_layout(registrar);
  }
```
Whereas in the old API the "outer" dimensions were explicit, since they no longer appear, is there a rule for the ordering of tiles in multiple tiled dimensions? In other words, previously I could write `{LEGION_INNER_DIM_X, LEGION_INNER_DIM_Z, LEGION_DIM_Y, LEGION_OUTER_DIM_X, LEGION_OUTER_DIM_Z}` or `{LEGION_INNER_DIM_X, LEGION_INNER_DIM_Z, LEGION_DIM_Y, LEGION_OUTER_DIM_Z, LEGION_OUTER_DIM_X}`, but that choice would not exist in the new API, right? Also, it's unclear to me where the "outer" dimensions go relative to other un-tiled dimensions (for example, `Y` above).

**Comment by lightsighter** [comment]
> since they no longer appear, is there a rule for the ordering of tiles in multiple tiled dimensions?

Yes, the order in which the (soon-to-be) `TilingConstraints` for individual dimensions appear in [this vector](https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion/legion_constraint.h#L729) will define the order in which tiles are laid out by walking along those dimensions from fastest-to-slowest for the tiles (just like inside the `OrderingConstraint`).

> Also, it's unclear to me where the "outer" dimensions go relative to other un-tiled dimensions (for example, Y above).

Dimensions that you don't tile don't have any bearing on the layout of the tiles relative to each other. Consider a 3-D array that you tile along the X and Y axes, but not along the Z axis. Inside of each tile, you need to specify the order in which to layout all three dimensions. However, when deciding what order to put the tiles in memory, you don't need to consider the Z axis at all. You just need to put tiles in order based on their X and Y coordinates; all the tiles already contain all the elements in the Z dimension for their subset of the X and Y elements because the Z dimension wasn't tiled.

**Comment by lightsighter** [comment]
@mpokorny [Merge request 694](https://gitlab.com/StanfordLegion/legion/-/merge_requests/694) with support for tiling constraints has been merged into the master branch of Legion and also upstreamed to control replication. There's also a [slightly modified example](https://gitlab.com/StanfordLegion/legion/-/blob/master/examples/tiling/tiling.cc) inspired from your original proposal that shows how the tiling constraints work. Let me know if you have any issues using the tiling constraints, but I'm closing the issue since they all appear to be working as far as I can tell.

**Comment by elliottslaughter** [comment]
@lightsighter Did you forget to update the C API?

https://gitlab.com/StanfordLegion/legion/-/blob/control_replication/runtime/legion/legion_c.h#L5655-5672

**Comment by lightsighter** [comment]
Done

**Comment by mpokorny** [comment]
Thanks, @lightsighter. I'm just getting around to trying this out in my code. I have one question for you at this time. One of the main reasons that I need tiled layouts is to use a third-party library which uses an array with a tiled layout. The library has an API that wants a pointer to the beginning of the array for all tiles at once. Is it correct to obtain such a pointer by using a `PieceIterator` and getting the pointer for the start of the array through a `FieldAccessor` for the first tile?

**Comment by lightsighter** [comment]
> Is it correct to obtain such a pointer by using a PieceIterator and getting the pointer for the start of the array through a FieldAccessor for the first tile?

Assuming you did the layout constraints correct, then it should work the way that you want. Anytime you get a raw pointer though, the onus is on you for correctness.
