### ISSUE TITLE
Proposed candidate update algorithm for equivalence sets

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#1453]
@lightsighter asked me to write this down during the Legion meeting, so here we go.

Every child $C$ has a score $S$ and a timestamp $T$. There is also a "global" timestamp $G$. (I put global in quotes because it's global only among a set of candidates, it is *not* global across unrelated region trees.) There is also a global rate of change which I'd suggest setting at $R=0.99$ or something similar.

Every time you see a new candidate $C_i$:

  * $S_i := R^{G-T_i}S_i + 1$
  * $G := G + 1$
  * $T_i := G$

There are a few different ways you could trigger the reevaluation of the candidates, either every $N$ increments of $G$, or you could keep a counter on each candidate and do it when a given candidate has been incremented some number of times.

At any rate, when you go to reconsider the candidates, you recompute their scores. To do this, for each candidate:

  * $S_i := R^{G-T_i}S_i$
  * $T_i := G$

This is the same as the algorithm above except we do not increment the score, i.e., it updates the exponential dropoff (and must update the timestamp to match, to avoid doing this multiple times) but otherwise does not increment anything.

At that point you can apply a threshold, looking for a candidate that has the highest score, possibly by a ratio (e.g., the best candidate must have a score $2\times$ higher than the next highest, or something like that).

**Comment by lightsighter** [comment]
Do you have a link for where you got this formula from? I'm especially curious how they chose the `+1`. I understand what the `R` is doing, but it's unclear how `R` and the `+1` interact. You can change them to produce quite different effects to scores over time.

**Comment by elliottslaughter** [comment]
The formal name for this is exponential moving average. It's a standard technique for measuring movement in the stock market. In the typical cases where you see it, you're looking at stocks, so instead of `+1` you'll be taking the actual price of the stock. I used `1` here because just because you're counting uses, i.e., this is the exponential decay of the usage count. I picked 0.99 out of thin air, so there's no magic about that except how fast you want it to decay.

There is a short (not super helpful) article on Wikipedia about it:

https://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average

**Comment by lightsighter** [comment]
I'm familiar with EWMA. I guess you're just using values of 1 here at different points in time to keep the time series across the candidates comparable.

Here is a little Python script with a proposed implementation that I've found that seems to minimize changes due to random fluctuations. All the candidates here should be uniformly distributed in their arrivals which should tend to converge to not many changes throughout the run.

```
import math
import random

bump = 1.0
weight = 0.99
candidates = 5
test_frequency = 256
hysteresis = math.sqrt(candidates)
steps = 1000000

scores = [0.0] * candidates
times = [0] * candidates

for time in range(steps):
    x = random.randint(0,candidates-1)
    scores[x] = math.pow(weight,time-times[x])*scores[x] + bump 
    times[x] = time
    if time > 0:
        if time % test_frequency == 0:
            for x in range(candidates):
                scores[x] = math.pow(weight,time-times[x])*scores[x]
                times[x] = time
            high = max(scores)
            if hysteresis*scores[current] < high:
                print("CHANGE "+str(time)+" current="+str(scores[current])+" high="+str(high))
                print(scores)
                current = scores.index(high)
    else:
        current = x
            
print(scores)
```

**Comment by lightsighter** [comment]
Here's the commit that adds support for this in the `shardrefine` branch:

https://gitlab.com/StanfordLegion/legion/-/commit/0edb630f9fa15d609ddb57c999716b99f25df978

**Comment by lightsighter** [comment]
Going to go ahead and close this since we're getting ready to merge the shardrefine branch. We actually ended up using a simpler algorithm than what is specified here as the most recent shardrefine changes allow us to use any partition the user might choose to use for a refinement, which means we can lag the execution when deciding to make refinements instead of needing to front-run it. This means our algorithms are much simpler and change refinements less frequently but without the scaling issues that we would have had before if we hadn't picked the right refinement the first time.
