### ISSUE TITLE
How to Apply Realms to Clusters

### ISSUE THREAD

**Issue by AngryBear2** [StanfordLegion/legion#1480]
Hello, about realm, I'm a rookie. When I read two realm-related papers in [](https://legion.stanford.edu/publications/), it seems that realms provide parallelism in clusters. When I run the official example 

> legion/examples/realm_saxpy

, I use a cluster of three machines. But only three machines were given the code to execute separately, and they didn't cooperate. The following execution mode is used:
`mpirun -np 3 -hostfile hostfile_3_slots_1 ./realm_saxpy -i 3`
Is there a problem with the execution mode or the realm does not support the functions on the cluster? If I want to run this demo on the cluster, what else should I do?

**Comment by eddy16112** [comment]
You should not see the program runs on three nodes, I guess you did not compile realm with GASNet enabled. Actually, even if you enable GASNet, you won't see any task parallelism across nodes in this example, because all sappy tasks are running on the first CPU core or the first GPU if GPU is enabled. 
https://github.com/StanfordLegion/legion/blob/stable/examples/realm_saxpy/realm_saxpy_cpu.cc#L397
The Legion saxpy example provides task parallelism across nodes. https://github.com/StanfordLegion/legion/blob/stable/tutorial/07_partitioning/partitioning.cc

**Comment by lightsighter** [comment]
Right, if you want to change the mapping in Realm, you'll need to modify the code to launch the tasks on different processors in the Realm machine model. The saxpy example is designed to be pedagogical so it doesn't contain the additional logic to dispatch tasks for lots of different kinds of machines.
