### ISSUE TITLE
profiler: improve the error message for the rust profiler when parsing logs

### ISSUE THREAD

**Issue by eddy16112** [StanfordLegion/legion#1602]
When parsing the wrong version of profile logs, if any logging statement is changed, we will see the following errors when using the rust profiler:
```
thread '<unnamed>' panicked at 'no entry found for key', src/serialize.rs:964:19
```
However, it is impossible to tell which logging statement is wrong from the error message. If using the python profiler, we could see a better error message:
```
TypeError: State.log_copy_info() got an unexpected keyword argument 'num_hops'
```
It tells us the error comes from the CopyInfo logging statement, and the `num_hops` does not belong to it. 
I think the rust profiler should provide a better error message. I have attached a log file for reproducing the error. 
[legate_0.prof.zip](https://github.com/StanfordLegion/legion/files/13384425/legate_0.prof.zip)

**Comment by elliottslaughter** [comment]
The error could be slightly better, but not that much. We're trying to parse the next log statement, which means getting the ID for that logger and matching it to a known logger statement. That lookup is what fails.

We could make it say "unknown logger statement <ID>", but that won't be helpful. Because the file already failed to parse, we have no idea where we are. We're not even at an ID, so printing it isn't helpful. It's just random garbage.

I think the most helpful thing we could print would be:

```
Failed to parse log files. This usually means the Legion version is out of sync with legion_prof.
```

Anyway, if we implement #1603 we can make a dedicated error which should make this go away.

**Comment by elliottslaughter** [comment]
We now record a version number in the logs.
