### ISSUE TITLE
HDF5 fails to create new file

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#161]
`runtime->attach_hdf5` fails to create a new HDF5 file with the error "No such file or directory" when using `LEGION_FILE_CREATE` (on a file that does not exist). My understanding is that this API should create the file when it does not exist. Is that true?

I created a minimal Regent file to show the failure:

https://github.com/StanfordLegion/legion/blob/master/language/tests/regent/run_pass/attach_hdf5.rg

The relevant line is:

```
attach(hdf5, r.{a, b, c}, filename, regentlib.file_create)
```

(The form `regentlib.file_create` is equivalent to `LEGION_FILE_CREATE`, and `attach(hdf5...)` calls `runtime->attach_hdf5(...)`.)

To reproduce the error, run:

```
cd legion/language
USE_HDF=1 ./install.py --debug
./regent.py tests/regent/run_pass/attach_hdf5.rg
```

And the error is:

```
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 139998381197056:
  #000: ../../../src/H5F.c line 1586 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5F.c line 1275 in H5F_open(): unable to open file: time = Tue Aug 16 17:39:17 2016
, name = '/tmp/lua_XWabaH.hdf', tent_flags = 1
    major: File accessibilty
    minor: Unable to open file
  #002: ../../../src/H5FD.c line 987 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: ../../../src/H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = '/tmp/lua_XWabaH.hdf', errno = 2, error message = 'No such file or directory', flags = 1, o_flags = 2
    major: File accessibilty
    minor: Unable to open file
```

It's true that `/tmp/lua_XWabaH.hdf` doesn't exist, but that's rather the point: I'm passing `LEGION_FILE_CREATE` with the intention that the file is supposed to be created from scratch. Is that not how this API works?

**Comment by jiazhihao** [comment]
Elliott,

I got the following error when I try to run the test case. Any easy fix for this?

In file included from <buffer>:1:
In file included from /local/home/zhihao/legion_github/runtime/legion/legion_c.h:31:
In file included from /local/home/zhihao/legion_github/runtime/legion/legion_config.h:21:
/usr/include/limits.h:123:16: fatal error: 'limits.h' file not found
# include_next <limits.h>
               ^
compilation of included c code failed

stack traceback:
	src/terralib.lua:3382: in function 'includecstring'
	...home/zhihao/legion_github/language/src/regent/std_base.t:26: in main chunk
	[C]: in function 'require'
	/local/home/zhihao/legion_github/language/src/regent/std.t:18: in main chunk
	[C]: in function 'require'
	...home/zhihao/legion_github/language/src/regent/builtins.t:17: in main chunk
	[C]: in function 'require'
	/local/home/zhihao/legion_github/language/src/regent.t:17: in main chunk
	[C]: at function: 0x403fcef0
	[C]: in function 'xpcall'
	src/terralib.lua:4216: in function <src/terralib.lua:4215>

**Comment by elliottslaughter** [comment]
Hm, ok. Could you try on sapling to see if you still get this?

We can also debug this to figure out the root cause, but it's almost certainly not related to the main issue. What system are you on (e.g. is this OS X)?

**Comment by jiazhihao** [comment]
I finally found the issue. The current implementation supports read-only and read-write access to an existing HDF file but doesn't support creating a previously non-exist HDF file. (Through, we can support creating normal file with Legion format.)

This is mainly because we need data type information to create HDF files, but that information is currently missing in the Legion runtime. @lightsighter is there any easy fix to add type information into attach_hdf interface?

=======================================================================
As for the compilation error, I also tried on sapling and got the exact same error message. It seems the error is related to the include paths for gcc.

Elliott, can you try the following command line and tell me the output:

gcc -xc -E -v -

**Comment by streichler** [comment]
My recollection is that we consciously chose to leave file creation out of the attach_hdf5 interface for exactly this reason, and just ask the parent application to do HDF5-metadata related things on its own, since those are rarely data-parallel anyway.  I propose we remove the LEGION_FILE_CREATE option here to avoid confusion in the future.

Hopefully Terra will make it relatively easy to get bindings for libhdf5 in Regent...
