### ISSUE TITLE
legion_prof_rs: assertion failed: running_stop <= start

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#1770]
I built legate with the latest legion master and I am seeing this when I try to generate an archive profile:

```
assertion failed: running_stop <= start
```

Logs are here: https://s3df.slac.stanford.edu/people/seshu/xpplx5720/prof_logs/

**Comment by syamajala** [comment]
I am able to at least view the profiles with `legion_prof view` but hovering over any boxes on the cpu causes the viewer to crash.

**Comment by elliottslaughter** [comment]
The relevant code appears to have been added in 216343416d19d31bdf297328c7f1c681ac02ea27 by @lightsighter and is part of the critical path infrastructure. Presumably some invariant is being violated but I'm not sure I understand exactly what.

In the meantime you might be able to work around with `-lg:prof_no_critical_paths`.

**Comment by lightsighter** [comment]
I need a time range to look at that will cause the profiler to crash on those profiles. I haven't found one yet.

**Comment by elliottslaughter** [comment]
Here's a command line that crashes:

```
cargo run --release --all-features -- archive legate_*.prof
```

**Comment by syamajala** [comment]
Between 2 and 22 seconds. If you hover on the purple box stacked on top of the green boxes on c1 it should crash. 

![2024-10-08-131546_1918x1174_scrot](https://github.com/user-attachments/assets/92dfa7c3-c94a-49e4-b812-908f96673786)

**Comment by lightsighter** [comment]
So the problem seems to be that Realm is allowing two tasks to be "running" at the same time on the same CPU processor (see screen shot: the purple is the hdf task and the green is the top-level task). I think this is because this is an implicit top-level task and we've just happened to associate that top-level task with this processor. The profiler code definitely won't work with two tasks having running ranges that overlap, so we need to handle this case of implicit top-level tasks correctly and have it not be part of this computation.
<img width="559" alt="Screen Shot 2024-10-08 at 11 08 50 AM" src="https://github.com/user-attachments/assets/151e1be0-5927-40ec-aab3-9ad2501c0988">

**Comment by elliottslaughter** [comment]
This sounds like a downstream consequence of the design decisions we made in #1477. I suppose we could just fix this by adjusting the profiler not to count implicit top-level tasks as running, but is that really what we want? At one point we'd mentioned creating actual Realm processors for implicit top-level tasks, is that going to happen at some point?

**Comment by lightsighter** [comment]
So right now we do associate a processor with every implicit top-level task because of the need to perform mapper calls for that implicit top-level task (to handle failure modes outlined in #1477). I'm inclined to maintain that relationship in the profiler because it actually has performance implications for which mappers handle calls for the implicit top-level task and I want users to be able to see that. I think the right answer here is just to ignore implicit top-level tasks in this particular bit of code that is trying to compute what the previous executing task was since they obviously weren't really executing on the same processor. In some sense that doesn't prevent bugs like this from recurring since it means you always have to handle implicit top-level tasks specially in the profiler anywhere that you might assume that there is exactly one task running on a processor at a time. I don't see a better way of handling that though that still maintains the relationship of the implicit top-level task with the mapper of a particular processor.

**Comment by lightsighter** [comment]
Ok, now I'm waffling on my answer from before because we actually need this to work in both directions. It's not enough to know that we're looking for the earliest executing previous task from a non-implicit-top-level task and ignoring the implicit top-level task. We also need to not look for previous executing for the running ranges of an implicit top-level task. I feel like we might need to render implicit top-level tasks on custom processor (with I/O processor kind).

**Comment by lightsighter** [comment]
I've taken the approach of synthesizing a custom I/O processor handle for rendering all implicit top-level tasks on for a given process. From now on all the implicit top-level tasks will appear on this "I/O" processor and nothing else will appear on that I/O processor (it is distinct from all other I/O processors). We can decide to mark this processor specially as an implicit task processor if we want to but I haven't taken that step yet.
https://gitlab.com/StanfordLegion/legion/-/merge_requests/1487

@ipdemes for visibility

**Comment by lightsighter** [comment]
Merged.
