### ISSUE TITLE
Failing HDF5 tests

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#218]
I only noticed this today when Zhenglin started using HDF5. Our HDF5 test has bitrotted, and several other relatively simple tests are not working. I already fixed one latent bug in the Regent compiler.

I have added a new HDF5 section under `language/tests/hdf5` and adding this to gitlab so we can track these tests on an ongoing basis.

I don't know who's fault this is but I'm assigning this to Zhihao until we figure out what's going on.

# Failing tests

  * Corrupt data when re-opening an HDF5 file:

        $ ./regent.py tests/hdf5/run_pass/attach_hdf5.rg
        test 2
        test 3
        test 4
        [0,0,0]: a mismatch - 2000 3000
        [1,0,0]: a mismatch - 2001 3001
        [2,0,0]: a mismatch - 2002 3002
        [3,0,0]: a mismatch - 2003 3003
        ...
        assertion failed: test failed

  * Error when opening an HDF5 file read-only:

        $ ./regent.py tests/hdf5/run_pass/attach_hdf5_read_only.rg
        WARNING: Attach invalidates region contents. DO NOT attempt to access region after using attach.
        WARNING: Detach invalidates region contents. DO NOT attempt to access region after using detach.
        test 1
        HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 140351919417088:
          #000: ../../../src/H5Dio.c line 234 in H5Dwrite(): can't prepare for writing data
            major: Dataset
            minor: Write failed
          #001: ../../../src/H5Dio.c line 366 in H5D__pre_write(): can't write data
            major: Dataset
            minor: Write failed
          #002: ../../../src/H5Dio.c line 635 in H5D__write(): no write intent on file
            major: Dataset
            minor: Write failed
        terra: /home/elliott/legion/runtime/realm/hdf5/hdf5_internal.cc:312: void Realm::HDF5::HDF5WriteCopier::transfer_data(hid_t, hid_t, hid_t, hid_t, void*): Assertion `err >= 0' failed.

  * Error when acquiring a subregion of an attached region.

        $ ./regent.py tests/hdf5/run_pass/attach_hdf5_subregion.rg 
        WARNING: Attach invalidates region contents. DO NOT attempt to access region after using attach.
        WARNING: Detach invalidates region contents. DO NOT attempt to access region after using detach.
        WARNING: Attach invalidates region contents. DO NOT attempt to access region after using attach.
        WARNING: Detach invalidates region contents. DO NOT attempt to access region after using detach.
        test 1
        terra: /home/elliott/legion/runtime/realm/hdf5/hdf5_internal.cc:390: void Realm::HDF5::copy_rect(LegionRuntime::Arrays::Rect<DIM>, T*, Realm::RegionInstanceImpl*, Realm::HDF5::HDF5Memory::HDFMetadata*, Realm::HDF5::OASVec&) [with T = Realm::HDF5::HDF5WriteCopier; unsigned int DIM = 3u; Realm::HDF5::OASVec = std::vector<LegionRuntime::LowLevel::OffsetsAndSize>]: Assertion `mem_base' failed.

**Comment by streichler** [comment]
I'm taking a look now.  This worked at least once after it got extracted into a Realm module.

**Comment by streichler** [comment]
Regarding the first failure, I don't think test 3 (which you turned back on as part of this commit) ever worked.  Adding @lightsighter , since I think there's some HLR issue related to repeated attach/detach that I can't remember the details of.

**Comment by streichler** [comment]
Hmm...  Looks like we need @lightsighter for the second one too.  If I comment out everything but the acquire/release:
```
     attach(hdf5, r2.{a, b, c}, filename, regentlib.file_read_only)
     acquire(r2)
-    copy(r2.a, r1.a)
-    copy(r2.b, r1.b)
-    copy(r2.c, r1.c)
-    compare_regions(is, r1, r2)
+    --copy(r2.a, r1.a)
+    --copy(r2.b, r1.b)
+    --copy(r2.c, r1.c)
+    --compare_regions(is, r1, r2)
     release(r2)
     detach(hdf5, r2.{a, b, c})
```
it still fails.  It's failing because the HLR is requesting a copy from a memory instance TO the HDF5 instance, which seems to be triggered by the release operation for some reason.

**Comment by streichler** [comment]
The third test is failing because a copy is being requested from HDF5->HDF5, which isn't currently supported in Realm.  The HLR should not be requesting that copy for this test case, and is likely doing so because of the repeated-attach issue seen in the first test.

However, once that issue is worked around by removing the middle detach/attach (so that everything appears inside the same attach/detach pair), the test still fails because the subset copies from HDF5->sysmem appear to be transposing the coordinates somehow.  Assigning the bug to myself for this part and @lightsighter to comment on the rest.

**Comment by lightsighter** [comment]
Tests 1 and 2 should work now in the master branch.  The attach/detach operations hadn't been updated to compute their version numbers correctly.  The third test runs, but fails because of what looks like improper copying of data by Realm as was identified earlier.  I'll wait for @streichler to fix that first before digging in any further.

In general, multiple attach/detach of the same file in a Legion program without explicit application synchronization has undefined behavior because the runtime can't perform global dependence analysis on the file name.  In this particular case we're getting away with it because the file is being attached again to the same logical region and there are transitive dependences that make that alright.  Any other use cases, including ones with the same region but in different contexts will pretty much always result in undefined behavior.

**Comment by streichler** [comment]
I've checked in a fix for the data transposition issue.  @elliottslaughter can you double-check that things look the way you expect now?

**Comment by elliottslaughter** [comment]
Confirmed fix.
