### ISSUE TITLE
RFC: Legion Dependent Partitioning API

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#227]
Questions and comments about the new Legion dependent partitioning API

**Comment by elliottslaughter** [comment]
Re: `create_cross_product_partitions`: I don't think this interface quite serves what I need in Regent. What I really want is an option like `AUTO_GENERATE_ID`, with the additional restriction that all the created partitions will have the same color. This way, the compiler only has to remember 1 color instead of N colors, which is much more tractable. Right now I enforce this constraint at the level of the C API shim, but it's somewhat obnoxious to do this and it would be nice to remove this restriction.

**Comment by elliottslaughter** [comment]
I still don't see any part of this interface that addresses the case of arbitrary aliased partitions. At a minimum we use these in the test suite and there are things we won't easily be able to test without them. The current solution of exposing the C API to Regent users isn't great, but it's better than not having any support at all.

**Comment by lightsighter** [comment]
Documenting comments from the meeting here: create_cross_product_partitions does use the same color for all the partitions that get made.  I'll modify the interface to return the color used to name all the partitions that get made just to make this clear.

I'm actually going to modify all the deprecated partitioning call implementations to use the new partitioning calls so we can force ourselves to use them.  For things like multi-colorings that create aliased partitions, I will make a temporary region with the different entries for the elements in the multi-coloring, create a partition of the temporary region that matches the colors, and then do an image operation to project the partition onto the original index space.  We'll then have an example code showing how to create an aliased partition this way.

**Comment by lightsighter** [comment]
Depending partitioning is merged so this question no longer has any relevance.
