### ISSUE TITLE
soliciting opinions about software testing 

### ISSUE THREAD

**Issue by aheirich** [StanfordLegion/legion#239]
I would like to collect information and opinions about software testing in Legion.  Please contribute your thoughts about any of these questions or anything else:

— how complete is the coverage for correctness testing?
— same question for performance measurement
— how do these differ between the compiler, Realm, and the Runtime?
— what are the most important things that are currently untested/unmeasured?
— in some world-views you decompose your architecture into interacting components and then write unit tests for the interfaces between those components, is this a viable or productive world view for Legion?

Thanks

**Comment by elliottslaughter** [comment]
Here are my two cents:

  * how complete is the coverage for correctness testing?

    We should actually run a coverage tool, but my informal estimate would be that we've maybe got about 60-80% coverage at the moment. The way I measure this by how likely it'll be that we hit new bugs when we write new applications for Legion. It used to be that this probability was 100%---i.e. we could be sure that every new application would hit some previously unseen bug (or more realistically, multiple bugs). At this point it feels like the situation is much better. While it's not necessarily a surprise if we hit a bug when writing a new application for Legion, there's also a good chance it'll work on the first try.

    However, this is heavily skewed by feature set, so it's likely there are corners that aren't being tested adequately.

  * same question for performance measurement

    This is much more rough. We've got a basic performance testing framework, but (a) it currently only tests ~3 applications, and only on a single node. So this situation is much more like where we used to be with performance. When I go to do performance runs (for experiments) I basically expect to do some performance debugging before I'll get even halfway reasonable results. This is bad for us because it means we're doing this performance debugging on a tight deadline, and even worse for anyone outside the group who wants to take Legion and use it for something.

  * how do these differ between the compiler, Realm, and the Runtime?

    Realm has some simple tests. Legion has very little dedicated testing. Almost all of the tests are currently in the Regent test suite. Regent's test suite is comprehensive enough that I'm usually surprised if something is broken in the language itself.

    Because Regent compiles to Legion (which uses Realm), the overall effect is that we get a reasonable amount of coverage over the whole stack. But these are essentially integration tests, and Regent generates fairly specific patterns of code. Legion has a very wide API, and we're almost certainly missing large pieces of it.

  * what are the most important things that are currently untested/unmeasured?

    Anything that Regent's code generator doesn't need to or know how to generate code for. Accessors come to mind (they're irrelevant in Regent). Tracing. Static dependencies. Mapping APIs in general (even in Regent we write these in C++). Non-default layout constraints (C order, AOS, hybrid, etc.). Non-trivial uses of atomic and/or relaxed coherence and interactions between coherence modes. I'm sure there are others.

    Another point worth making is that there are a lot of cases where if you make a mistake in Legion, you'll hit an assert, but without a useful error message. This is somewhat orthogonal to your question, but also has a large impact on user experience.

  * in some world-views you decompose your architecture into interacting components and then write unit tests for the interfaces between those components, is this a viable or productive world view for Legion?

    @lightsighter will have to comment on this one, but I think the sticking point here is that since this is a parallel runtime, many bugs only reproduce with certain timing effects. A functional only test may stress all the right code paths, but not hit some interleaving which causes a problem. It's certainly worth thinking more about whether we can do this meaningfully, but so far our testing has been mostly at the integration test level because it's easier to conceive of meaningful tests at that level.

Again, just my thoughts on the situation, I'm sure others will have different perspectives on these issues.

**Comment by alexaiken** [comment]
I'll add a few thoughts.

We need people to be able to use Legion and Realm both for research and to
get real work done.  But we also have limited bandwidth for fixing bugs.
That means if a bug is blocking someone's research or work, we have to fix
it and otherwise we shouldn't spend time on it.  In fact, for now it is
fine to be completely demand-driven, not even prospecting for bugs and just
taking the reports people generate in the course of research/work.  There
are still enough of these relative to our resources for fixing them that it
isn't worth finding more.

So the real problem we need to address is regression.  We need to make sure
the tests we do have, and that we add to reproduce bugs that come up, are
run regularly.  As Elliott said, correctness testing is at the point of
being useful now, but or performance regression testing is still not what
we need.  Especially poor, because it is non-existent, is performance
regression testing at scale.  This is currently our biggest problem.

We also need to ensure that when people fix a bug that they also add tests
to or modify tests in the test suite to cover that bug.

Alex

On Sat, Apr 15, 2017 at 7:00 PM, Elliott Slaughter <notifications@github.com

**Comment by lightsighter** [comment]
Here are my comments:

* how complete is the coverage for correctness testing?

I think we cover about probably between 60-70% of the Legion runtime API with our current tests.  As @elliottslaughter pointed out this is mostly through the Regent test suite (tests are much easier to write by hand in Regent).  This does mean that any features that Regent doesn't use are not covered by the test suite.  In the past we tried to develop an automated test generator for some parts of the runtime, but the person writing the test generator didn't have close enough communication with the runtime developers to know all the right kinds of tests to generate.  One option would be to explore this path again, hopefully with better co-design.

With regards to the correctness of the runtime with respect to races and other difficult to detect phenomenon, I think we are a good ways along this path with Legion Spy.  Legion Spy isn't quite a formal verification framework, but it does a lot of good checking of the important correctness properties necessary for Legion to maintain correctness. Legion Spy has a few known holes but @TWarszawski and I have been working on the necessary improvements necessary to close them up. 

* same question for performance measurement

As @alexaiken pointed out, this is our biggest short coming.  We have almost no performance automated performance tests (except for the few the @elliottslaughter has rigged up on sapling for a few of the regent mini-apps).  Knowing that we don't regress existing codes is really important, but testing both at scale and across different machine types is really hard.  This is not something that will be fixed all at once, but will need to be incrementally improved.

* how do these differ between the compiler, Realm, and the Runtime?

Most of our tests are in the Regent test suite and they consequently end up testing both the Legion and Realm runtimes as well.  We therefore do mostly whole-stack testing of our systems.

* what are the most important things that are currently untested/unmeasured?

Performance and runtime overhead are probably the two biggest metrics that are untested/unmeasured. They are often correlated, but it would be good to know when runtime overhead goes up even if it doesn't impact performance on a given application (Legion is good at latency hiding like this, but from a developer's perspective it is good to know when a change effects something that might have performance implications for another application even if it doesn't for the one being tested).

* in some world-views you decompose your architecture into interacting components and then write 
unit tests for the interfaces between those components, is this a viable or productive world view for Legion?

I feel like the current size of the codebase for Legion and Realm and our relatively small number of developers make it intractable to write lots of good unit tests for specific components of the runtime systems.  I think it would be better to focus on whole-stack tests that exercise the system in ways we know are important, but still invest energy in tools like Legion Spy so that when something does go wrong, we at least have something that will tell us where to go looking to fix the problem so we don't have to do it by hand. (Finding bugs by hand in Legion is also mostly intractable.)

**Comment by aheirich** [comment]
closing to clean up issues
