### ISSUE TITLE
Some header names are too generic

### ISSUE THREAD

**Issue by junghans** [StanfordLegion/legion#257]
With an legion installed in `/usr` or `/usr/local`, one can make legion pick up the wrong header:
```
$ cat accessor.h
#error Wrong header
$ cat main.cpp
#define LEGION_CMAKE
#include <legion.h>

int main () {
  return 1;
}
$ g++ -I. -I/usr/include/legion -I/usr/include/realm main.cpp
In file included from /usr/include/realm/redop.h:22:0,
                 from /usr/include/realm/event.h:23,
                 from /usr/include/realm/processor.h:23,
                 from /usr/include/realm/profiling.h:27,
                 from /usr/include/realm/realm.h:23,
                 from /usr/include/legion/legion_types.h:43,
                 from /usr/include/legion/legion.h:36,
                 from main.cpp:2:
./accessor.h:1:2: error: #error Wrong header
 #error Wrong header
  ^~~~~
```

Looking at what legion installs:
```
/usr/include/accessor.h
/usr/include/activemsg.h
/usr/include/arrays.h
/usr/include/atomics.h
/usr/include/channel.h
/usr/include/channel_disk.h
/usr/include/utilities.h
```
`accessor.h`, `arrays.h`, `atomics.h` and `utilities.h` might be too generic names and should be moved to a subdirectory.

**Comment by lightsighter** [comment]
Any header files you see directly in the runtime/ directory are going to be dead in the next few months (including all the ones you see above).  Users should never need to include anything other than realm.h or legion.h by the time we are done.

**Comment by streichler** [comment]
The header_cleanup branch (initial commit fbe7ab6) moves all the real headers out of the base runtime/ directory.  For compatibility with older apps using the older Makefiles, there are still files there that redirect (with a warning) to the new locations, but cmake should not be installing them.

Rather than changing the names of header files that might conflict with other names, my plan is to make all #include paths within Legion and Realm be rellative to the root (i.e. explicitly include legion/ or realm/ in the path).  That'll come next.

**Comment by streichler** [comment]
All Legion and Realm headers are now #include'd using their full path (from the runtime root directory), which should eliminate this issue.  @junghans , when you get a chance, can you take a look and see if you agree the changes are sufficient?

**Comment by streichler** [comment]
@junghans, do you have any remaining concerns?  If not, I'll close this issue.
