### ISSUE TITLE
Drastic slowdown of task launches

### ISSUE THREAD

**Issue by krivenko** [StanfordLegion/legion#273]
Dear developers,

I am sorry for bombarding you with questions, but the issue I report here seems to completely block development of my project...

Let me consider the following problem. There is a chain (sequence) of `N` numbers. Each number, except the first one, is computed as a function of all previous numbers.
I want to store the sequence in a region, and launch a Legion task to compute each number.
Here is how I implement the algorithm:

[chain_test.cpp](https://gist.github.com/krivenko/a9cfa36ce980d50318a6a38320cccf8f)

This program works but suffers from a visible slowdown between task launches as it proceeds along the chain.

By contrast, a similar program based on futures does not take visibly more time between launches for the latter tasks.

[chain_futures_test.cpp](https://gist.github.com/krivenko/e974c67542c957924f0d63f3f2579198)

Could you explain me what's the reason for things getting slower? Is there a way to circumvent the problem? I guess it has something to do with the growing number of dependencies between tasks.

The chain example I am presenting here is a simplified version of my original two-dimensional problem.
In that program I have quadratic growth of read-only dependencies between tasks, which literary makes execution stop at some point.

Thanks in advance!

**Comment by lightsighter** [comment]
You are absolutely correct that the problem is stemming from the growing cost of the dependence analysis between tasks.  If the data being passed is actually individual numbers, futures are actually the best way to go.  Data should starting getting put into regions probably somewhere are the 100s to 1Ks+ of elements depending on the granularity of your tasks and the size of the data.  Legion's dependence analysis is really optimized for cases with coarse grain tasks and large chunks of data being stored in logical regions and subregions.  Let us know if you continue to see strange behavior and we'll try to explain it/fix it.

**Comment by krivenko** [comment]
Many thanks!
I checked your suggestion to use futures, and it was much faster indeed. Now I know how to move on.

> If the data being passed is actually individual numbers, futures are actually the best way to go.

Each data point is a structure with 10-20 numeric fields. Does this make much difference?

**Comment by lightsighter** [comment]
Futures on the order of a few hundred bytes seems reasonable in size to me.  When they start reaching ~10-100KB is probably when you want to start moving the data into a logical region.  The cross-over point will be depend on the granularity of your tasks and how expensive they are for the runtime to analyze.
