### ISSUE TITLE
Weird assertion failure when returning a serializable user-defined type from a task

### ISSUE THREAD

**Issue by krivenko** [StanfordLegion/legion#280]
I am trying to register a task, which returns a fairly complex data structure. The structure type defines three serialization methods,
```c++
size_t legion_buffer_size() const { ... }
size_t legion_serialize(void *buffer) const { ... }
size_t legion_deserialize(const void *buffer) { ... }
```
My code fails to compile with the following error message (latest Legion master):
```
/include/legion/legion.inl:2074:7: error: implicit instantiation of undefined template 'Legion::LegionStaticAssert<false>'
      LEGION_STATIC_ASSERT(sizeof(T) <= MAX_RETURN_SIZE);
```
Why does it make any sense to compute `sizeof(T)`? That size is compiler- and platform-dependent, as far as I know. And, more importantly, why bother to check if the output buffer will be much bigger after deep serialization?

**Comment by lightsighter** [comment]
The reason we set this is maximum return size is to discourage users from moving around large amounts of data by-value in Futures.  Anything of a sufficiently large size should most likely be put in a logical region.  If you would like to ignore this assertion, you can make MAX_RETURN_SIZE as large as you want in legion_config.h.  It's right at the top and easy to change.

**Comment by krivenko** [comment]
>  If you would like to ignore this assertion, you can make MAX_RETURN_SIZE as large as you want in legion_config.h

I cannot say I like this solution too much. But okay, if increasing MAX_RETURN_SIZE is safe indeed, this is my only way to go, I guess.

> The reason we set this is maximum return size is to discourage users from moving around large amounts of data by-value in Futures.

What do you call moving data by-value? Is using `legion_[de]serialize()` considered moving by-value?

Let me explain what I mean on a simple example. `sizeof(std::vector<T>)` will normally be equal to `sizeof(T*) + sizeof(size_t) + sizeof(size_t)` (data pointer + vector capacity + vector size). Sometimes you might have to add some more bytes for padding. Anyway, the total size, as computed by `sizeof(std::vector<T>)`, is very small. Nonetheless, a vector object can carry gigabytes of data. And that data will readily be moved by a wrapper you provide in `runtime/legion/legion_stl.h`.

Could it be the case that Legion does not recognize my object as serializable?

**Comment by lightsighter** [comment]
Yes, increasing the MAX_RETURN_SIZE will always be safe.

Yes, when I refer to moving data by-value, I'm referring to using the legion_[de]serialize methods to serialize and deserialize data.  This methods are required to soundly move something like a std::vector<T> in a Legion future (e.g. if the future is made on one node and then used on a different one).  Just copying the std::vector<T> by value will not be sound because, as you pointed out, it has a pointer to an actual allocation of memory (which can be very large) but that pointer is not valid on remote nodes.  

You should be able to confirm that Legion is recognizing your object as serializable by putting some print statements inside the legion_[de]serialize methods.

**Comment by krivenko** [comment]
> Yes, increasing the MAX_RETURN_SIZE will always be safe.

Thank you, this is basically all I wanted to know.
