### ISSUE TITLE
Stale Index-Space Meta-Data Results in Remote Instance Overallocation

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#34]
The low-level runtime is using stale meta-data when doing remote instance allocations which is resulting in very large over-allocations for physical regions using unstructured index spaces.  Example from mini-aero: on node 0, when looking at the element mask for an index sub-space, I see the following:

(gdb) p first_enabled_elmt
$64 = 7400448
(gdb) p last_enabled_elmt
$65 = 8222719
(gdb) p $65-$64
$66 = 822271

However, when I ask for a remote physical instance on node 1, I see the following being returned from the StaticAccess data controlled by the reservation associated with the index sub-space

(gdb) p first_elmt
$1 = 0
(gdb) p last_elmt
$2 = 13156351
(gdb) p num_elements
$3 = 13156352

I'm pretty sure the problem is that the meta-data used by the StaticAccess is not being properly updated by the IndexSpaceAllocators when allocations are being performed and so it stays fixed at the absolute maximum boundaries of the index space even when in practice they are much smaller.

**Comment by lightsighter** [comment]
Note: I tried hacking around this by requesting the full element mask, but this caused a double delete at activemsg.cc:751

**Comment by streichler** [comment]
Actually, the choice to have instances on other nodes use the full range is intentional, and due to a larger issue.  The old repo had an ill-fated branch where Elliott and I tried to turn on trimming and a bunch of other stuff broke.  The plan for dealing with this is to not allow creating instances of "mutable" index spaces - only of snapshots of them (or of their upper bounds, if allocation is enabled).

**Comment by streichler** [comment]
Closing this for now.  Will re-examine after index space changes.
