### ISSUE TITLE
Question about error 356

### ISSUE THREAD

**Issue by chamsolli** [StanfordLegion/legion#368]
Hi,

I'm trying to mimic routines in "~/legion/language/examples/circuit/circuit_dep_par2.rg" for my application. However, I wasn't able to find a solution for resolving "error 356" in my code. Would someone briefly look the code (about 70 lines) and advice me what I'm missing?

[test.rg.gz](https://github.com/StanfordLegion/legion/files/1827265/test.rg.gz)
The problem has 10 "Elem" elements and 9 "surf" elements. A "surf" element connects adjacent "Elem"s. "Elem" is divided into two partitions(from 0 to 4 and from 5 to 9). I divided "Elem" in three group - Private, Shared and Ghost as in circuit example.

Partition 0 : Private = 0,1,2,3 / Shared = 4 / Ghost = 5
Partition 1 : Private = 6,7,8,9 / Shared = 5 / Ghost = 4

When I tried to use + reduction for a "surf" element which connects "Elem" 4 and 5, I'm getting error 356.

**Comment by lightsighter** [comment]
I think this is a combination of a compiler bug and user error. You shouldn't need to specify read-only privileges on 'qShared.sum' and 'qGhost.sum' in the 'residualSurfaceCross' task if you are only going to be doing reductions to those fields. By adding those fields the compiler is promoting your privileges to 'read-write' since that is the privilege that supports both 'read-only' and 'reduction' privileges on the same field. This lead to the error that you get from the runtime about having interfering region requirements. Ideally the compiler would have caught this scenario statically as we document in (still outstanding) issue #195, but the compiler has not caught up enough yet to be able to do this which is why you get the runtime error.

All this being said, it seems that 'read-only' privileges need to be specified even though I don't think they should be. When I remove the read-only privileges the compiler hits an internal assertion which should never happen so I am assigning @elliottslaughter and @magnatelee to fix the bug. This code should be able to work with just reduction privileges.

Here is the internal compiler assertion when read-only privileges are removed on 'qShared.sum' and 'qGhost.sum':
/Users/mebauer/legion/language/src/regent/std_base.t:260: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/Users/mebauer/legion/language/src/regent/std_base.t:260: in function 'find_field_privilege'
	/Users/mebauer/legion/language/src/regent/std_base.t:288: in function 'find_task_privileges'
	...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:1212: in function 'get_privilege_field_map'
	...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:1357: in function 'stat'
	...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:1831: in function 'fn'
	src/asdl.lua:16: in function 'map'
	...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:1829: in function 'block'
	...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:1891: in function 'stat'
	...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:1831: in function 'fn'
	src/asdl.lua:16: in function 'map'
	...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:1829: in function 'block'
	...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:3319: in function <...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:3308>
	/Users/mebauer/legion/language/src/regent/passes_hooks.t:41: in function 'optimize'
	/Users/mebauer/legion/language/src/regent/passes.t:54: in function </Users/mebauer/legion/language/src/regent/passes.t:46>
	test.rg:49: in main chunk

**Comment by elliottslaughter** [comment]
As a short-term workaround for the issue, you can follow @lightsighter's advice and then run with `-fflow 0` to get around the assert in the compiler. There is a known bug when using RW privileges on statically aliased regions, but I didn't think it would occur with reductions. I'll have to take a look, and many of these RDIR bugs can be quite pernicious.

**Comment by chamsolli** [comment]
Thank you @lightsighter and @elliottslaughter. I followed your advice and additionally changed field type of "sum" to int64(not uint64). Then it worked fine. Closing the issue.
