### ISSUE TITLE
regent: Support for more expressive non-trivial projection functors

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#413]
The following snippet is a simplified version of a pattern we use in Soleil, to wrap around the domain in an index-space launch. Regent's loop optimizer cannot currently handle this pattern, which means we have to use sequential launches. This is fine for now, but might become more of an issue when we switch to DCR.

```
import 'regent'
task foo(r : region(ispace(int3d),int))
where reads writes(r) do
  for idx in r do
    r[idx] += 1
  end
end
task main()
  var r = region(ispace(int3d,{8,8,8}), int)
  fill(r, 42)
  var cs = ispace(int3d,{2,2,2})
  var p = partition(equal, r, cs)
  __demand(__parallel)
  for c in cs do
    foo(p[(c + {1,0,0} + cs.bounds.hi) % cs.bounds.hi])
  end
end
regentlib.start(main)
```

**Comment by magnatelee** [comment]
I think this kind of code is safe only conditionally when the offset is smaller than the divisor. For example, (c + 4 + N) % N will produce the same value for both c = 0 and c = 2 if N is 2. ThoughI think in general the program itself should avoid this case, letting the index parallelizer know that this is actually safe launch to optimize seems not clear to me.

**Comment by manopapad** [comment]
I agree. We only need to support this pattern when doing modulo over the loop bounds (`0 <= c < N` in your example, and `cs.bounds.hi` in the above code snippet), in which case the pattern is safe.

**Comment by elliottslaughter** [comment]
The other requirement is that the modulus must be <= the loop bounds.

We can hard code this for the case where they're equal, but the general case seems quite challenging.

**Comment by elliottslaughter** [comment]
Sorry, modulus >= loop bounds. See, I've already messed it up.

**Comment by manopapad** [comment]
I was looking at this today and realized that my code snippet is wrong. The following expression is not safe:
```
(c + {1,0,0} + cs.bounds.hi) % cs.bounds.hi
```
It should instead be:
```
(c + {1,0,0} + cs.bounds.hi+{1,1,1}) % (cs.bounds.hi+{1,1,1})
```
which is equivalent to what we actually do in Soleil:
```
var cs = ispace(int3d,{NX,NY,NZ})
for c in cs do
  foo(p[(c + {1,0,0} + {NX,NY,NZ}) % {NX,NY,NZ}])
end
```
This is starting to get pretty complex, but I don't immediately see any other (non-built-in) way to communicate to the compiler that we want to modulo over the loop bounds.

**Comment by elliottslaughter** [comment]
I believe we now have modulus that works over rectangles, right? Then we should be able to do something like `(c + {1,0,0})%cs`.

**Comment by elliottslaughter** [comment]
This is similar to what we're seeing in #607, except a different property of the loop needs to be proved. I'm inclined to add `-foverride-demand-index-launch 1` as a first step since the rabbit hole goes (potentially) quite far down.

**Comment by elliottslaughter** [comment]
As of `a5c903d448fa35abdd59ae4efd9e5e0f85615cac` we now support the flag `-foverride-demand-index-launch 1` which should make it possible to start writing these programs.

**Comment by elliottslaughter** [comment]
As of a23407b06f4d58da0d5f98626cf15c2acc2ae948 we now support a dynamic checking mode (enabled by default) that makes `-foverride-demand-index-launch 1` unnecessary in many cases. In particular, any loop of the form:

```lua
for i in ... do
  my_task(p[f(i)])
end
```

Can be analyzed dynamically as long as `p` is a disjoint partition.

One ongoing item is to support multiple projections, e.g.:

```lua
for i in ... do
  my_task(p[f(i)], p[g(i)])
end
```

I.e., `f` and `g` are both being used as projection functors on the same disjoint partition `p`, which I think is required to handle the Cholesky case.

The more general case of two partitions `p` and `q` with arbitrary aliasing probably won't be handled, since I can't see how we'd make that analysis efficient.

**Comment by elliottslaughter** [comment]
As of #1097, we now support both of the use cases in my last comment. The one restriction (as I mentioned above) is that when you have two projection functors that may be conflicting, we need those to be on the same partition (and the partition must be disjoint). I think this is the best we can reasonably do, because the checks would get very expensive otherwise.

I'm going to close out this issue because I think this covers all the use cases we've seen.
