### ISSUE TITLE
Better solution for passing information from application to mapper

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#438]
This was motivated by the way we're currently differentiating between the two simulations in 2-section cases in Soleil's mapper: we're attaching different semantic information to the regions of each simulation as we create them. According to @lightsighter, this is not what semantic information should be used for. Instead, we should be using the `MappingTagID` on the operation launcher.

One issue with the `MappingTagID` is that it's restricted to 32 bits. @lightsighter could extend the `mappable_data` interface to be accessible from the application side, so that we can attach arbitrarily large mapping tag information on each launcher:
https://gitlab.com/StanfordLegion/legion/blob/e54aa9f41a72386f8f1b9fc7ae391801b3fd42e2/runtime/legion.h#L2597-2599
https://gitlab.com/StanfordLegion/legion/blob/e54aa9f41a72386f8f1b9fc7ae391801b3fd42e2/runtime/legion/legion_mapping.h#L1693-1703

Another issue is that Regent currently does not support attaching information to task launches, so any solution that uses such an interface would require changes to Regent's syntax.

**Comment by elliottslaughter** [comment]
A couple of thoughts on alternative ways to do this. It might be worth exploring these first before jumping down the hole of implementing something new.

1. Why do you need information about the task at all? Don't you really care about the *parent* task? I'm pretty sure the mapper has an API to look up the parent. You could have the mapper attach metadata to the parent during `map_task` and then look it up when mapping the children. This seems the cleanest way to do this since it means no involvement from the application at all.

2. If there is data that absolutely has to be passed along with the task, it could be passed as an argument to the task and then looked up in the mapper. Regent has a fairly stable calling convention that shouldn't be hard to work with.

**Comment by manopapad** [comment]
1. I have two copies A and B of the same simulation created through metaprogramming and inlined in the same task. I need to copy data from A's fluid grid to B's fluid grid between fluid solves, and this was the most straightforward way to achieve that. A and B have the exact same set of regions (for the fluid grid, particles, DOM grid etc.) so I can't e.g. use the fieldspace to differentiate between them. So far as the mapper knows, the two calls `initializeTemporaries(A.fluidGrid)` and `initializeTemporaries(B.fluidGrid)` will be identical (including parent task), unless we attach some extra information to the arguments or the launch itself.

2. I could certainly do this, but I'm not happy with how task arguments are read in the mapper (or, if there is a saner way I'm not aware of it). Here's what we currently do to retrieve the (only) argument from the work tasks:
    ```
    const Config* config = static_cast<const Config*>(first_arg(task));
    ```
    where:
    ```
    static const void* first_arg(const Task& task) {
      const char* ptr = static_cast<const char*>(task.args);
      // Skip over Regent-added arguments.
      // XXX: This assumes Regent's calling convention won't change.
      return static_cast<const void*>(ptr + sizeof(uint64_t));
    }
    ```
    After retrieving the data in this way, we attempt to guard against a Regent calling convention change by doing a sanity assert. Following this convention for passing mapping info as task arguments would mean that (a) I trust that Regent's calling convention will never change, and (b) that I always put the relevant argument first on every task, because there's no way I can ever read subsequent arguments. I would feel much better about this alternative if there were some API call I could do to retrieve the arguments from Regent tasks by name (and this interface would coincidentally not break if Regent's calling convention ever does change).

**Comment by lightsighter** [comment]
The example illustrated by @manopapad is exactly why MappingTagID exists. The application often needs to provide context sensitive information to the mapper so that the mapper can differentiate between tasks that have the same arguments, but should be mapped differently.

**Comment by elliottslaughter** [comment]
So I guess we could add a syntax like:

```
var x : int = 1234
__demand(__tag(x))
some_task_call(...)
```

And for index launches:

```
var x : int = 1234
__demand(__parallel, __tag(x))
for i in ... do
  some_task_call(...)
end
```

One of the tricky points is that the first syntax can't work for index launches, because you only get one mapper tag for the whole index launch.

I could imagine making this smart enough to stuff if into the mapper tag if the value is an `int32` and into the mapper metadata otherwise.

However, using this feature will probably mess with Bishop mappers, since I believe those use mapper tags. @magnatelee will need to tell us if there is a conflict here. I realize you might not be using Bishop for Soleil specifically, but this is just an issue of having language features that are not entirely compatible.

The other thing I've been thinking about is having a way to label statements in a more first-class way. Then Bishop can use these to match against, and we can also add them to mapper tags if desired.

**Comment by magnatelee** [comment]
Bishop is currently using mapper tags to keep track of the sequence of tasks the mapper has seen so far, so there will be definitely a conflict. And the tag value is context sensitive, meaning the same call site may produce different tag values. So I don't think the first-class support for labeling statements would be helpful for Bishop's use case of mapper tags. But I think it would be useful to have an interface to share the mapper tag, or basically any metadata that is carried along with the task.

**Comment by manopapad** [comment]
Mirroring my comment from #696, a first step might be to associate all the launches of a task with the same tag, set at task creation:

```
__tag(TAG1)
task foo() ... end
```

or

```
task foo() ... end
foo:attach_tag(TAG1)
```

This value could be set as the mapper tag on every launch of that task (with the possibility of overriding it on a per-launch basis, using the syntax @elliottslaughter suggested above), or attached as semantic information on the task's ID.

This approach would not solve the original problem listed for this issue, but would be sufficient to pass information about a task from application to mapper using a well-defined interface (as opposed to e.g. matching on the task name).

**Comment by elliottslaughter** [comment]
I'd be fine with adding something like `task:set_semantic_information(id, value)`, which would not modify mapping tags at all but would give you something you could look up in the mapper for each task. I'm a little less enthusiastic about the `__tag` syntax since it would be yet another syntax extension.

**Comment by elliottslaughter** [comment]
This is supported in 429a17fb8553c828384996b24cebef2738919413 via the syntax `foo:set_mapping_tag_id(TAG1)`. I'd be willing to consider a version for arbitrary semantic info if that would help, but I think this solves the immediate issue at hand.

Note that this will assert if you attempt to use it at the same time as Bishop, since we can only have one mapping tag associated with a task.

See also https://github.com/StanfordLegion/legion/issues/696 which adds a syntax for setting a custom mapper.
