### ISSUE TITLE
Regent CUDA codegen inefficiency: blocking in tasks that do scalar reductions

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#440]
Refer to this profiler output from a Soleil-X GPU-only single-node run on Sherlock: http://sapling.stanford.edu/~manolis/28913694/legion_prof. You will notice that there are gaps in GPU utilization. Most of these gaps align with tasks blocking during execution, specifically those tasks that are doing scalar reductions over their regions (`Flow_AddTurbulentSource`, `Particles_DeleteEscapingParticles` etc.).

The reason this is happening for these tasks in particular is (probably) how the Regent CUDA code generator is performing the final step of the reduction:
https://github.com/StanfordLegion/legion/blob/6675008b0483d0714edb01f50494456d4c8d90db/language/src/regent/cudahelper.t#L484-L510
It is performing a `cudaDeviceSync`, causing the task to wait for the CUDA kernels to finish, then does a blocking `cudaMemcpy` from device to host, where it performs some final computation to get the final scalar value. During part of this process apparently the GPU is sitting idle. This sort of inefficiency has not been noticeable on other machines like sapling, possibly because the GPUs there were not efficient enough for this to matter.

Sean suggested an alternative way of achieving this behavior without the need for a `cudaDeviceSync`: Have the main CUDA kernels write their values to device memory, then have a fixup kernel that reads those values and does the final reduction (what is currently done on the host, in the postamble code above). This fixup kernel would then write the final scalar value to a small region in zero-copy memory. Presumably the calling convention for these tasks would also need to change, such that the caller now looks for the result in that special zero-copy memory region.

**Comment by lightsighter** [comment]
Why isn't Regent using the DeferredValue and DeferredReduction classes to avoid syncing the GPU when doing these reductions?
https://gitlab.com/StanfordLegion/legion/blob/master/runtime/legion.h#L2330-2349

**Comment by magnatelee** [comment]
I think Regent can use DeferredReduction at least to get rid of cudaMemcpy that it currently emits, although we're not gonna be able to call any of the methods, because the current PTX code generation cannot handle external function calls. Making CUDA variants actually return a DeferredReduction object is going to be non-trivial because it also requires to change the preamble and postamble of the variant and also the task registration part, and presumably we want to do this only for CUDA variants. I'll first try to use DeferredReduction without changing the preamble and postamble, and then if syncing the GPU turns out to be still costly, which I guess it will, I'll fix it as well.

**Comment by magnatelee** [comment]
I pushed several changes and now the compiler uses DeferredBuffer in scalar reduction for GPUs. I also confirmed on Lassen that these changes make the contention with multiple GPUs disappear and also bring 2~3X improvement in the scalar reduction performance. BTW, I decided to keep the calls to `cudaDeviceSynchronize` because they seem to have only negligible impact on performance and synchronization is necessary when the task performs multiple scalar reductions or uses the result in the middle of the task. That said, it will be really nice if I can call `cudaStreamSynchronize` instead.

@manopapad Could you run Soleil-X with my changes and see if you no longer observe the weird slowdown with one-rank-per-node?

**Comment by streichler** [comment]
@magnatelee, `cudaDeviceSynchronize` is basically `cudaStreamSynchronize` when the cudart hijack is active:
https://gitlab.com/StanfordLegion/legion/blob/master/runtime/realm/cuda/cuda_module.cc#L1988-2002

**Comment by lightsighter** [comment]
Why is cudaStreamSynchronize needed if there are multiple scalar reductions? All the kernels are going on the same stream for the same task so they should all be properly ordered. If one kernel produces a value for a later one then it should just be able to read it directly.

**Comment by magnatelee** [comment]
@lightsighter with multiple scalar reductions, I was assuming that the task computes a new value using the result of a kernel before passing it to the next one, so it is actually the same case as that the task uses the reduction result in the middle. I guess I can implement something similar to the future optimization for reduction variables (i.e., pushing all computation on a reduction variable to the consumer kernels), but I'm not sure how useful this will be.

**Comment by lightsighter** [comment]
Why not just reduce deferred a value? All the kernels will be ordered because they go on the same stream. When the consumer kernel starts it can then just read the deferred value result directly because it knows all the kernels on the same stream are ordered?

**Comment by magnatelee** [comment]
Please note that the compiler transforms only the for loops in CUDA tasks. Consider this example:
```
var avg = 0
for e in r1 do
  avg += @e
end
avg = avg / N
for e in r2 do
  @e = avg
end
```
The task computes `avg / N` on the CPU side and therefore must block on the kernels from the first loop. If there is an optimization pass that either factors this part out into its own kernel or pushes it down to all the subsequent consumers, we can avoid the synchronization. Until we find a compelling example that really needs this optimization, I will not implement this.

**Comment by magnatelee** [comment]
No, there isn't. But, doing so is not always possible (for example, if the code has calls to host-only functions) and also not always beneficial. In my experience, any sequential code with some control flow runs much more slowly on GPUs. On top of this, we need a static analysis to lift scalar variables to deferred variables, just like we needed to lift variables to futures for tasks. I guess we can come up with a very simple heuristic that does this for only a narrow set of cases, but even then I'm not sure how useful this would be, though I'm pretty sure the optimization passes that we need to implement aren't that simple. Plus, almost all cases we care about don't actually need this optimization. (They just have only one for-all loop on a region without any scalar reduction, for which no stream synchronize is emitted.) As I said, it should be possible to remove the stream synchronize by changing the task postamble to return a deferred value directly, but again it's not too late to do this once we find that stream synchronize is causing any real performance issue.

**Comment by manopapad** [comment]
With the latest master, I can no longer see the blocking on scalar reduction kernels on Sherlock, and 4-ranks-per-node mode has the same performance as 1-rank-per-node on Lassen.
