### ISSUE TITLE
Hardcoded values in runtime/legion/legion_config.h

### ISSUE THREAD

**Issue by tpatki** [StanfordLegion/legion#454]
The legion_config.h file defines MAX_NUM_PROCS to hardcoded values, which are being used despite USE_HWLOC being set as 1. We have nodes with 72 cores on our system with SMT, and there should be a nicer way to detect this through HWLOC than to edit the legion_config.h. Also, it seems that this value needs to be a multiple of 64, and it is unclear why this value needs to be a multiple of 64 and what the SSETLBitMask and AVXTLBitMask functions do.

**Comment by elliottslaughter** [comment]
I'll need @streichler to confirm to be absolutely sure, but I'm pretty sure this is being used to size a bitmask. Certain kinds of IDs get bitpacked with node number / processor number / resource number etc. all packed into the same bit field, so increasing this puts pressure on e.g. the maximum number of nodes (or on the size of the bitfield). Also more generally, if we made this dynamic it would prevent us from constant-folding the masks and shifts for the different fields.

For now I'd recommend either increasing this to the next power of 2 or sharding the runtime so that you have 2 or more runtimes per node. (Presumably, your 72 cores are spread out over multiple sockets, so it may make sense to do so anyway.)

@streichler or @lightsighter can you confirm what constraints there are on `MAX_NUM_NODES` / `MAX_NUM_PROCS` (e.g. do these have to be powers of 2)? At a minimum these should be documented in the source.

**Comment by lightsighter** [comment]
Both MAX_NUM_NODES and MAX_NUM_PROCS need to be a power of 2. If you violate the constraint you'll get a static assert and your code will fail to compile. These just have to be an upper bound on the number of nodes/processors and doesn't need to be tight.

**Comment by elliottslaughter** [comment]
I've pushed a change to document that they must be powers of 2.

@tpatki Does this resolve your main problem in this issue?

**Comment by tpatki** [comment]
Yes, it does. Thanks!
