### ISSUE TITLE
Documentation on multi-node runs, ll:mp_cpu, ll:mp_threads, ll:cpu

### ISSUE THREAD

**Issue by tpatki** [StanfordLegion/legion#455]
It is unclear how to correctly get the simplest legion mapping on a multi-node system with GASNET. Couple of things we can use help in:

1) After the execution, how do we check the total number of tasks that were run? Legion Spy produces task/event graphs, but we couldn't find information on task counts or specific runtime mappings (without digging through details of mapper code). 

2) How do we launch a multi-node legion application correctly so that it utilizes all cores? This requires us to create more independent tasks than cores on our nodes, and it is unclear to us how ot measure this. For example, we modified circuit.cc to have more num_loops/num_pieces (set to 100 loops and 200 pieces, so it runs long enough). We tried several combinations on 2 nodes. Each node in this example has 2 sockets, 36 logical cores per socket (72 total logical cores per node, 144 total). We also tried with 1 less logical core (so 36 instead of 35, for example to account for the legion task.

```
srun -N2 -n2 ./circuit -ll:cpu 72
srun -N2 -n4 ./circuit -ll:cpu 36
```
When we tried `top +1`, we only saw part of the cores being used in all those scenarios, and most cores were idle. In some cases, only one of the two sockets on each of the nodes was in use. It is unclear how many tasks are being created in each case, and why these aren't mapped across all available logical processors. How do we create enough tasks to get all cores to be utilized? Is there a simple mapper that already does this?

3) It is unclear what options such as `ll:mp_cpu` and `ll:mp_threads` do, and how they can be used in combination with `ll:cpu`.

**Comment by elliottslaughter** [comment]
A couple things (ok, more than a couple):

 1. Just as a heads up, Legion Spy is very slow, so please don't run it in any runs where you intend to measure performance. It's fine to use it for debugging, but remember to turn it off (and recompile) before you start performance runs because even having it compiled into a Legion binary will have a performance impact.

 2. As a related reminder, turn off debug mode before you do any performance runs (and recompile).

 3. I generally recommend Legion Prof for profiling issues. The overhead is not zero, but much much lower than Legion Spy and still provides a lot of useful information. In this case, you could get a lot of information with the `-s` flag to Legion Prof:

    ```
    $ ./regent.py examples/circuit.rg -hl:prof 1 -hl:prof_logfile prof_%.gz
    $ ~/legion/tools/legion_prof.py -s prof_*.gz
    ****************************************************
       TASK STATS
    ****************************************************
      -------------------------
      Task Statistics
      -------------------------
      toplevel [primary]
           Total Invocations: 1
           Total Time: 330469 us
    ...
    ```

   All of our tools support `-h` so you can use that to discover more flags on your own.

 4. When you ran, did you see a warning like:

    ```
    [0 - 7f232437d780] {4}{threads}: reservation ('CPU proc 1d00000000000008') cannot be satisfied
    ```

   This warning does not matter for correctness, but you should not ignore it when you are doing performance runs! This is telling you that you have oversubscribed the machine.

5. In general, we don't recommend using logical processors with Legion, except in very specific situations. Typically what I would recommend is using an `-ll:cpu` value of `N-K` where `N` is the number of **physical** processors on the system, and `K` is a small number like 1 or 2. The exact value of `K` depends on the application so it's difficult to give general advice here except to try it out and see what works for you. There are changes coming down the pipe that will make Legion less sensitive to this value, but for the moment you've got to find the optimal value by tuning it yourself.

 6. Keep in mind that depending on the SLURM configuration and the contents of your sbatch script or command line, that SLURM may be attempting to bind Legion to a sub-optimal number of cores. Legion respects the CPU affinity mask set by the job scheduler and will not use any cores outside of that. So a typical SLURM command line might look like:

    ```
    srun -N2 -n2 --cpus-per-task 72 ./circuit -ll:cpu 34
    ```

    Depending on whether SLURM is configured to count logical or physical cores you might need to change that to `--cpus-per-task 36`. (There seems to be no consistency in this, unfortunately, so you just have to see how you've got it set on your machine.) If your SLURM is set to use the cpu-bind plugin, you could alternatively try to use `--cpu_bind none`, but this only works in the case where there is exactly one Legion runtime per node, so it's not something I recommend in general.

 7. If you want to sanity check the core assignment that Legion is using, you can use the `-ll:show_rsrv` flag to print it out. You may want to map output from different ranks to different files, because the output can get tangled up otherwise. But in general you only need to check this if you see the warning above and want to figure out what is wrong. E.g. if SLURM is assigning Legion a small number of cores, you will see this show up here.

 8. Also keep in mind that the number of tasks is purely a function of the application. So it doesn't make sense in Legion to ask why `M` tasks were created when you configured Legion to use `N` cores. These are entirely unrelated. Most Legion applications take a command line parameter that configure how much parallelism to create. In the `examples/circuit.cc` code, this flag is `-p`. You can also control the number of loops through `-l`. Unless the application is poorly written you would not typically configure these by modifying the source code.

 9. I'm pretty sure that the circuit mapper is written correctly in this case, and that you don't have a problem with your mapper. But if you did have a custom mapper which you thought might be at fault, a quick way to verify the task to core assignment is to run Legion Prof. It will be very obvious if all the tasks are being assigned to one core.

10. I don't think `ll:mp_cpu` and `ll:mp_threads` are Legion flags? There are flags called `ll:ocpu` and `ll:othr`, but these are used only in applications that specifically support OpenMP tasks. Do not use them unless you know that's what the application wants. In general, I'd recommend following the advice above about choosing an `ll:cpu` value unless you know the application specifically has other requirements.

11. I agree in general this needs more documentation, something like the advice above about choosing `ll:cpu` values should probably be in our performance tuning page here: https://legion.stanford.edu/profiling/ . In the longer term, we hope to make a lot of this unnecessary, or at least take a better guess out of the box, but please understand that the configuration space for Legion is much larger than most systems and so this means there isn't any easy algorithm that can be expected to work in 100% of cases, even when we can auto-detect the hardware. The configuration is always a function of what the application wants, and that means you'll need to spend some time understanding the application to know e.g. whether it needs OpenMP processors or not, I/O processors or not, GPUs or not, how many utility processors or DMA processors it can take advantage of etc.

Hope that helps and please let me know if you have any more questions.

**Comment by elliottslaughter** [comment]
Did you get a separate output file per rank? It looks like this output has been interleaved, which makes it a bit difficult to read.

The `core map {` part shows what Legion thinks it was assigned by the job scheduler. In this case, it seems like Legion thinks each runtime got assigned the entire node, even though your SLURM command line seems to show 2 runtimes per node? In this case, you might need to turn on `--cpu_bind=cores` if you actually want to slice up the machine in this way. If your SLURM doesn't have the cpu_bind plugin, you should probably stick to one runtime per node (or you could manually do the affinity, but that's not going to be much fun).

The part after that `CPU proc ...: allocated <...>` shows the binding from Legion's internal notion of processors (i.e. the `-ll:cpu` flag) to hardware cores. This looks alright except for the fact that both runtimes got the same set of cores, so multiple Legion processors are being assigned to the same core, e.g.:

```
CPU proc 1d0001000000000a: allocated <0>
CPU proc 1d00030000000009: allocated <0>
```

The machine configuration isn't controlled by the application, but by flags like `-ll:cpu`. You can see the full set of flags here:

https://legion.stanford.edu/profiling/#machine-configuration

Again the optimal configuration will depend on the application. So you will want to talk to the application developers to see what settings to use for their apps (or us, for the example apps).

For example, Circuit is CPU bound initially and eventually communication bound as it has an all-to-all communication pattern. The tasks are large if you have it configured properly, so I wouldn't expect you to need more than one utility processor (`-ll:util 1`). (You can check this by running Legion Prof and seeing how full the utility processor timelines are.) Because it will be bottlenecked on the network, I'd expect on most networks you can keep the network saturated with only a single core, so `-ll:dma 1` is probably sufficient too. But you can always test `-ll:dma 2` to be sure. I don't think I've ever used more that one active message thread.

So, if you have `-ll:util 1 -ll:dma 1` (the default setting), you'll have 3 extra threads, or 4 on Cray (because Cray insists on having its own thread for the network). So to be sure that each thread has its own logical core, you'd need to leave 2 cores (`K=2` in my formula above), though you could probably get away with `K=1` because realistically most of the threads won't be fully utilized.

**Comment by elliottslaughter** [comment]
Can you try `--cpu-bind=X,verbose` where `X` is `cores` or whatever binding you're trying to use? Then we can compare that to what Legion is seeing.

Also, can you try disabling hwloc and see if the problem still persists?

I believe the `--output` flag to srun should be able to do what you want. E.g. `--output "out_%J_%t.log` should give you a file per rank.

**Comment by tpatki** [comment]
Ah, I was missing the %t for task, thanks!


Here's the test I ran, `hwloc` was disabled by setting `USE_HWLOC` to 0 in the Makefile for circuit.
 
```srun -N2 -n4 --cpus-per-task=18 --cpu_bind=cores,verbose --output out_%J_%t.log ./circuit -p 100 -ll:cpu 16 -ll:util 1 -ll:dma 1 -ll:show_rsrv```

Here are the log files. 4 tasks are being created, but I'm not sure how legion is mapping cores. 

[out_1874952.4_0.log](https://github.com/StanfordLegion/legion/files/2645936/out_1874952.4_0.log)
[out_1874952.4_1.log](https://github.com/StanfordLegion/legion/files/2645937/out_1874952.4_1.log)
[out_1874952.4_2.log](https://github.com/StanfordLegion/legion/files/2645938/out_1874952.4_2.log)
[out_1874952.4_3.log](https://github.com/StanfordLegion/legion/files/2645939/out_1874952.4_3.log)

**Comment by tpatki** [comment]
Here are the ones with hwloc enabled, these look like they're picking up logical processors. 

```srun -N2 -n4 --cpus-per-task=18 --cpu_bind=cores,verbose --output out_with_hwloc_%J_%t.log ./circuit -p 100 -ll:cpu 16 -ll:util 1 -ll:dma 1 -ll:show_rsrv```
 
[out_with_hwloc_1874952.5_0.log](https://github.com/StanfordLegion/legion/files/2645962/out_with_hwloc_1874952.5_0.log)
[out_with_hwloc_1874952.5_1.log](https://github.com/StanfordLegion/legion/files/2645963/out_with_hwloc_1874952.5_1.log)
[out_with_hwloc_1874952.5_2.log](https://github.com/StanfordLegion/legion/files/2645964/out_with_hwloc_1874952.5_2.log)
[out_with_hwloc_1874952.5_3.log](https://github.com/StanfordLegion/legion/files/2645965/out_with_hwloc_1874952.5_3.log)

**Comment by elliottslaughter** [comment]
Wow, it looks like these are actually both buggy.

  * without hwloc, we're picking up the affinity mask but then somehow ignoring the hyperthreads.
  * with hwloc we're not picking up the affinity mask at all, so both ranks on a node are trying to map to the same set of cores.

I'd recommend without hwloc for now, it will not use hyperthreads correctly but at least there won't be collisions between the different runtimes. (And realistically, the hyperthreads don't have much impact in most situations anyway.)

In the meantime, we'll I'm going to assign this to @streichler to get these fixed.

**Comment by tpatki** [comment]
Thanks for looking into this, @elliottslaughter!

**Comment by tpatki** [comment]
I ran another test for you in case this helps. So, without hwloc, but setting ll:cpu to 34 as opposed to 16 (as we have 36 logical cores per processor). This isn't printing out the allocated CPUs for some reason...

```srun -N2 -n4 --cpus-per-task=18 --cpu_bind=cores,verbose --output out_no_hwloc_34LLCPU__%J_%t.log ./circuit -p 100 -ll:cpu 34 -ll:util 1 -ll:dma 1 -ll:show_rsrv```

[out_no_hwloc_34LLCPU__1876695.1_0.log](https://github.com/StanfordLegion/legion/files/2646223/out_no_hwloc_34LLCPU__1876695.1_0.log)
[out_no_hwloc_34LLCPU__1876695.1_1.log](https://github.com/StanfordLegion/legion/files/2646224/out_no_hwloc_34LLCPU__1876695.1_1.log)
[out_no_hwloc_34LLCPU__1876695.1_2.log](https://github.com/StanfordLegion/legion/files/2646225/out_no_hwloc_34LLCPU__1876695.1_2.log)
[out_no_hwloc_34LLCPU__1876695.1_3.log](https://github.com/StanfordLegion/legion/files/2646226/out_no_hwloc_34LLCPU__1876695.1_3.log)

**Comment by tpatki** [comment]
On another note, @elliottslaughter, the `mp_cpu` and `mp_threads` options are a part of the `procset` module here: https://github.com/StanfordLegion/legion/blob/stable/runtime/realm/procset/procset_module.cc#L110

My very limited understanding from when @amarathe84 was tracing through the example was that there was a call to`create_processors`, which was calling the procset module, but we may be entirely incorrect here.

**Comment by tpatki** [comment]
On another note, @elliottslaughter, the mp_cpu and mp_threads options are a part of the `procset` module here: https://github.com/StanfordLegion/legion/blob/stable/runtime/realm/procset/procset_module.cc#L110

My very limited understanding from when @amarathe84 and I were tracing through the example was that there was a call to `create_processors`, which was calling the `procset` module, but we may be entirely incorrect here.

**Comment by tpatki** [comment]
I see. 

We're not looking into OpenMP or MPI, just multi-node Legion (I'm not even sure how to reason about Legion threads/tasks + OpenMP tasks yet). Is it safe to assume that `procset` will not get called (I see it being included here without any ifdef: https://github.com/StanfordLegion/legion/blob/stable/runtime/realm/module.cc#L40, but I can see checks in place for PROC_SET in mapper functions)? 

By any chance, is there any documentation or a flow diagram of which functions are called internally and what happens when `default_policy_select_target_processors` is invoked in circuit? I'm assuming that particular function is calling the DefaultMapper's `default_policy_select_target_processors` before it applies constraints. It is unclear to me how `local_cpus` are determined there.

**Comment by streichler** [comment]
@tpatki, can you try running the non-hwloc case with `-level threads=2` on the command line and attach the logs?

**Comment by streichler** [comment]
Ok, there's some discrepancy between the cpu binding that srun says it's doing and what Realm is seeing:
```
cpu-bind=MASK - quartz11, task  0  0 [35934]: mask 0x3ffff00003ffff set
[0 - 2aaaaab148c0] {2}{threads}: cpu 36 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 37 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 38 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 39 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 40 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 41 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 42 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 43 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 44 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 45 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 46 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 47 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 48 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 49 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 50 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 51 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 52 not available - skipping
[0 - 2aaaaab148c0] {2}{threads}: cpu 53 not available - skipping
```
Realm is using the results from `sched_getaffinity`, which do not seem to include the upper set of bits in the message from srun.

**Comment by tpatki** [comment]
Here's what I got.

[out_numactl_1891044.5_0.log](https://github.com/StanfordLegion/legion/files/2654668/out_numactl_1891044.5_0.log)
[out_numactl_1891044.5_1.log](https://github.com/StanfordLegion/legion/files/2654669/out_numactl_1891044.5_1.log)
[out_numactl_1891044.5_2.log](https://github.com/StanfordLegion/legion/files/2654670/out_numactl_1891044.5_2.log)
[out_numactl_1891044.5_3.log](https://github.com/StanfordLegion/legion/files/2654671/out_numactl_1891044.5_3.log)

**Comment by streichler** [comment]
Ok, so the `numactl` output matches what Realm is seeing from `sched_getaffinity` and not what `srun` says it is setting the mask to.  @elliottslaughter, have you seen anything like this before?

**Comment by elliottslaughter** [comment]
I've definitely seen cases where `taskset` reports something different than `numactl`. I'm not sure why. But I've never seen divergence between `srun` and `realm`/`taskset`.

If you want another data point, you could try:

```
srun -N2 -n4 --cpus-per-task=18 --cpu_bind=cores,verbose --output out_taskset_%J_%t.log bash -c 'taskset -p $$'
```

**Comment by tpatki** [comment]
Here's the taskset output. This seems to match `srun`...

[out_taskset_1898584.5_0.log](https://github.com/StanfordLegion/legion/files/2659224/out_taskset_1898584.5_0.log)
[out_taskset_1898584.5_1.log](https://github.com/StanfordLegion/legion/files/2659225/out_taskset_1898584.5_1.log)
[out_taskset_1898584.5_2.log](https://github.com/StanfordLegion/legion/files/2659226/out_taskset_1898584.5_2.log)
[out_taskset_1898584.5_3.log](https://github.com/StanfordLegion/legion/files/2659227/out_taskset_1898584.5_3.log)

**Comment by streichler** [comment]
Actually, I think it matches `realm` and `numactl`:
```
cpu-bind=MASK - quartz42, task  0  0 [78871]: mask 0x3ffff00003ffff set
pid 78871's current affinity mask: 3ffff
```
Bits 0-17 are set, but bits 36-53 are not.

**Comment by tpatki** [comment]
Oops, sorry, yes, you're right. I also tried running with `srun --cpu_bind=threads,verbose`
 to see if the logical processors get picked. Any other ideas on what to try? Here's what I get with `numactl -s`, `taskset` and `./circuit -p 100 -ll:cpu 16 -ll:util 1 -ll:dma 1 -level threads=2 -ll:show_rsrv` when I use `cpu_bind=threads` instead of cores.

[out_cpubind_threads_1898716.6_0.log](https://github.com/StanfordLegion/legion/files/2659286/out_cpubind_threads_1898716.6_0.log)
[out_cpubind_threads_1898716.6_1.log](https://github.com/StanfordLegion/legion/files/2659287/out_cpubind_threads_1898716.6_1.log)
[out_cpubind_threads_1898716.6_2.log](https://github.com/StanfordLegion/legion/files/2659288/out_cpubind_threads_1898716.6_2.log)
[out_cpubind_threads_1898716.6_3.log](https://github.com/StanfordLegion/legion/files/2659289/out_cpubind_threads_1898716.6_3.log)

[out_cpubind_threads_numactl_1898716.5_0.log](https://github.com/StanfordLegion/legion/files/2659290/out_cpubind_threads_numactl_1898716.5_0.log)
[out_cpubind_threads_numactl_1898716.5_1.log](https://github.com/StanfordLegion/legion/files/2659291/out_cpubind_threads_numactl_1898716.5_1.log)
[out_cpubind_threads_numactl_1898716.5_2.log](https://github.com/StanfordLegion/legion/files/2659292/out_cpubind_threads_numactl_1898716.5_2.log)
[out_cpubind_threads_numactl_1898716.5_3.log](https://github.com/StanfordLegion/legion/files/2659293/out_cpubind_threads_numactl_1898716.5_3.log)

[out_cpubind_threads_taskset_1898716.7_0.log](https://github.com/StanfordLegion/legion/files/2659294/out_cpubind_threads_taskset_1898716.7_0.log)
[out_cpubind_threads_taskset_1898716.7_1.log](https://github.com/StanfordLegion/legion/files/2659295/out_cpubind_threads_taskset_1898716.7_1.log)
[out_cpubind_threads_taskset_1898716.7_2.log](https://github.com/StanfordLegion/legion/files/2659296/out_cpubind_threads_taskset_1898716.7_2.log)
[out_cpubind_threads_taskset_1898716.7_3.log](https://github.com/StanfordLegion/legion/files/2659297/out_cpubind_threads_taskset_1898716.7_3.log)

**Comment by tpatki** [comment]
Okay, I believe I've figured out what may be causing this. At LLNL, we have a separate ``srun`` flag that is enabled by default, called ``--mpibind`` that automatically binds processes/threads to cores in order to ensure better reproducibility on science runs. I wasn't aware that this is on by default, turning this off shows a better ``numactl`` result (see below). 

Can you check that the mappings for circuit (further below) look correct? If so, I'm still not seeing high utilization on the nodes that we have, what input parameters should I provide to the circuit app to make it relatively compute bound? Alternatively, is there an example of a Legion application that is compute bound and utilizes all cores heavily?
 
#### ```numactl```
[out_numactl_1935330.7_0.log](https://github.com/StanfordLegion/legion/files/2678406/out_numactl_1935330.7_0.log)
[out_numactl_1935330.7_1.log](https://github.com/StanfordLegion/legion/files/2678407/out_numactl_1935330.7_1.log)
[out_numactl_1935330.7_2.log](https://github.com/StanfordLegion/legion/files/2678408/out_numactl_1935330.7_2.log)
[out_numactl_1935330.7_3.log](https://github.com/StanfordLegion/legion/files/2678409/out_numactl_1935330.7_3.log)

 #### ```circuit```

```srun -N2 -n4 --cpus-per-task=18 --mpibind=off.vv --cpu_bind=cores,verbose --output out_mpibind_off_%J_%t.log ./circuit -p 200 -ll:cpu 16 -ll:util 1 -ll:dma 1 -ll:show_rsrv```

[out_mpibind_off_1935390.1_0.log](https://github.com/StanfordLegion/legion/files/2678438/out_mpibind_off_1935390.1_0.log)
[out_mpibind_off_1935390.1_1.log](https://github.com/StanfordLegion/legion/files/2678439/out_mpibind_off_1935390.1_1.log)
[out_mpibind_off_1935390.1_2.log](https://github.com/StanfordLegion/legion/files/2678440/out_mpibind_off_1935390.1_2.log)
[out_mpibind_off_1935390.1_3.log](https://github.com/StanfordLegion/legion/files/2678441/out_mpibind_off_1935390.1_3.log)

**Comment by tpatki** [comment]
@elliottslaughter, @streichler: Can you please confirm the above mapping and help me identify input parameters/alternate application that generates enough tasks to keep the CPUs utilized?

**Comment by elliottslaughter** [comment]
Yes, that binding looks correct now.

Can you try something like the following?

```
for nodes in 2; do
  for cores in 16; do
    srun -N$nodes -n$(( 2 * nodes )) --cpus-per-task=18 --mpibind=off.vv --cpu_bind=cores,verbose --output out_mpibind_off_%J_%t.log ./circuit -l 100 -p $(( nodes * cores )) -npp 1000 -wpp 4000 -ll:cpu 16
  end
end
```

I'm showing this as a loop so you can see what I expect to vary as you scale.

The values of `-npp` and `-wpp` are just guesses because it's been a while since I ran this variant of Circuit and they will depend on your hardware at any rate. These determine how computationally intensive the tasks are. `-npp` stands for "nodes per piece" and `-wpp` for "wires per piece". If it's still not computationally intensive enough, try increasing one or both until you're happy with how long it's taking.

If you'd like us to check this for you, please do a run with `-hl:prof $nodes -hl:prof_logfile prof_${nodes}_${cores}_%.gz` and run it through `legion/tools/legion_prof.py`. You can zip the output and attach it here. This should quickly tell us whether you're using the processors fully or not.

**Comment by elliottslaughter** [comment]
I made some minor edits to my comment above to fix typos and correct for the number of runtimes per node.

**Comment by streichler** [comment]
@tpatki have we resolved this issue to your satisfaction?

**Comment by streichler** [comment]
@tpatki I'm going to close this bug due to inactivity, but feel free to reopen it if you still have any concerns.
