### ISSUE TITLE
Regent: Detect how many dimensions Legion was compiled with

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#466]
To properly interface with Legion's newly implemented support for a variable number of index space dimensions, Regent needs to know the value of the `LEGION_MAX_DIM` constant that Legion was compiled against when it calls `terralib.includec` on `legion_c.h`.

One option would be to autodetect this by inspecting `libregent.so`, the way it's done for CUDA and OpenMP, and add an `-f` flag so the user can set it manually when auto-detection isn't available (and do a dynamic consistency check, when the code starts running).

A cleaner option might be to have the Makefile generate a `legion_defines.h` header, like the one generated by CMake. This has also been suggested as a way to communicate the link flags that Legion's `runtime.mk` infers to the compiler (see https://github.com/StanfordLegion/legion/pull/341).

**Comment by elliottslaughter** [comment]
As a workaround I've added a flag `-flegion-dim` that you can use to tell Regent about the value of `LEGION_MAX_DIM`.

**Comment by lightsighter** [comment]
Would it help if you had a runtime call to query this value from the runtime?

**Comment by elliottslaughter** [comment]
Unfortunately no, any autodetect mechanism had to work without actually loading the runtime because:

(a) on platforms like Summit we jus can't do that right now

(b) even when we can we need to set LEGION_MAX_DIM at the point where we include the Legion header file. So if you need to load Legion in order to include that header, you've got a circular dependency.

In my opinion the most promising approach is to have legion_defines.h be generated as part of the build in both Make and CMake. That way any build-influencing variables can always be depended on being set, which is the simplest way for users (most won't even have to think about this at all) and makes this future proof as well.

**Comment by lightsighter** [comment]
What about a static method on the runtime so you can call it without having actually started the runtime?

**Comment by elliottslaughter** [comment]
No, we can't even load `libregent.so` because the ffi implementation in Lua is incomplete (and LuaJIT doesn't support PPC64le). Anything that requires calling a C or Terra function during compilation, or even just loading a shared library, is not going to work.

Futhermore, the static method still doesn't resolve the cyclic dependency, because presumably the way I call the static method is by running `terralib.includec("legion.h")` and the set of defines is already fixed at that point.

**Comment by elliottslaughter** [comment]
As of ff00fb898db725ec0abb6ce804ff1efb9461e161 we generate `legion_defines.h` which includes the value for `LEGION_MAX_DIM` so that it no longer needs to be set on the command line. `-flegion-dim` is no longer required or supported.
