### ISSUE TITLE
Regent: Proper memoization of unpack_param functions

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#472]
Regent currently emits ~4k separate functions for unpacking parameters in tasks for Soleil, which seems excessive. We should be able to memoize these on the type of the parameter. This may not work out of the box for region types, because the compiler creates a distinct type on every instance of `region(...)`, but we could potentially just compare region types structurally for this specific usecase.

**Comment by elliottslaughter** [comment]
Ok, there is a partial version of this in master now, which should be sufficient to memoize any non-unique types (i.e. anything other than ispace, region, partition, cross-product, etc.).

There is also a more aggressive version in the branch `regent-memoize-unpack-param-regions`, which should work for at least ispaces, regions, and partitions. I'm not quite happy with this version because it adds some additional gunk, but if it can be shown to make a big difference then I'll merge it.

**Comment by manopapad** [comment]
I tested this on sapling, here's the time it takes to compile Soleil under different configurations:
```
no memoization: 19m40.410s
basic memoization: 15m20.498s
aggressive memoization: 15m22.302s
```
So I'd say memoization of these functions has a measurable impact, but any improvement the aggressive version might be offering is getting lost in the noise. I might do some more detailed profiling later, but for now I'm closing this issue.
