### ISSUE TITLE
Regent: parallelizer misreports location of error

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#484]
For this program:

```
import "regent"
fspace MeshFields {
  Xi   : double[5]
}
__demand(__cuda)
task InitMesh( Mesh : region(ispace(int3d),MeshFields) )
where
  reads writes(Mesh.Xi)
do
  __demand(__openmp)
  for c in Mesh do
    Mesh[c].Xi = array( 0.0, 0.0, 0.0, 0.0, 0.0 )
    regentlib.assert(Mesh[c].Xi[0]<1e-3, "")
  end
end
```

The reported error is:

```
...lis/sw/legion/language/src/regent/check_parallelizable.t:873: Errors reported during typechecking.
PseudoSolver.rg:12: CUDA code generation failed: found a region access outside parallelizable loops
    Mesh[c].Xi = array( 0.0, 0.0, 0.0, 0.0, 0.0 )
        ^
```

The reported error should be that you can't use `regentlib.assert` inside a CUDA loop.

**Comment by magnatelee** [comment]
Well that's not how the parallelizability checker works. It is perfectly fine to call `regentlib.assert` in a CUDA task as long as it doesn't appear within a parallelizable for loop (which makes it run on the host side). Inversely, any for loop that calls a host-only function is considered non-parallelizable. The real problem in your code is that the CUDA task tries to access a region outside parallelizable loops, because only parallelizable loops will run on GPUs and thus have access to instances. So, the reported error is not a bug, but is intended behavior.
