### ISSUE TITLE
Regent: Add optional argument to partition operators for specifying partition kind

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#487]
There is currently no way to specify a legion_partition_kind_t in Regent for image and restrict. Both assume COMPUTE_KIND which causes expensive runtime analysis to occur. Adding an optional argument would allow you to specify DISJOINT_KIND. 

It looks like preimage will also use COMPUTE_KIND under certain conditions.

**Comment by syamajala** [comment]
The work around I was using for this, calling `legion_index_partition_create_by_image_range` and  `__import_partition` doesn't seem to be working anymore. It would be nice if this could be fixed.

**Comment by elliottslaughter** [comment]
What do you mean doesn't work anymore?

**Comment by lightsighter** [comment]
When you fix this, please also get rid of the dynamic cast in the barnes-hut example that leads the user to create a duplicate deletion because they create two static names for the same dynamic partition. See this commit:
https://github.com/StanfordLegion/barnes-hut/commit/9c11b5b48bb14bfddb8b48082a85aa5cb11b10d6

**Comment by elliottslaughter** [comment]
This has been added for the `image`, `preimage` and `restrict` operators. Barnes Hut has been updated.
