### ISSUE TITLE
Regent: overloading of __parallel keyword

### ISSUE THREAD

**Issue by manopapad** [StanfordLegion/legion#520]
Copying this from a recent email discussion, where a user's comments signaled to me that the `__parallel` keyword may be too vague.

The meaning of `__demand(__parallel)` is very different depending on where it appears:

* If `__demand(__parallel)` appears on a task declaration, it means to pass the code through the auto-parallelizer. This pass creates a different version of the task that uses generated regions for the ghost accesses. This version of the task will be inserted automatically wherever the original was used (with the appropriate launching loop).
* If `__demand(__parallel)` appears on a task-launching loop, it means to not launch the tasks one-by-one, but instead use an index-space launch, a construct that lets the runtime launch a collection of tasks together, and shortcut some of the analysis. In particular, not putting `__demand(__parallel)` on a loop doesn't mean the tasks won't run in parallel, just that they aren't launched in parallel.

I would suggest switching to `__index_space_launch` or `__isl` for the launches, and `__parallelize` or `__parallelized` for invoking the auto-parallelizer.

**Comment by elliottslaughter** [comment]
I'm fine with making the index launch keyword something like `__index_launch`. I'm less sure about the parallelizer keyword, is adding `ize` or `ized` really going to make it clearer?

CC @magnatelee

**Comment by magnatelee** [comment]
I'm also fine with using `__index_launch` for index launches. And I don't think we need to change both of them.

**Comment by elliottslaughter** [comment]
Part 1 of this has landed in 531e909. I added the `__index_launch` annotation, which is currently just an alias for `__parallel` on a `for` loop. Internally the compiler converts `__parallel` to `__index_launch` in the specialize stage and thereafter the two are completely distinguished.

Currently the compiler issues a warning on `__parallel`. Since this is a widely used feature I suggest we let this continue until (a) we have made a public release and (b) that release has been available at least N months (for some value of N, maybe 3-6?). At that point I'd suggest switching it to an error, but with an optional switch to downgrade back to a warning. (Again repeating the same process to make sure people switch over.) Then we can make it a hard error and remove it from the compiler.

**Comment by elliottslaughter** [comment]
The deprecation was announced in https://github.com/StanfordLegion/legion/releases/tag/legion-19.09.0. As the next stage, we should move to an error (with a flag to downgrade to a warning), possibly for the next release. This could potentially go into master now.

**Comment by elliottslaughter** [comment]
Part 2 has landed in 023c2e1c112799ab58a7fb9e11b87efa454bfd9e. Using `__parallel` on a loop will now issue an error, which can be downgraded with the flag `-fallow-loop-demand-parallel 1` back into a warning. This is a temporary measure to make this "fails loudly" for users prior to the final removal of this feature.

**Comment by elliottslaughter** [comment]
This has been an error (with flag to downgrade to warning) since https://github.com/StanfordLegion/legion/releases/tag/legion-19.12.0. It probably makes sense to wait one more release before making it a hard error.

**Comment by elliottslaughter** [comment]
This has been in for over a year now. I'm removing the best effort tag to force myself to do this before the next release.

**Comment by elliottslaughter** [comment]
The error has been made permanent as of f7cbe50fab6d46ed7c3167ce132d83bdda53c92e and the flag to downgrade to a warning removed.
