### ISSUE TITLE
Document requirements on explicit copies

### ISSUE THREAD

**Issue by sparkasaurusRex** [StanfordLegion/legion#539]
If `r_src` is some partition, then `copy(r_src, r_dest)` actually gives `r_dest` the values of the original region. This is confusing if `r_src` is a parameter of a task because the programmer might not even know that `r_src` is a partition.

```
import "regent"

task toplevel()
  var r_foo = region(ispace(int1d, 10), int)
  for i in r_foo.ispace do
    r_foo[i] = i
  end

  var p_foo = partition(equal, r_foo, ispace(int1d, 2))
  var r_bar = region(ispace(int1d, 5), int)

  var r_part = p_foo[1]
  copy(r_part, r_bar)
  for i in r_bar.ispace do
    var part_idx = r_part.bounds.lo + i
    regentlib.c.printf("bar[%d] = %d\n", i, r_bar[i])
    regentlib.c.printf("r_part[%d] = %d\n", part_idx, r_part[part_idx])
    regentlib.assert(r_part[part_idx] == r_bar[i], "")
  end
  regentlib.c.printf("done\n")
end

regentlib.start(toplevel)
```

**Comment by elliottslaughter** [comment]
Did you run this code with Legion in debug mode? I get the following:

[0 - 7faf6b73f700] {5}{runtime}: [error 209] LEGION ERROR: Destination index space 3 for requirement 0 of cross-region copy (ID 6) in task toplevel (ID 1) is not a sub-region of the source index space 5. (from file /home/elliott/legion/runtime/legion/legion_ops.cc:3511)[error 209]

The reason for the error is that you are copying between two regions that are unrelated to each other (i.e. `r_part` is not a subregion of `r_bar` and vice versa, and there is no other region `A` of which both `r_part` and `r_bar` are both subregions). You can only copy between regions that are in the same "region tree" (i.e. both are subregions of some root region `A`).

By the way, as far as I know you can't issue copies to/from partitions at all. What you've done in the above code is attempt to issue a copy from a subregion of a partition to a completely unrelated region.

Also: it's worth noting that even in `r_part` and `r_bar` were in the same region tree, this copy still would work. This is because the index spaces of the two regions are non-overlapping. Specifically:

  * `r_part` contains elements [5, 9]
  * `r_bar` contains elements [0, 4]

Until gather-scatter copies are implemented (and this will be a different interface that you can't invoke by accident) this is not something that would work.

Hope that helps, and if there's something you're trying to do with this code it might help to explain that so that we can give more advice about what you should be doing instead.

**Comment by sparkasaurusRex** [comment]
I did not realize `copy` had these limitations. I have not been using Legion in debug mode and never saw any errors like that. Can the language reference for `copy` be changed on the webpage to reflect these limitations? In my own code I'm moving data from one fspace to another and I thought `copy` would be cleaner. The code was almost working, so I thought it was a bug. Can you force `copy` to fail in these cases to make sure programmers don't try to do this?

**Comment by elliottslaughter** [comment]
In general I recommend running in debug mode during initial development: there are many more errors like these that will be caught automatically if you do.

This particular case could also be caught at compile time but unfortunately in general this is an undecidable problem. The compiler can't always know how regions are related to each other. In the past our policy has been to let the runtime catch these since that check can be performed with 100% accuracy.

I'll consider it a to-do item to update the reference.

**Comment by lightsighter** [comment]
Do we want to keep this issue open to track the TODO or should we close it?

**Comment by elliottslaughter** [comment]
@lightsighter Can you remind us of the exact set of requirements on copies? Then I can add them to the documentation.

E.g. src and dst must live in the same region tree, but is it a requirement that `src <= dst` or the other way around, and what are the requirements if you issue copies between two regions across the region tree (i.e. `not (src <= dst or dst <= src)`).

**Comment by lightsighter** [comment]
Src and dst do not have to be from the same region tree (that used to be a requirement but it is not any longer). The only requirements right now is that index spaces be of the same dimensionality, have this relationship dst <= src, and the fields that are being copied between are the same size.

The case of when src does not dominate dst will be handled once @streichler implements affine gather/scatter copies in Realm, but then it will be up to the user to specify an affine mapping 'f' for the src or dst region requirements that guarantees that dst <= f(src) or f(dst) <= src respectively.

**Comment by elliottslaughter** [comment]
Just to be clear, does `dst <= src` mean subregion relation, or just that the bounds of src are larger than dst?

**Comment by lightsighter** [comment]
In the master branch it means the former; in the nopaint and later branches it means the later.

**Comment by elliottslaughter** [comment]
I've updated the reference here: http://regent-lang.org/reference/#copies

Please let me know this is inaccurate or confusing.
