### ISSUE TITLE
Support for Reduction and Copy Trees

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#546]
The runtime should really generate reduction trees whenever we are reducing a very large number of reduction instances across a distributed system. Similarly, when doing a post-mapping operation that creates many output copies, the runtime should create broadcast trees of the copies for the instances in a distributed system. It's unclear whether or not this needs mapper guidance or not in order to be done well.

**Comment by streichler** [comment]
@lightsighter and I discussed this some today, and converged on an expansion of the "sharded views" that Legion currently makes in some cases.  The idea is that instead of the actual instances created/used by every shard being sent back to the owner of an equivalence class, a single sharded view is used as a global placeholder and each shard keeps its local list of instances.  In the select_task_options part of an index launch (i.e. before it's been blasted across the shards), a mapper can mark that certain region requirements will used sharded views rather than the normal centrally-managed views.  In addition to limiting communication of instance names, these can be the trigger for optimizations that do hierarchical reductions and/or broadcasts of data (e.g. a sharded reduction view feeding into a sharded read-only view can be implemented with an all-reduce operation).  Although Legion can implement these trees itself at first, we'll eventually want to lower them to the low-level networking layers (e.g. GASNet), and Realm will have to get involved because Legion shards are not necessarily 1:1 with ranks.

**Comment by lightsighter** [comment]
@jiazhihao Can you give me a driver application for this of some kind? Even something simple or written in FlexFlow is fine. I mainly need something to make sure what I'm going to implement is going to support what you need.

**Comment by elliottslaughter** [comment]
I have a use case with a read-only region that is initialized once at program startup, and then needs to be read by every node on every iteration for the rest of the run. The real app for this is MTIP, but I can code up a simplified demo app in Regent if that would help.

**Comment by lightsighter** [comment]
@elliottslaughter Yes, a small demo application would be good. There aren't going to be any changes to the application interface, just changes to the mapping API. The idea is that we will use premap_task to create a new kind of PhysicalInstance object that represents replicated collective view where all the point tasks are going to make their own physical instance, but the runtime should reason about it holistically.

**Comment by lightsighter** [comment]
Design question for everyone on this issue: when doing copies from a "collective view", how do we pick the actual source instance? There are two cases here:

1. We're copying from a "collective view" to a normal instance, so we need to pick a single source instance to be source of the copy. How do we do that? Do we ask the mapper using something like select_*_sources? Do we enumerate all the possible sources (which could be a large number)?
2. We're copying from one "collective view" to another, how do we pick sources for each of the instances in the destination? Obviously the common case is there are the same number of instances in each collective view and natural one-to-one mapping between them, but what happens when there isn't?

I'm thinking that each "collective view" will have an index space associated with it. You can only map an index space with a collective view if the index space of the operation is congruent with the one of the collective view. In case (1), then we won't enumerate all the options but just tell the mapper what the collective view is and have it return the chosen point. The mapper is the one that makes the mapping of points to instances in the collective view anyway so it can choose whether to enumerate points or not. In case (2), we need a way to have the mapper create a mapping between the two collective views so that it can pick a source for each destination. I don't have a good answer for how to do this though. I'm hesitant to introduce a new function type into the interface, but I also don't want the mapper to have to enumerate all the destination points and pick a source point for each one either. Any other ideas?

**Comment by jiazhihao** [comment]
All use cases I have in FlexFlow have one-to-one mapping between different collective views. For (2), i.e., copies between collective views, I think the index space associated with the source/destination collective views should be broadcastable from one to the another (similar to the Numpy-style broadcasting). More specifically, if we assume IS1 and IS2 are the index space for two collective views. In order to copy between the two views, IS1 and IS2 should have the same number of dimensions, and for each dimension, IS1 and IS2 should have the same dimension size or we can broadcast from one's dimension to the other's.

**Comment by lightsighter** [comment]
@jiazhihao I like the broadcasting idea, but NumPy broadcasting is pretty specific that the shape being broadcasted only have an extent of 1 or it doesn't work. I think we probably want this to work even in the case where it can't broadcast in the NumPy sense. We could do something like N % M where M is the extent of the source array along a dimension and N is the extent of the destination array along the same dimension. That's an easy thing to implement, but it also might not be the best thing depending on the machine being used. I guess my question is whether we want to expose that kind of control in the mapper somehow and, if so, how?

**Comment by elliottslaughter** [comment]
The cases I can think of that should be fairly common are:

 a. Allreduce. The source is a collective view but the instances are reduction instances, so you need to get all the contributions. The result is also a collective view since everyone has to read the result.

 b. Broadcast. E.g. there's a small region that almost always read-only (read by everyone) but does occasionally get written to (on a single node). Maybe this case is easy since there should only be one valid region after the write.

 c. Staggered reductions. I.e. think about Pennant. There are N reduction instances, they need to get coalesced into M read-only instances in a non-trivial way.

I think (a) and (c) map into Mike's (2), whereas (b) is sort of the reverse of (1). I can't think of any cases that actually map to (1) unless you're doing a reduction, in which case you need all the contributions anyway---you just get to skip the broadcast back out again (i.e. Reduce instead of Allreduce).

I'm nervous about making the mapper even more complicated, so any simplications we can make to the interface would seem to be welcome. I think Mike's suggestion in the comment two up from this one seems reasonable.

I would also point out that you only really need to have the mapper pick instances if there are multiple valid copies to choose from. E.g. in all the reduction cases, I think the obvious answer is "you need all the contributions". Even in RW cases where you then want to broadcast or gather or whatever, I think usually you'll typically have one valid instance per subregion. The only case that I can think of where we actually end up with multiple valid copies is when we broadcast a RO region, and in those cases I think the obvious answer is "pick the instance closest to me" (which usually devolves into the one that is already in the memory I want it to be in). If you do this suboptimally, then it's not really that terrible, worst case you end up doing another broadcast of the data, but that's only log(N). Once you reach a steady state you shouldn't need to be doing this any more.

E.g., taking @jiazhihao's NumPy style broadcast, assuming I understand correctly: you start with a collective view which is RW. You then want to broadcast that to get a (larger) collective view which is RO. But it seems to me that, once you pick the locations of the destination instances for the RO view, the copies will be entirely predetermined, since the RW view forces there to be exactly one copy of each instance in the source view. So I don't see how there could be more than one possible answer here---therefore, nothing for the mapper to choose (aside from the mapping of the destination view).

Am I missing something?

**Comment by lightsighter** [comment]
The case of (c), at least as it applies to Pennant, is different than what we are discussing here since those are reductions applied to different sub-regions, so it's not really an all-reduce. Making that case build reduction trees is also on my todo list, but it's a much easier case. The actual third case is just the reduction tree case where you have a collective reduction instance reducing to a single instance so you need to build a reduction tree, but again, that case is pretty easy also.

> Even in RW cases where you then want to broadcast or gather or whatever, I think usually you'll typically have one valid instance per subregion.

There will only be a single logical region for these collective instances; we won't be representing sub-regions with collective instances.

> The only case that I can think of where we actually end up with multiple valid copies is when we broadcast a RO region

With control replication, we'll also get replicated instances when the top-level task does inline mappings or attach operations and those won't just be read-only.

**Comment by lightsighter** [comment]
Ok, another important question that we need to answer: how do we make a replicated/collective instance in the mapper? Consider an index space task launch in a control replicated context. Each shard gets its own mapper call for "premap_task" and they all want to make a replicated/collective instance to use for the same region requirement. Can the process of doing the replicated/collective instance creation be itself a "collective" operation in the mapper? If so, who is responsible for the rendezvous? Does Legion have to figure that out, or can we ask the mapper to provide a "tag" that the runtime can use for doing the rendezvous?

**Comment by lightsighter** [comment]
This issue has now been tied up for a while awaiting my refactoring of the instances in the `newinst` branch which is slowly but surely making progress. I will continue to push it forward with the expectation that this will be available by the 20.06 milestone.

**Comment by lightsighter** [comment]
Work on this issue is ongoing in this [merge request](https://gitlab.com/StanfordLegion/legion/-/merge_requests/183)

@jiazhihao A reminder, that I could still really use an example program to test this with.

**Comment by elliottslaughter** [comment]
I may have a use case for this via ExaFEL.

**Comment by lightsighter** [comment]
I'm all for more use cases. The sooner someone gives me some example code to test, the faster this will all go.

**Comment by elliottslaughter** [comment]
I put together a very simplified version of the ExaFEL FXS usecase here:

https://github.com/elliottslaughter/exafel-reduction-demo

There are versions in Python and Regent.

Please note that the region sizes and number of tasks and steps are expected to scale, e.g. a realistic problem size might be on the order of hundreds of elements on each side of the data cube, tasks that scale with number of nodes/cores, and steps in the thousands or even millions.

**Comment by elliottslaughter** [comment]
I added a second demo code, this time for SPI (another ExaFEL app). This one is in Python only (so far). (Use the same repo link above.)

This is again a toy problem size. Realistic problem sizes would be on the order of 1e6 for short_size and 1e10 to 1e12 for long_size.

**Comment by lightsighter** [comment]
Thanks! I'm still working on the implementation in the `newinsts` branch, but the mapping interface is there now if you want to take a crack at writing a mapper to map these.

**Comment by powderluv** [comment]
is newinsts a public branch ? We can't seem to locate it. We are happy to try it out too.

**Comment by elliottslaughter** [comment]
We maintain "private" branches on Gitlab: https://gitlab.com/StanfordLegion/legion/-/tree/newinsts

**Comment by lightsighter** [comment]
Gitlab is the "main" repo where we do most of our work. Github serves as a mirror for some of our more important branches. We also use github as the primary issue tracker since we like their interface better.

**Comment by powderluv** [comment]
We are writing some tests and benchmarks to test out the newinsts branch. Happy to share / upload if it will help testing / development. Also how would the reduction work if the systems did have NCCL support ? Will we be able to use it or will it rely only something that is only aware of the GPU buffers and legion does it by itself ? Thanks

**Comment by lightsighter** [comment]
> Happy to share / upload if it will help testing / development.

Yes, more tests will always be a good thing. There are still some open questions about how to expose this in the mapper.

> Also how would the reduction work if the systems did have NCCL support ? Will we be able to use it or will it rely only something that is only aware of the GPU buffers and legion does it by itself ?

For the moment, Legion is going to be ignorant of NCCL. There is a plan to expose a collective interface in Realm that would be backed by NCCL for GPUs, but that is still a little ways off. One benefit of Legion's collectives though is that we will allow multiple collectives to be in flight simultaneously, whereas NCCL will pretty much serialize all your collectives. NCCL will almost certainly have lower latency than us for the moment for any one collective, but we'll probably be able to achieve better aggregate bandwidth.

As an aside, there is an issue that has moved above this one on my priority list. This issue is looking like end of August for an initial working version for people to try out.

**Comment by eddy16112** [comment]
What if issuing multiple NCCL routines with different cuda streams? Are they also serialized?

**Comment by lightsighter** [comment]
I can't say for sure, but there is a single persistent kernel running on each GPU for NCCL, so I'm guessing that they are serialized.

**Comment by lightsighter** [comment]
@jiazhihao Will FlexFlow's use of collective instances always span all of the GPUs in the machine, or will you sometimes only be performing collectives between a subset of GPUs in the machine?

**Comment by powderluv** [comment]
In our runtime which utilizes Legion similar to FlexFlow we do perform collectives on a subset of GPUs. Im sure FlexFlow could have parallelism strategies that do that too.

**Comment by lightsighter** [comment]
Thanks @powderluv. Is there symmetry in your collectives that are only operating on a subset of the GPUs? For example, do you do `M` collectives with `G` GPUs such that `M * G = N` where `N` is the total number of GPUs, or are there one-off collectives on a subset of GPUs which the other GPUs are doing something completely unrelated?

**Comment by powderluv** [comment]
The latter. We may partition models at a higher level and some GPUs will be doing unrelated later stage processing while some will be running collectives amongst them.  Also in some cases like AWS P3dn.24xlarge instances each set of 4 GPUs are fully connected by NVlink and they traverse the PCIe bridge to connect to the remaining 4 - so for performance reasons we may partition models to live in these nvlink connected islands and the collectives will be operating on just on the gpus in the island.

**Comment by lightsighter** [comment]
The new equivalence set work has delayed this to the next milestone.

**Comment by lightsighter** [comment]
Still a strong precondition for #765 which is slated for 21.03 now, so keep it in the same release.

**Comment by lightsighter** [comment]
There is now support for collective views in the `control_replication` branch of Legion and will soon be in the `master` branch of Legion. This allows mappers to tell the runtime to check for collective behavior between point tasks all mapping the same logical region in an index space task launch, and if so perform the mapping for those collectively with a collective view. When mapping tasks or other operations that need to pull data from currently valid collective views, Legion will issue collective copies (tree broadcasts/reductions or butteryfly all-reduces) for asymptotically good performance.

Notes for the future: we are still intentionally not building broadcast/reduction trees for non-collective views (e.g. in the case where we have a large number of reduction instances to reduce down to a single instance, we could fold them together). The motivation for this is we still want the mapper to control when these tree reduction copies should occur, and this process should be deterministic depending on whether the mapper instructed the runtime to look for collective behavior in the task launch or not.
