### ISSUE TITLE
Support for CUDA Fortran in the Realm CUDA Hijack

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#570]
We need to add support for CUDA Fortran in the Realm CUDA hijack. Attached is a very basic hello world example from @sdcohen that we can use for testing if things work.
[hello-fortran-legion.tar.gz](https://github.com/StanfordLegion/legion/files/3412471/hello-fortran-legion.tar.gz)

**Comment by streichler** [comment]
Commit e4b9551 handles the apparently-not-illegal case of registering a kernel with the cuda runtime that doesn't actually exist.  With that out of the way, the attached repro case then fails because it is calling `cudaDeviceSynchronize` outside of a CUDA task, but that's easily fixed by removing the (unnecessary and ineffective anyway) call.
