### ISSUE TITLE
Regent: Error in running Cholesky.rg in legion/language/examples

### ISSUE THREAD

**Issue by qyz96** [StanfordLegion/legion#574]
Hi, I am having an error when trying to run cholesky.rg in legion/language/examples

[adncat@sh-101-58 ~/legion/language]$ regent examples/cholesky.rg
table: 0x7f1a55ef94e8
...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:938: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:938: in function 'open_region_tree_top_finalize'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:974: in function 'open_region_tree_top'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:998: in function 'open_region_tree'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:2445: in function 'expr'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:3236: in function 'stat_expr'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:3301: in function 'fn'
        src/asdl.lua:18: in function 'map'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:3022: in function 'block'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:3098: in function 'stat_for_num'
        ...
        src/asdl.lua:18: in function 'map'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:3022: in function 'block'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:3098: in function 'stat_for_num'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:3268: in function 'fn'
        src/asdl.lua:18: in function 'map'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:3022: in function 'block'
        ...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:3330: in function <...gion/language/src/rdir/plugin/src/regent/flow_from_ast.t:3317>
        ...w/legion_fresh/legion/language/src/regent/passes_hooks.t:41: in function 'optimize'
        ...warszaw/legion_fresh/legion/language/src/regent/passes.t:63: in function <...warszaw/legion_fresh/legion/language/src/regent/passes.t:48>
        examples/cholesky.rg:256: in main chunk

**Comment by elliottslaughter** [comment]
Can you try `regent examples/cholesky.rg -fflow 0`?

Unfortunately I think this is one test where the RDIR pass fails (which is what `-fflow` controls).

**Comment by qyz96** [comment]
This gives the following error?
[adncat@sh-101-58 ~/legion/language]$ regent examples/cholesky.rg -fflow 0
table: 0x7f4af06b9130
[0 - 7f4af47f9780] {4}{threads}: reservation ('DMA request queue') cannot be satisfied
ELAPSED TIME =   2.725 ms

**Comment by elliottslaughter** [comment]
The `reservation cannot be satisfied` part is a warning that says you're trying to oversubscribe the machine. This is only an issue if you are trying to do performance measurements. (Though note, this Cholesky code hasn't really been evaluated for performance, so you probably don't want to measure its performance anyway.)

The `ELAPSED TIME` shows the code is running to completion.

**Comment by qyz96** [comment]
Got it, thanks! Suppose that I do want to evaluate the performance, would I only need to do some minor revisions for the code?

**Comment by elliottslaughter** [comment]
If you only want to do a single-node evaluation, you could probably get by with the code as it is now. (Though probably it would best to show us your results first so we can double check for anomalies.)

If you want it to perform well at scale, it really needs to be using index launches. Unfortunately this issue is more fundamental, due to the way the code is structured, the compiler can't perform the analysis necessary to make this optimization work. Issue https://github.com/StanfordLegion/legion/issues/551 would be a partial fix (and we have that fix in the works), but the issues in Cholesky go beyond this.

If you really want Cholesky specifically I'd be happy to talk about what you'd need to do, but if you just want some example codes to evaluate I'd pick one of the other ones we've used in our papers.

**Comment by qyz96** [comment]
Yes, I am interested in evaluating the performance of Cholesky specifically. It would be great if you could give me some guidance on it. Thanks!

**Comment by elliottslaughter** [comment]
I talked about this a bit with @magnatelee and we think the place to start is by restructuring the code to match this structure:

https://www.oerc.ox.ac.uk/sites/default/files/uploads/ProjectFiles/ASEArch/starpu.pdf#page=41

You'll still hit #551 when you try to index launch, but the good news is that it doesn't require anything else (whereas the current code would require the compiler to reason about the relationship between `k`, `x`, and `y`).

That can go on in parallel with us finishing up the fix for #551. Let us know if you're interested in doing this.

After that it's going to more the usual performance tuning type of stuff: profiling, checking for anomalies, and fixing them as necessary. We can go over that more when we get there.

**Comment by qyz96** [comment]
Yes I will look into the references. It would also be great if I can be notified when #551 is fixed. Thanks!
