### ISSUE TITLE
Regent: Formal parameter space overflowed

### ISSUE THREAD

**Issue by mariodirenzo** [StanfordLegion/legion#638]
Currently, Regent returns the following error
```
src/tcuda.cpp:157: nvvm error reported (9)
 (): Error: Formal parameter space overflowed (4469 bytes required, max 4096 bytes allowed) in function [name of the task]
```
if the arguments of a task compiled with `__demand(__cuda)` exceed a certain size.
It would be nice to have a way to pass large arguments to the task or at least to have an error from the compiler that informs the user about the memory requirement of each argument.

**Comment by mariodirenzo** [comment]
Is there any plan to allow people to pass larger data structures (of constants) to the tasks on GPUs?

**Comment by lightsighter** [comment]
Is there a way to recognize/annotate constants for kernels so we can put them in the constant cache? It would probably go a long way to reducing the need to pass things as parameters. Either that or try to inline them directly if possible.

**Comment by mariodirenzo** [comment]
I am not aware of any annotation that can be used in regent to define an argument of a task as a constant.
However, from what I know, parameters are passed to tasks by value, so they are effectively constant unless one of them is returned.

**Comment by elliottslaughter** [comment]
Right, I think this is a question for @magnatelee. In theory any variable that is not written to could be put into the constant cache.

**Comment by magnatelee** [comment]
Moving read-only variables to the constant cache is my plan and Terra does have support for the constant cache. I'm still playing around with it using a toy example and will soon implement support in Regent.

**Comment by elliottslaughter** [comment]
I've been talking with @magnatelee and we think it would be easier to use a DeferredBuffer (internally) in Regent instead of constant cache. There might be a minor performance hit but right now I think this is pretty theoretical, so until we get a compelling use case the DeferredBuffer seems like a better idea. That way we're not limited to the constant cache size.

The plan is to branch on the size of the parameters, and if the parameters are too large move them into a DeferredBuffer.

This then decouples us from Terra's constant cache support, which does not have an officially supported way to update constants. If we were to go with the original plan we'd either need to hack around that or else update Terra to improve that support first.

**Comment by magnatelee** [comment]
This should be fixed by 72998c85. @mariodirenzo Can you confirm the fix?

**Comment by mariodirenzo** [comment]
Thanks for pushing a fix.
I'm sorry but I had to workaround the issue a few months ago now I do not have the piece of code that was triggering the error anymore.
I’ll comment here (and in case reopen the issue) if I encounter the problem again

**Comment by magnatelee** [comment]
@mariodirenzo Sounds good. Closing this issue for now.
