### ISSUE TITLE
legion: avoiding deadlock with concurrent must epoch launches

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#659]
The Legion runtime currently has no mechanism to prevent deadlock when multiple independent must epoch launches overlap on two or more processors.  This issue hasn't been observed in the wild, but deadlocks are generally bad, so it'd be good to have a plan for fixing this.  The priority of it probably depends on whether @jiazhihao 's efforts with using nccl for inter-gpu reductions run into the problem.

An obviously-sufficient approach is to serialize all must epoch launches, no matter which context they belong to, but there ought to be a more elegant approach if we need/want to figure it out.

**Comment by lightsighter** [comment]
@elliottslaughter @magnatelee @alexaiken @jiazhihao for visibility. I actually don't think anything else other than serializing (in program order) all must epoch launches that use overlapping processor sets is safe. Someone else can try to convince me I'm wrong, but I'm confident that I will be able to create a counter example that results in deadlock for anything else assuming that tasks can go off and block on some external collective API call like NCCL and Realm won't be able to preempt the task.

**Comment by elliottslaughter** [comment]
To clarify, is deadlock possible if you only use Realm synchronization primitives? Maybe an example would help.

**Comment by streichler** [comment]
If you only use Realm synchronization primitives, you're fine.  The problem comes when a task is running on a processor and refuses to finish (or yield via a Realm synchronization primitive) until another task can run on another processor.  This could happen if they are communicating directly through memory (e.g. via a region with simultaneous coherence) or using a third-party library that incorporates synchronization (e.g. MPI or NCCL).

**Comment by elliottslaughter** [comment]
Ok, I can think of some cases for psana where forcing must epoch launches to execute in program order basically destroys any ability to do concurrent execution. I do communicate through Python global variables (which I lock, but the locks are not held for long and I don't see how I could have deadlock in my case).

It occurs to me that maybe I should be using a nested must epoch launch in order to fully match the Legion semantics. Have you thought about what that would even mean in your proposal?

**Comment by lightsighter** [comment]
> I do communicate through Python global variables (which I lock, but the locks are not held for long and I don't see how I could have deadlock in my case).
This is fine. These are locally blocking, which means forward progress doesn't rely on synchronization with other tasks in the same must epoch launch. The problems occur when you do blocking collective operations which require synchronization with other tasks in the same must epoch launch and that communication can result in blocking that Realm does cannot preempt.

**Comment by lightsighter** [comment]
@streichler and I talked today. The current plan that we propose is a two-fold solution to this problem:

1.  I am going to go through and implement a compile-time opt-in safe-mode for must epoch launches at the top-level. By compiling with a special macro (something like -DSAFE_MUST_EPOCH_LAUNCHES) then users are guaranteed that two must epoch launches with overlapping processor sets will be serialized. Note this will only apply to must-epoch launches done in the top-level task! There will be no ordering of must-epoch launches done from lower levels of the task tree.
2. For a longer term solution, we would like to leverage Realm support for collectives which is not implemented yet to handle these cases. Legion will offload must-epoch launches onto Realm collective operations and Realm can then speculatively execute them and detect deadlock cases lazily. 

Ask questions or raise concerns here.

**Comment by lightsighter** [comment]
I did something even simpler for now. If you compile with `-DSAFE_MUST_EPOCH_LAUNCHES` in `CC_FLAGS` then we will insert an execution fence before every must epoch launch. This guarantees that  all must epoch launches will be executed in program order. It also means that the right thing will happen with control replication as well. This is a pretty heavy hammer, but for the moment I think it is fine because most epoch launches that we are doing are across the whole machine and aren't really designed to run concurrently with each other. If someone wants to argue that we need something more fine grained then they are are welcome to do so. For now, I believe we have the mechanism needed to make everything functionally equivalent, so I'm going to move this issue to be an enhancement going forward and put it in the backlog.

**Comment by lightsighter** [comment]
This was fixed with this merge request that also added support for concurrent index space task launches:
https://gitlab.com/StanfordLegion/legion/-/merge_requests/589
