### ISSUE TITLE
Better Legion error message when no processors of a given type exist

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#66]
When you run the thrust_interop example without `-ll:gpu 1`, you get:

```
thrust_interop: ../../runtime/legion/runtime.cc:10522: LegionRuntime::HighLevel::AddressSpaceID 
LegionRuntime::HighLevel::Runtime::find_address_space(LegionRuntime::HighLevel::Processor) 
const: Assertion `finder != proc_spaces.end()' failed.
```

I believe this occurs because a task is being launched that only has a GPU implementation, and either
the default mapper or the runtime is not noticing when none of those exist.  This is a fairly common mistake for a user to make when running a Legion application, so a better error message would be nice to have.

**Comment by lightsighter** [comment]
So just to be clear, we want it to be a failure for the mapper to specify any target processor that is not an actual processor?  In this case, the mapper picked NO_PROC which is clearly wrong.  However, I can also envision a case where the mapper picks a processor that used to exist but no longer does (due to a hard fault or something), and I'm not sure we want that to be a hard stop if the mapper makes that mistake.  To summarize: we can either make it a hard failure, or we can figure out a way to hand the problem back to the mapper.

**Comment by streichler** [comment]
The case for which I would like a more helpful (and fatal) error message is when a task is launched and the only available variants for that are for processor kinds that do not exist anywhere in the machine.  This is a case where throwing it back to the mapper to decide again can't result in any other answer.  That said, it seems like this information may only be available to the mapper and therefore should be an error check in the default mapper rather than in the HLR.

In cases where the mapper's chosen processor has vanished, or when the mapper knows how to create new variants of the task in question, I agree throwing it back to the mapper is preferable to a fatal error.

**Comment by lightsighter** [comment]
Alright, adding this to the list of things to do when updating the mapping API.

**Comment by lightsighter** [comment]
This has definitely been fixed by the new mapper API.
