### ISSUE TITLE
Detect (and Maybe Work-Around) Multi-Tenancy GPU Cases

### ISSUE THREAD

**Issue by lightsighter** [StanfordLegion/legion#675]
It would be nice if Realm could detect multi-tenancy use cases with GPUs and do something more intelligent than report a CUDA driver error like it does today:

```
CU: cuCtxCreate(&context, CU_CTX_MAP_HOST | CU_CTX_SCHED_BLOCKING_SYNC, info->device) = 101 (CUDA_ERROR_INVALID_DEVICE): invalid device ordinal
/legion/runtime/realm/cuda/cuda_module.cc:2257: Realm::Cuda::GPU::GPU(Realm::Cuda::CudaModule*, Realm::Cuda::GPUInfo*, Realm::Cuda::GPUWorker*, int): Assertion `0' failed.
```

Ideally it would try to find GPUs that are unused too, but just a better error message would be sufficient.

**Comment by streichler** [comment]
With commit 10ea064, Realm understands the following command-line parameters:

`-cuda:skipgpus N` - Do not try to use the first N gpus.  You can do this with CUDA_VISIBLE_DEVICES in most cases, but this also works to reserve GPUs for use by (often non-configurable) non-Legion code in the same process as well.

`-cuda:skipbusy` - Silently skip over GPUs for which a CUDA context cannot be created (either due to being in exclusive mode or because so much memory is already in use that the context itself cannot be allocated).  Note that this does not change the behavior of `-ll:gpu N` - Realm will still provision exactly `N` GPUs or die trying.

`-cuda:minavailmem M` - Also silently skip over GPUs that have less than `M` megabytes of available device memory (value specified can also use scale prefixes - e.g. `12g` for 12 GB).  Useful for avoiding out-of-memory conditions on shared GPUs.  Note that this check is done at context creation time rather than actual allocation time later, and needs to account for more than just what's in `-ll:fsize`.  It also provides no protection against another application that allocates more device memory after Realm has created its context - that's what the CUDA exclusive process mode is for.

**Comment by streichler** [comment]
@lightsighter are these controls sufficient for your needs?

**Comment by lightsighter** [comment]
I'm pretty sure I reported this bug on behalf of @mjgarland so I'll let him respond.

**Comment by lightsighter** [comment]
I think we've addressed this issue sufficiently and the use of `-cuda:skipbusy` has been incorporated into Legate.
