### ISSUE TITLE
Regent: Force error if `__demand(cuda)` is not satified

### ISSUE THREAD

**Issue by sparkasaurusRex** [StanfordLegion/legion#699]
I would like to have the option to throw an error when `__demand(cuda)` is not satisfied. Right now, I only get warning when this happens and then no cuda code is generated. I think down the road this could be a huge issue for users wondering why suddenly there program is much slower and not using GPUs.

Here is the warning I'm getting
```
file.rg:39: ignoring demand pragma at file.rg:39 since calling cuInit(0) failed for some reason (CUDA devices might not exist)
```

Maybe there could be a command line option to Regent that forces this.

**Comment by magnatelee** [comment]
The meaning of __demand(__cuda) has changed as of commit 4cc2439e. The compiler will now raise a hard error when it cannot do CUDA code generation for some reason. There is now an __allow(__cuda) pragma that implements the old behavior. @sparkasaurusRex feel free to close the issue if you think the fix is sufficient.

**Comment by sparkasaurusRex** [comment]
The only issue that I can think of is that now `__demand(cuda)` does not allow for testing correctness without a GPU. @magnatelee would it make sense add an option like `--relax-demand-cuda`? I do like the distinction between `__demand` and `__allow`, though.

**Comment by magnatelee** [comment]
Okay. Commit 9a30fcce provides the `-fwarn-as-error` flag, which promotes a warning to an error. A combination of `__allow` and the flag will give you what you want. Can you pull and see if the flag works for you?

**Comment by sparkasaurusRex** [comment]
I found that I needed to add the flag `-fwarn-as-error 1` to Regent to enable the error message. Other than that, it works perfectly. Thanks!

**Comment by elliottslaughter** [comment]
@magnatelee and I were talking, and we were wondering if the following semantics would be more obvious:

  * If the user passes `-fcuda 1` to the compiler, but CUDA is not available (for any reason, e.g. perhaps there are no GPUs on the machine), then this an error. This is true regardless of the contents the program, i.e. whether or not it contains any `__demand(__cuda)` tasks.
  * `__demand(__cuda)` is understood to mean: "If CUDA were available, would this task generate correct CUDA code." It no longer has anything to do with whether CUDA is actually available on the machine or not.

This means if you want to be 100% sure you're getting CUDA code, you run with `-fcuda 1` and mark all your tasks as `__demand(__cuda)`.

If you don't have a GPU, but want to make sure that users who do will be able to run with GPU tasks, then you mark you tasks with `__demand(__cuda)` and either pass `-fcuda 0` or no `-fcuda` flag at all.

Running with no `-fcuda` flag will use GPUs if they are available, but will not generate any warnings or errors if they are not. (Or possibly, we can warn on `__demand(__cuda)` to hint that GPUs are not enabled and the user should run with `-fcuda 1` to figure out why.)

Would this be more clear? It feels more orthogonal to me than the current approach.

If we do this, we can make `__allow` the default again, but change the semantics so that we do still do CUDA code generation on allow (so e.g. if you have an un-annotated program, and run with `-fcuda 1`, it will CUDA-ize everything that it can).

**Comment by sparkasaurusRex** [comment]
> * If the user passes -fcuda 1 to the compiler, but CUDA is not available (for any reason, e.g. perhaps there are no GPUs on the machine), then this an error. This is true regardless of the contents the program, i.e. whether or not it contains any __demand(__cuda) tasks.
This sounds like a good solution to my original problem since it is easy enough for the user to pass `-fcuda 1`.

**Comment by sparkasaurusRex** [comment]
By the way @magnatelee, I noticed that I got this warning even though I had no `__demand(__cuda)`.

```
:0: ignoring pragma at :0 since the cuInit function is missing (Regent might have been installed without CUDA support)
```

This sounds like a bug in your last commit.

**Comment by magnatelee** [comment]
I pushed changes that implement the semantics that we agreed with. The availability of CUDA code generation is required only when the user passed `-fcuda 1` and its applicability is checked regardless of the flag. When CUDA is unavailable and there are tasks with `__demand(__cuda)`, the compiler will print warning messages like it did previously. I didn't go all the way to making `__allow` by default as it requires some changes in the compiler to track the parallelizability separately for different codegen paths. @sparkasaurusRex Can you pull and try again? I believe the other spurious warning message you reported should be also fixed.

**Comment by sparkasaurusRex** [comment]
Works as expected!
