### ISSUE TITLE
Prof: embed resources in single file to enable loading locally on modern browsers

### ISSUE THREAD

**Issue by ellishg** [StanfordLegion/legion#709]
Firefox updated its CORS security policy so that legion_prof does not work. When I open up `index.hmtl` in firefox, nothing shows up and I get this warning.

"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///.../legion_prof/json/scale.json. (Reason: CORS request not http)."

This link is referenced in the warning.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

A local fix is to type `about:config` in Firefox's address bar and search for `privacy.file_unique_origin`. Setting this to `false` will disable the security check.

I don't know if Chrome or Safari have the same issue.

**Comment by seemamirch** [comment]
We will need to update https://legion.stanford.edu/profiling/#legion-prof (Legion Prof Troubleshooting section) - it mentions a similar issue for Chrome.


On Dec 12, 2019, at 4:02 PM, Ellis Hoag <notifications@github.com<mailto:notifications@github.com>> wrote:


Firefox updated its CORS security policy so that legion_prof does not work. When I open up index.hmtl in firefox, nothing shows up and I get this warning.

"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///.../legion_prof/json/scale.json. (Reason: CORS request not http)."

This link is referenced in the warning.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

A local fix is to type about:config in Firefox's address bar and search for privacy.file_unique_origin. Setting this to false will disable the security check.

I don't know if Chrome or Safari have the same issue.

**Comment by lightsighter** [comment]
Pretty much all browsers today have this enabled including Chrome and Safari. I think the right thing to do is actually to make a way to start-up a light-weight webserver with legion_prof.py on each person's machine so that they don't have to deal with all the browsers now that block this common path to prevent cross-site scripting attacks.

**Comment by streichler** [comment]
Are the browsers happy if you mash the javascript and json directly into the HTML file instead of providing them as separate files?  This appears to be how the chrome tracing stuff works.

**Comment by elliottslaughter** [comment]
I've updated the instructions here so that they're hopefully more obvious: https://legion.stanford.edu/profiling/#using-legion-prof-locally

Are we still interested in a technical solution to this problem or is a documentation-only fix sufficient?

**Comment by lightsighter** [comment]
I'm still somewhat interested in a technical solution that will do what @streichler suggested and cram everything into one file. Do we know that this will work for all the browsers or is it just firefox that allows this?

I think we should also update the wiki with information about how to address this issue too.

**Comment by elliottslaughter** [comment]
I think it should work, it's just a matter of finding someone with the time to do it.

I've updated the title of this issue to reflect what we're trying to do now.

**Comment by seemamirch** [comment]
Legion Prof deals with json and multiple tsv files. The data in tsv files can be large - they contain proc/channel/memory etc. timeline information. As a result they are selectively loaded on demand - i.e. when the user expands a particular view. To make the single html file work - we need to cram those tsv files too - which may not be what we want to do.

**Comment by streichler** [comment]
could we experiment with embedding them as a base64-encoded string or something and only decoding it when needed?  I'm guessing that the cost of pulling the data over the network is tiny compared to the parsing of it

**Comment by elliottslaughter** [comment]
We're actually going the opposite direction with this, because single files don't lend themselves well to tiled formats.

However, we do have the ability to load a local viewer, which I think mostly handles the issue here (no `file://` URLs are now required).
