### ISSUE TITLE
Legion: Inline partitioning operator

### ISSUE THREAD

**Issue by magnatelee** [StanfordLegion/legion#741]
Currently, creating a partition from a set of ranges cannot be done without going through the partition-by-image-range call. This requires the ranges to be first stored in a region, either by a task or an inline mapping, which will be later mapped again for the image operator. In common cases where each subregion can be specified by a single range, going through all these steps is both inefficient and inconvenient. It would be nice to have an "inline" partitioning operator that constructs a partition using a set of ranges stored in somewhere other than a region.

One concern with this inline partitioning operator is that this could easily fall back to the old style coloring API, which should be avoided as much as possible. For that, I think we would want to limit the number of ranges that are associated with each color in the color space, preferably to 1, which can be easily enforced by the type system. Alternatively, we can keep the container for ranges being generic and instead raise a warning when the number of ranges for any of the colors exceeds a certain threshold.

**Comment by lightsighter** [comment]
Another option is to have the interface support something like `vector<Domain>` and/or `vector<IndexSpace>` so that if users want to go through a really kill themselves by making really sparse Realm index spaces (represented by `Domain`) or to use existing index spaces then they can do that, which I think I prefer.

One obvious question regardless of the interface is what happens to ranges that our outside the bounds of the parent index space that is being partitioned. Do we prune or raise an error?

Another question is whether we want to be explicit about the color space? For example we could do something like `map<DomainPoint,Domain>` for mapping points in the color space.

**Comment by magnatelee** [comment]
I believe the semantics of the partition-by-image-range is to take an intersection between ranges and the index space being partitioned, so the new operator better be consistent with this.

I think having the color space a separate argument would be convenient for cases where the color space is dense but only some of the subregions are not empty.

A bonus point would be to make this operator take future maps. The domains for subregions will likely be computed by tasks and being able to pass future maps to the operator will be good for eliminating blocking on them.

**Comment by elliottslaughter** [comment]
Can you sketch the proposed API?

*Definitely* want a separate color space. That was always a huge pain point in the old style APIs. I don't want to go back to a world where you have to write `coloring[color];` to ensure a color exists.

**Comment by elliottslaughter** [comment]
Overall, I'm fine with this idea. I agree for simple cases it's nice to be able to just hand Legion the partitioning you want, when you know exactly what you want.

Though having said that, image/preimage(_range) are not _that_ inconvenient in Pygion since you have a syntax for (what are effectively) region literals. But I'm not sure this is a direction we'd ever go with C++: https://github.com/StanfordLegion/legion/blob/stable/bindings/python/examples/partition_by_image_range.py

**Comment by lightsighter** [comment]
Here are some draft runtime method type signatures:

```
IndexPartition create_partition_by_coloring(Context ctx, IndexSpace parent, IndexSpace color_space, std::map<DomainPoint,Domain> &coloring, PartitionKind part_kind = COMPUTE_KIND, Color color = AUTO_GENERATE_ID);

template<int DIM, typename COORD_T, int COLOR_DIM, typename COLOR_COORD_T>
IndexPartitionT<DIM,COORD_T> create_partition_by_typed_coloring(Context ctx, IndexSpaceT<DIM,COORD_T> parent, IndexSpaceT<COLOR_DIM,COLOR_COORD_T> color_space, std::map<Point<COLOR_DIM,COLOR_COORD_T>,DomainT<DIM,COORD_T> > &coloring, PartitionKind part_kind = COMPUTE_KIND, Color color = AUTO_GENERATE_ID);

IndexPartition create_partition_by_coloring(Context ctx, IndexSpace parent, IndexSpace color_space, const FutureMap &coloring, PartitionKind part_kind = COMPUTE_KIND, Color color = AUTO_GENERATE_ID);

template<int DIM, typename COORD_T, int COLOR_DIM, typename COLOR_COORD_T>
IndexPartitionT<DIM,COORD_T> create_partition_by_typed_coloring(Context ctx, IndexSpaceT<DIM,COORD_T> parent, IndexSpaceT<COLOR_DIM,COLOR_COORD_T> color_space, const FutureMap &coloring, PartitionKind part_kind = COMPUTE_KIND, Color color = AUTO_GENERATE_ID);
```

**Comment by elliottslaughter** [comment]
I'd flip the order of the `color_space` and `coloring` arguments, to make it more consistent with other partitioning calls, but otherwise looks fine to me.

**Comment by magnatelee** [comment]
The signatures (in particular the last one) look fine to me, too.

**Comment by lightsighter** [comment]
How would we want the ones that take a std::map<DomainPoint,Domain> for the coloring to be exposed in the C API?

**Comment by elliottslaughter** [comment]
Two arrays, one of DomainPoint and one of Domain, and a size?

**Comment by lightsighter** [comment]
There is support for this now in both the master and control replication branches with the `create_partition_by_domain` set of calls. To test it I've removed the partitioning shim code so that all the old coloring-based partitioning calls (which are officially deprecated, but are still used by many apps and Regent) now are translated to calls to `create_partition_by_domain` so we should have pretty good test coverage. I also added C API bindings for the calls so that they can be easily used from Python. Everything is passing CI so I'm going to close this issue. If we need further extensions we will open a new issue.

**Comment by lightsighter** [comment]
Also forgot to mention, this code will be significantly faster with control replication if the color space of the partition being made aligns perfectly with the index space of the operation that created the future map. Otherwise it's going to suck. Don't say I didn't warn you. ;)
