### ISSUE TITLE
CI: update compilers we test with

### ISSUE THREAD

**Issue by streichler** [StanfordLegion/legion#809]
So gcc and clang are both up to (or nearly up to) version 10, and we're beginning to see issues that only show up in these newer compilers.  Let's get them into the CI runs, and consider removing some of the compiler versions in the middle.

**Comment by elliottslaughter** [comment]
What compilers do you want to test?

**Comment by streichler** [comment]
At least gcc 10 and clang 10, as there are known users of both of those now.  I don't know enough about version 9 of each to know whether it's ok to skip, so I'd probably add those in and drop (somewhat arbitrarrily) 5 and 7 of each of clang and gcc.

Note that gcc 10 will require building a new docker image - it doesn't show up in ubuntu until focal (20.04).

**Comment by elliottslaughter** [comment]
Maybe we should drop some on the bottom end? Ubuntu 16.04 is GCC 5, and most supercomputer facilities seem to be upgrading their compilers aggressively now (and older machines are being decommissioned).

We could make GCC 5 the default in our tests, get rid of 4.8 and either drop 4.9 or relegate it to our "extras" section.

Similarly, I think we only have Clang 3.5 because Terra requires it for debug symbols, but it's tested separately in Terra's CI and all our practical users are on 3.8 or above at this point (I believe).

**Comment by streichler** [comment]
Commit 6f4120f added CI tests using gcc9, gcc10, clang9, and clang10.  No old compilers were removed at this time - I figure we can address that as part of #731.
