### ISSUE TITLE
Legion: semantics of deletion

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#812]
Currently, deletion is recursive and applies to the entire subtree underneath the object in question. So if you delete an index space, that applies to all regions created with that index space, if you delete a region, it applies to all partitions of that region, if you delete a partition, to all subregions of the partition, and so on.

The current semantics are **not** reference counted. Duplicate deletion is an application bug, and note that this includes transitive deletion.

I've been trying to implement correct automatic deletion of resources in Regent, and currently this makes it a pain to combine with manual deletion (i.e. Regent's `__delete` operator). In order to make sure that I don't double delete a region R, I need to track the dynamic liveness of R in a variable. But in order for this to be correct, I need to track all the way up the tree, i.e. with a chain like A->B->C->D, in order to make sure a deletion of D is safe I also need to check A, B and C.

I've been wondering if an alternative, reference counted semantics would be nicer to use. The tricky part here is that a naive semantics could be really painful---you probably don't want to have to go delete every single subregion of a partition, and so on.

My proposal is that only certain APIs, like `create_*` will add references. Hopefully we'll be able to come up with a rule that is reasonably obvious for which APIs would do this. To a first approximation, anything that is explicitly `create_*`'d should also be `destroy_*`'d. If a partition of P is deleted after its parent region R, R will be kept alive until P is deleted, since the creation of P holds a reference on the entire subtree up to the root.

Thoughts?

**Comment by lightsighter** [comment]
Can you list exactly which calls will create a reference? I'm fine with switching to reference counting semantics as it will make my life easier. It will cause a bunch of existing programs though to start leaking things. I'm also going to make it your responsibility to discuss to get everyone's approval too. :)

**Comment by elliottslaughter** [comment]
Unless otherwise specified I mean all overloaded versions of a method call under a given name.

`Runtime` method calls that create references:

* create_index_space
* union_index_spaces, intersect_index_spaces, subtract_index_spaces
* create_index_partition (note: in this and all subsequent partition calls, the reference is on the **partition only**; the partition holds references on all **direct** subregions and keeps them alive as long as the partition is alive)
* create_equal_partition
* create_partition_by_weights
* create_partition_by_union, create_partition_by_intersection, create_partition_by_difference
* create_cross_product_partitions (note: creates references on all of the output partitions)
* create_partition_by_restriction
* create_partition_by_blockify
* create_partition_by_domain
* create_partition_by_field
* create_partition_by_image, create_partition_by_image_range
* create_partition_by_preimage, create_partition_by_preimage_range
* create_pending_partition
* create_field_space
* create_logical_region
* create_field_allocator (I'm not 100% sure about this one, but seeing as it's called "create" I suppose it should take a reference on the field space it's created for)

A non-exhaustive list of methods that **DO NOT** create references:

* create_index_space_union, create_index_space_intersection, create_index_space_difference (note: the reference is held by the **parent partition** created with create_pending_partition, so there isn't a need for a reference on the individual subspaces)
* get_index_partition
* get_index_subspace
* get_index_partition_color_space_name
* get_parent_index_partition
* get_logical_partition, get_logical_partition_by_color, get_logical_partition_by_tree (note: the logical partition is implicitly held as long as both the region and its index partition are held)
* get_logical_subregion, get_logical_subregion_by_color, get_logical_subregion_by_tree (note: the subregion is held as long as both the region and its index partition are held)
* get_parent_logical_region

Fortunately the current naming is pretty consistent so it fits the "create" heuristic pretty well.

**Comment by elliottslaughter** [comment]
I realized last night that there's a way to unify the current semantics with my new semantics proposed above. We can add an optional `recurse` parameter to `destroy` methods that defaults to `true`. When it is `true`, we keep the current semantics. When it is `false` we use the new semantics.

This is consistent because under the new semantics (most) runtime objects have their own reference count, and the old semantics (deleting the subtree under an object) amounts to recursing down the tree and clearing all child references. The new semantics would essentially skip the recursion but otherwise keep all the other reference counting behavior. In this way we can keep the utility of allowing users to do one delete call for an entire tree, but also allow the reference counting behavior that makes things easier for the compiler to code generate to.

**Comment by lightsighter** [comment]
Several questions:

- Does `recurse` also imply deleting logical region trees associated with index space trees? For example, if I say `recurse` on the deletion of an index space tree, do that also imply deletion of any corresponding region trees instantiated from that index space tree? Or does recurse only imply "vertical" recursion and not "horizontal" recursion?

- What about logical partitions? We never explicitly "create" those with an explicit call. They are lazily instantiated whenever a client program first asks for it with `get_logical_partition_by_*`. However, I think you want those to potentially live past when a call to `delete_index_partition` is performed, so I feel like there need to be references on those. However, it's racy to know which is the first task to instantiate one of those logical partitions, so how do you decide who ends up responsible for the deletion?

**Comment by elliottslaughter** [comment]
* `recurse`: I can see arguments either way, but for consistency with our current semantics I'd be inclined to make it do both "vertical" and "horizontal" per your terminology.

* One option is to add an explicit `create_logical_partition` call that is identical to `get_logical_partition` except that it also adds a new application reference. For our users' sanity I do not think we should allow `get_*` calls to add references. The other then has to call `delete_*` once for ever call to `create_*` (i.e. each `create_*` adds one reference and each `delete_*` removes one reference).

  Another option is to add explicit reference counting calls `add_reference` and `remove_reference`, but I don't think I'm a fan of this approach.

  A third option is to just say that the user has to keep the index partition alive as long as they want access to any corresponding logical partition. In a certain sense, this may actually be a more consistent semantics: because the index partition is going to keep alive not just the logical partition in the one region tree the user cares about, but in all region trees, the logical partition doesn't really "exist" in the same sense of the word as other objects. That's why we never gave it its own `create` method originally, and it may still make sense to keep things this way.

**Comment by opensdh** [comment]
Presumably `recurse` means whatever the calls mean now, but that's not clear and not documented.  The tree model is not obvious (at least to this user): for example, if `destroy_index_space` takes logical regions down with it because they were made from it, why wouldn't `destroy_field_space` do the same thing, making it impossible to use both?  Can I `destroy_logical_region` long **before** I destroy the parent index space in case I want to switch to a new `FieldSpace` for work later in the process?

As a user of the C++ API, what I most **want** is class types that _own_ Legion resources so that I don't have to do anything to have the correct set of objects live at any given time.  Maybe, absent reference counting, it's not possible to avoid certain dangling-reference situations (_e.g._, an index space owns its logical regions, therefore `LogicalRegion` is non-owning and can dangle if its parent index space has been destroyed), but in that case we should at least have `Legion::RAIIIndexSpace` (with a better name) that both manages lifetimes and indicates by its existence which things need their lifetime managed.  It's my attempt to make such classes myself (and thus cause FleCSI to reliably destroy things) that has gotten us talking about this situation.

I realize that the C++ API does not emphasize ease-of-use (hence Regent), but all these issues must be _documented_ whether or not they are automated.

**Comment by elliottslaughter** [comment]
I think there is some slight confusion here, so let me clarify. Suppose you have a index space `I`, field space `F`, region `R` (of `I` and `F`) and partitions `IP` (of `I`) and `RP` (of `IP` and `R`).

Under the current semantics (using `delete` as a shorthand for the corresponding `destroy_*` method):

```c++
delete I // deletes I, IP, R, RP
delete F // deletes F
```

The second delete is valid because `R` is unlinked when it is deleted, so there is no double deletion.

Under the current semantics, the following would be a bug:

```c++
delete I // deletes I, IP, R, RP
delete R // ERROR, R does not exist any more
```

But if you do it in the other order it's fine:

```c++
delete R // deletes R, RP
delete I // deletes I, IP
```

The second deletion is fine because `R` is unlinked at the time it is deleted and doesn't get caught in the recursion from `I`.

The semantics above is equivalent to what I originally called my `recurse` semantics. Another alternative is have the recursion go down instead of across (what @lightsighter called "vertical" but not "horizontal" recursion):

```c++
delete I // deletes I, IP (not actually deleted yet because R still holds a reference)
delete R // deletes R, RP (now I and IP are actually deleted)
```

With the "vertical only" `recurse` semantics above it no longer matters what order you delete the index space and region; either order produces the same result. But watch out with partitions, because the same ordering rules will apply as above.

And then finally there are the non-`recurse` semantics that I originally proposed. I won't bother to show this one, because you just have to delete each object individually, and order doesn't matter because the reference counting keeps things alive until they're really free.

I think what this means is that you can build your own RAII class and it should work fine as long as you never let a region outlast the index space and field space it was created from. Some of the restrictions on ordering are lifted with the "vertical only" `recurse` or non-`recurse` semantics, you may prefer those depending on how strict you want to be about ordering.

Having said that, there are some tricks with RAII that you have to be very careful about. The first is that there are lots of places where you can lose track of references with Legion data structures, typically because those data structures get serialized. If you destroy the original copy then you lose the reference, and this may result in invalid execution (and worse, racy behavior). I think this is the reason why I think Legion requires users to explicitly delete their objects, so that they think explicitly about what the lifetimes of the data are.

It's also worth mentioning that the "reference counting" in my non-`recurse` semantics above is not really a full reference counting. There are no APIs to add and remove references. Every object has one and only one *application* reference (i.e., that can be cleared by `destroy_*`. But different objects in the tree independently hold references and deleting one doesn't automatically clear all references in the subtree below it, which eases certain implementation details, in my opinion.

I'm not sure it's possible to make something as seamless as `shared_ptr` for Legion objects (due to the issues around serialization and task calls), but if you want to do this in an application or library you can probably get most of the way by making your `RAIIRegion` class internally take a `shared_ptr`, in combination with the non-`recurse` semantics I described above. You still have to be careful around what you do with task calls and such.

If you want to propose a different semantics, we're all ears, and now is the time to do so while we're talking about this.

**Comment by opensdh** [comment]
I think it's a perfectly reasonable semantics to say, in general, that `destroy_`ing a thing destroys everything made _from_ that thing: in C++ terms, that every tree node **owns** the subtree rooted at that node.  (But that's not documented anywhere that I know...)  I can understand the other two equally well: the only difference with "vertical-only" is that you say that *`Partition` objects are owned and others are reference counted.

What's important for the application programmer to understand is **when** these things can be destroyed at all.  The tutorial [says](https://legion.stanford.edu/tutorial/logical_regions.html#resource-reclamation) you can do so while tasks are still using them, which sounds like you can't "lose track" of them.  As for explicitly thinking about lifetime, I for one don't consider RAII a substitute for doing so, but rather a **means** for it expressed in terms of the structure of class types and the schedule of local variables.

The code that I've written is independent of model: I assumed that I needed to destroy _each_ object _and_ in "upwards" order (one of whose linearizations is `RP`, `R`, `IP`, `I`, and `F`) because it seemed plausible that destroying, say, a `LogicalRegion` needed to do something with (the internal objects referenced by) its `IndexSpace` and `FieldSpace`.  (How does this relationship work for an `IndexPartition` and its _color_ `IndexSpace`?)

The `shared_ptr` issue I don't understand: I've just been making _unique_, owning handles for Legion objects.  If you're saying that I could make a `std::shared_ptr<MyUniqueLogicalRegion>` to control the lifetime of Legion's object via that of mine, then of course I could (but I haven't happened to need that yet).  You're right also that that approach would be much safer with non-recursive destruction.

**Comment by lightsighter** [comment]
@opensdh I think you should probably not conflate the way @elliottslaughter and I use the term "reference counting" with the more traditional sense of the term. Our references are conceptual and global in a distributed system. Normal reference counting algorithms just track references inside of a single address space for freeing memory. That's very much NOT what we're talking about here. In our "reference counting" we mean that there is a conceptual reference being held to these resource when calls to create or destroy things. There's no object like a smart pointer that is "holding references." Using C++ structures like `std::shared_ptr` are not going to help you maintain these kinds of references because you'll often want to create a resource in one task running on node A and then remove the reference it in a different task running on node B, and C++ smart pointers will not help you with that.

**Comment by opensdh** [comment]
I didn't bring up `std::shared_ptr`.  I'm also not sure how to tell whether a reference is "conceptual": at some point some code on some node has to decide that the reference is gone and free the resources it was using, so it was evidently a detectable thing (however encoded) at at least one place.

I haven't had to deal with the disparate create/remove case yet: what does it look like?  Do you invoke a task and then walk the tree from its `std::vector<PhysicalRegion>` via functions like `PhysicalRegion::get_logical_region`, `LogicalRegion::get_index_space`, and `Runtime::get_index_partition`?  In any case, it's true that you can't use a smart pointer _directly_ in such cases, but I might very well define (as part of our argument-passing system) that a `unique_logical_region` could be passed, only as an rvalue, to transfer (our notion of) ownership to a task.  (Maybe that seems obsessive, but I'll do it only if it seems like it will actually make something simpler or less error-prone for our non-C++-expert users.)

**Comment by elliottslaughter** [comment]
I was the one who brought up `shared_ptr`, but it was intended to be an illustration of the principle @lightsighter is talking about.

Just to be clear, I do think local reference counting can be useful, *but only if you allow yourself to make some simplifying assumptions*. That's why I feel this has to be application-specific or in a library, and it will not cover the full generality of cases that Legion handles. Creating a region in one task and destroying it in another is an example of this generality.

Also, I don't think it's accurate to call Legion's reference counting "conceptual". We do real, honest to goodness reference counting on the inside of Legion. The issue is, we don't trust "automatic" mechanisms like RAII to be responsible for adding and removing references. And we also historically haven't wanted to burden users with needing to explicitly add and remove references themselves. So that's why we made the rule that there is only one application reference and it gets cleared when you run `destroy_*`. But there are absolutely other kinds references: this is how we keep a region alive as long as there is any task that takes it as a `RegionRequirement`.

My recommendation to @opensdh is to think about what kinds of use cases you want to support. Do you need to:

  * Destroy a region in a task other than the one that created it?
  * Create a region inside a subtask and return it to the caller?

If you only use regions within a single task (i.e. the task that creates the region will eventually destroy it), then I do think you can get away with a fairly straightforward `RAIILogicalRegion`. And it might very well use `shared_ptr` internally to make it easier for your users to use. But as soon as you need any of the use cases above you need to think carefully about how to do this so that you don't destroy the underlying `LogicalRegion` too early.

**Comment by opensdh** [comment]
Certainly neither copying nor moving a `shared_ptr` from one task to another is meaningful (lacking any means of coordination).  Nor should Legion necessarily expose a general, distributed reference-counting system, since lazy, extensive use of it (as happens with `shared_ptr`!) would have poor performance.  I personally would still recommend having official Legion owning classes and providing mechanisms to _transfer_ that ownership to another task to help the user guarantee the single `destroy_` call (but not everyone has to share my enthusiasm for destructors).

(I also asked some questions on Slack that I hope will eventually help me speak more intelligently on these topics; that seemed like a better venue for such education.)

**Comment by lightsighter** [comment]
Summarizing what I plan to implement. I am going to modify the semantics of the existing deletion calls to have reference counting semantics. There will be no option for the recursive semantics of deletion that we have today as I don't believe they are even well specified. I am also going to add calls to allow applications to request additional "ownerships" of each of the resources (effectively the ability to add a reference) so that different libraries can each hold ownership of partitions of data that they intend to use regardless of who made the partition.

With regards to dependence analysis, the runtime will continue to perform dependence analysis for deletions in the context in which they are performed and any ancestor task contexts, but will not handle sibling cases.

**Comment by lightsighter** [comment]
What are the semantics of field allocation? Does every field add a reference to its field space and then we require all the fields to be deleted before you can delete the field space? That feels like the natural answer to me, but also somewhat not ergonomic.

**Comment by elliottslaughter** [comment]
I guess the main thing that gets us is that libraries can allocate fields without needing to explicitly request ownership on the field space as a whole. But if you're using truly dynamic fields, you'd have to manage the allocation/deallocation of specific fields anyway. So to be honest, I'm not sure that's really an improvement in semantics.

I can see arguments either way, personally I'm not convinced that the effort to manually deallocate all fields is worth what it buys us in terms of semantics.

**Comment by lightsighter** [comment]
Does that mean that you believe that the deletion of a field space should transitively delete all it's fields? If so, how do you think we should deduplicate races between one task deleting a fields space and another one deleting a field in that field space?

**Comment by elliottslaughter** [comment]
If this is a substantial implementation issue, I'm fine with having that be the deciding factor in terms of what to implement. I don't feel that strong about the semantics either way, it just seems like a minor improvement in usability to not have to delete individual fields.

**Comment by lightsighter** [comment]
Yes, this "deletion from two directions" is exactly the problem that the current runtime suffers from which is why everyone gets crashes. As soon as you have two ways to delete the same object it's possible for there to be races from the application side that the runtime can't protect you from.

**Comment by lightsighter** [comment]
Making a small side-note for myself. Once we fix this, we should also fix the evaluation of projection functions with NO_ACCESS privileges which right now are turned into no NO_REGION results to avoid races with region tree deletions.

**Comment by lightsighter** [comment]
Tracking merge request: https://gitlab.com/StanfordLegion/legion/-/merge_requests/184

**Comment by lightsighter** [comment]
I've merged MR 184 into the master branch. This semantics of deletions should now match those describe above with the following clarifications:

- There is an option on deleting index space and index partitions to recursively destroy partitions below them in the tree to match earlier semantics. It defaults to true to keep the previous semantics, but it can be set to false so you only delete the specific index space or partition.
https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion.h#L3819
https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion.h#L3993
- You can continue to delete fields right up to the point where a field space is destroyed. At that point the runtime will transitively free all remaining fields in the field space.
- Destruction of logical partitions are now a no-op. Logical partitions are deleted by the runtime once either the top-level logical region is deleted or their index partition object is deleted (whichever happens first). 

If anyone has a problem with these semantics you've got 24 hours to comment before I close the issue.

**Comment by opensdh** [comment]
Is the non-effect of `destroy_logical_partition` part of the interface or an implementation detail?  It's [not documented](https://gitlab.com/StanfordLegion/legion/-/blob/master/runtime/legion.h#L5364).

**Comment by lightsighter** [comment]
I will mark it deprecated so that future users will not start to use it, but I do want to give people time to remove it before I delete it from the API.

**Comment by lightsighter** [comment]
It's been a week that everyone has been running with these changes and no major issues so I am closing this issue. If we have problems in the future then we can open new issues to address them. @elliottslaughter you might want to open a new issue to update the Regent compiler, but I believe all the things you need now are in Legion.
