### ISSUE TITLE
Possible bugs in garbage collector?

### ISSUE THREAD

**Issue by jiazhihao** [StanfordLegion/legion#91]
It seems garbage collector doesn't destroy the physical instances even if its belonging logical region has been destroyed. 

I have created a mini test (test/garbage_collection_mini in attach-file branch). The test iteratively creates new logical region, launches a task, and destroys the logical region. The test code controls the number of active logical regions (which is 8 by default).

Following command line could reproduce the bug:
./garbage_collection -ll:csize 1024 -ll:cpu 8 -ll:dma 8

The test case creates 1024 logical regions, each of which contains 1M integers. Therefore, the total memory requirement is 1024 * 1M * 4B = 4GB. But since we are controlling the number of active logical regions (<= 8), 1GB cpu memory should be enough to hold them.

BTW, it seems we cannot observe any instance deletion until Legion runtime is shut down.

**Comment by jiazhihao** [comment]
Following legion_prof output shows the instance lifetime of a successful execution of garbage_collection mini. The bottom part of the profile graph proves that all instances stay alive until the end of the execution.

http://stanford.edu/~zhihao/garbage_collector.html

**Comment by streichler** [comment]
Zhihao,
  Can you use the new legion_prof output mode (-T)?  It's much easier to
navigate.  Thanks,
  - Sean

**Comment by lightsighter** [comment]
There is no bug in the garbage collector.  The cause of this is an implementation decision that Sean and I made several years ago.  When we perform deletions of logical regions, fields, field space, or index spaces, we don't actively go through and invalidate the associated region tree contexts right now.  Instead we wait for the parent task to finish, and then do our normal context invalidation which removed all the references and garbage collector kicks in (hence the reason all the instances do get deleted at the end of the parent task execution).  

There is no reason that we couldn't start invalidating contexts when the actual deletions are performed, but if you do start doing this, we'll need to give precise semantics for how the deletions propagate through the task tree, so that we can ensure that the effects of deletions don't show up unexpectedly in the wrong place and time.  This will require a non-trivial implementation effort.  Do we deem that it is necessary to do now?  Estimated fix time is two uninterrupted coding days.
