### ISSUE TITLE
Support comparison of complex numbers and the reductions comparison implies

### ISSUE THREAD

**Issue by marcinz** [StanfordLegion/legion#910]
NumPy supports lexicographic ordering of complex numbers (in difference from built-in complex numbers in Python). 

Adding comparison operators to complex number implementation in Legion is possible in an external project by just defining these operators in the external project. However, extending reductions seems to be harder without modifying Legion (e.g., extend `MaxReduction`).

So the question is whether it would make sense to extend Legion with lexicographic comparison and the related reductions (with a define guard to enable/disable), or should the external application have special-case implementations for complex numbers that do not rely on reductions.

**Comment by marcinz** [comment]
@lightsighter What do you think?

**Comment by lightsighter** [comment]
I think adding comparison operators to complex numbers should be fine. If you send me a pull request I will merge it into the repo.

**Comment by marcinz** [comment]
I opened merge request #921 with the proposed changes for now.

**Comment by lightsighter** [comment]
I've migrated this pull request over to a gitlab merge request:

https://gitlab.com/StanfordLegion/legion/-/merge_requests/191

There are a few things I changed, and one thing that I think needs to be resolved:

- First, while I understand why you wanted to protect complex comparisons with a special guard, I think it's actually unnecessary. Any user should be smart enough to recognize that comparisons for complex numbers are not particularly well defined, and will therefore check our implementation. Therefore, I've omitted the guards for `LEGION_COMPLEX_LEXICOGRAPHIC_COMPARE` and left them out of the build system. Lexicographic compare will just be the default comparison for our complex types. `std::complex` doesn't define the comparisons so we're not even trampling on their feet either.
- There were a few places where you had assumed c++11 features which I cleaned up. In Legate repos you have full permission to assume at least c++14, but with Legion we keep this part of the code base to c++98 because there are still some client machines that do not have c++11 (or c++03) compilers.
- The one thing I think we definitely need to resolve is the part about the default constructors for complex types. In particular, I did not understand this comment or the need to delete the default constructor that we had there:
> // Default constructor provided for initialization of __shared__ variables
In general, CUDA shouldn't be calling constructors for objects put in `__shared__` memory I think. It's just giving them space, and you need to explicitly construct them yourself. Does the CUDA compiler raise an error or warning if the code has our original default constructor?

**Comment by marcinz** [comment]
Totally forgot about C++98 in Legion. 

As to constructors for `__shared__` variables, here is [the relevant fragment from the documentation](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#device-memory-specifiers). The constructor is not allowed to do anything, including having an initializer list. Initially, I had a constructor with default values for real and imaginary, but I hit the compiler warning on this. Took me a while to get to the specification, and I actually got a hint of it from [this LLVM issue](https://reviews.llvm.org/D15305).

**Comment by lightsighter** [comment]
I've updated the merge request so that each of the complex types now have an empty default constructor, which I think should be sufficient for the CUDA use cases, e.g.:

https://gitlab.com/StanfordLegion/legion/-/blob/complexcompare/runtime/mathtypes/complex.h#L41-42

If that looks good to you then I'll merge the code into the `master` branch and then upstream it to `control_replication`.

**Comment by marcinz** [comment]
It almost looks good. :) `std::complex` has default values for the constructor taking `real` and `imag`. This way you can construct a complex number with no values, with just real, or with both real and imag. At first, I tried exactly this approach (on constructor with two default values), but it failed because of the CUDA requirements. So I provided a default constructor, and a constructor with two arguments, but with default value only for the second argument. I would suggest that we do this again (default value for `imag`) so we can construct complex numbers in all the three ways.

**Comment by lightsighter** [comment]
I've added support for the additional constructors too. The constructor specifications for `std::complex` actually will disqualify them from ever being able to be used in a `__shared__` context with CUDA.

**Comment by marcinz** [comment]
Yes, that's true (about the constructors of `std::complex` not being suitable for CUDA). I wonder if the committee will ever make such adjustments for CUDA, so I guess that the best we will be able to do will be to mimic "as if" we implemented exactly the `std` constructors.

**Comment by lightsighter** [comment]
I've merged the merge request so all the code is in master. It will get merged into control replication later tonight. Closing the issue and the original pull request #921.

> I wonder if the committee will ever make such adjustments for CUDA, so I guess that the best we will be able to do will be to mimic "as if" we implemented exactly the std constructors.

I doubt it. I think CUDA complex and c++ `std::complex` will always just need to be add odds with each other. It's unfortunate, but GPUs are second class citizens for C++.

**Comment by marcinz** [comment]
@lightsighter I noticed that in the process of migration some things got lost. For example, I don't see [these lines](https://github.com/StanfordLegion/legion/pull/921/files#diff-a973cf86da88ec48c3de88cfff5667d5R426-R439) in the checked in version. I wonder if this is because I committed something after the migration was done. I will try to submit a separate pull request for the missing changes, unless they have been removed on purpose.

**Comment by marcinz** [comment]
It seems like it should be actually the only piece missing.

**Comment by lightsighter** [comment]
No need to do that. I think I just missed them. Will push them here shortly.

**Comment by lightsighter** [comment]
Fix pushed to `master` and `control_replication`.

**Comment by marcinz** [comment]
Thank you!

**Comment by marcinz** [comment]
/gpfs/fs1/mzalewski/repos/legate.core/legion/runtime/mathtypes/complex.h(445): error: class "complex<double>" has no member "image" 
:)

**Comment by lightsighter** [comment]
Typo, pushed a fix.
