### ISSUE TITLE
Legion Prof performance improvements

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/legion#926]
The current profiler struggles to produce profiles for large node counts, when it does they are often not viewable as browsers cannot load them in a reasonable amount of time.

This issue is meant to track the progress of porting legion prof to Rust and explore other visualizations options as well as a query interface.

**Comment by elliottslaughter** [comment]
The current status of this is that the Rust profiler works, but generates output that does not match the original Legion Prof. We also have an optional mode to generate output for the Chrome Trace Viewer, with its own set of tradeoffs---it's generally more scalable, but has (in my opinion) a much worse UI, and also can't load traces larger than about 1GB or so.

**Comment by lightsighter** [comment]
> but generates output that does not match the original Legion Prof

How does it not match? Do you think it is buggy? It's also possible the original Legion Prof has bugs in it too, although probably not big ones.

**Comment by elliottslaughter** [comment]
It's been a while since I looked at this, but I think the utilization plots were wrong. I'm currently more inclined to suspect a bug in the Rust Legion Prof, but yes the issue could technically be in either of them.

It might actually be nice to have some programmatically generated Legion Prof logs, because at the moment it's a bit hard to get to ground truth (I mean, you can read the logs, but it's slow and fairly painful). Maybe something else to think about.

**Comment by elliottslaughter** [comment]
The basic Rust profiler has been merged into master. It's not necessarily full-featured, but the features that are present are robust (i.e., are bitwise identical to the Python outputs).

Viewing is still an issue, but I'm not sure we want to tackle that in this issue. We might also be able to solve viewing partially through some combination of mipmaps in the utilization graphs and trimming the detailed profiles.

**Comment by elliottslaughter** [comment]
Another thing I'm noticing is that depending on the filesystem, I/O (especially the final output) easily becomes the bottleneck. It seems to me that we could save both disk space and bandwidth (and eventual network bandwidth) by gzipping the tsv files that we're emitting. My initial estimates are that we could save about 5x on disk space with a `gz` encoding, so that would presumably be a pretty large improvement to I/O (especially on slower or networked filesystems).

**Comment by elliottslaughter** [comment]
One alternative to mipmaps would be to just reduce the resolution of the utilization via averaging over some larger windows, e.g. 10 us, 100 us or even 1 ms. I'm guessing we don't need super fine-grained output anyway here, and this would make the output step and subsequent re-loading in the browser a lot more efficient. (And if we're really worried, we can always make the granularity configurable.)

**Comment by streichler** [comment]
>via averaging over some larger windows

If we go this route, I'd strongly recommend storing (and displaying) the min and max over an interval in addition to the average.

>we can always make the granularity configurable

Bonus points for having the conversion script dump the data at different resolutions and letting the choice of which one to load be controlled by the javascript viewer.

**Comment by syamajala** [comment]
> Another thing I'm noticing is that depending on the filesystem, I/O (especially the final output) easily becomes the bottleneck. It seems to me that we could save both disk space and bandwidth (and eventual network bandwidth) by gzipping the tsv files that we're emitting. My initial estimates are that we could save about 5x on disk space with a `gz` encoding, so that would presumably be a pretty large improvement to I/O (especially on slower or networked filesystems).

I think its possible to test something like this right now for the visualizer without making any changes. You just have to turn on gzip compression in nginx and add the tsv mime-type.

**Comment by elliottslaughter** [comment]
> If we go this route, I'd strongly recommend storing (and displaying) the min and max over an interval in addition to the average.

The way we do things now, the min/max is always 0.0 and 1.0, respectively. (Either a task is running, or it's not.)

Perhaps you meant that if we display e.g. at 1 ms interval, that we also analyze at 0.1 ms intervals (or some smaller value) and take the min/max of that? Because otherwise if you decompose small enough, it seems trivially the case that you'll end up with useless min/max information.

**Comment by streichler** [comment]
Hmm...  Good point.  The smaller interval approach might work - I'm looking for something that helps indicate "burstiness" in the utilization.

**Comment by elliottslaughter** [comment]
Rust Legion Prof is now feature complete (and bitwise identical) for all profiler features that don't require Legion Spy. This means for most typical use cases people should be able to switch to it as their daily driver.

**Comment by lightsighter** [comment]
> for all profiler features that don't require Legion Spy

Are there plans to tackle the critical path analysis in the new Rust profiler or is it just too hard?

**Comment by elliottslaughter** [comment]
There's nothing fundamental, it's just work. I need to implement the parser for the Legion Spy log format and then build all the corresponding data structures, in addition to the visualization output.

**Comment by elliottslaughter** [comment]
Some notes, mostly intended for myself:

  * Browsers support gzip crompression via the `Content-Encoding: gzip` header. This is a standard part of the HTTP protocol and is supported by many web servers.
  * This support is *not* exposed to JavaScript. See [here](https://stackoverflow.com/a/36232639/188046). Ironically, in order to get the browser to automatically decompress content, you need to set the header server-side. Alternatively, you can do it with a third-party JavaScript library like [pako](https://github.com/nodeca/pako).
  * As far as servers go, it seems the normal expectation is that the server compresses content via gzip on the fly. I.e., the content is assumed to be stored uncompressed on disk. In my initial searching so far, I haven't found any servers that support serving pre-compressed content with the correct header. (And again, without the header, you end up needing to do the compression in third-party code instead of getting it for free in the browser.)

You can test this in the simple Python web server we recommend by default. In this test I manually compressed one `tsv` file via `gzip -k`. You can see that the content type comes back as `application/octet-stream` and `Content-Encoding` is not set.

```
$ python3 -m http.server

... switch to different tab ...

$ curl -I -X GET http://localhost:8000/legion_prof_rs_14/legion_prof_processor.tsv.gz
HTTP/1.0 200 OK
Server: SimpleHTTP/0.6 Python/3.8.2
Date: Fri, 02 Jul 2021 00:07:35 GMT
Content-type: application/octet-stream
Content-Length: 838
Last-Modified: Wed, 30 Jun 2021 20:48:31 GMT

$ curl -I -X GET http://localhost:8000/legion_prof_rs_14/legion_prof_processor.tsv
HTTP/1.0 200 OK
Server: SimpleHTTP/0.6 Python/3.8.2
Date: Fri, 02 Jul 2021 00:07:37 GMT
Content-type: text/tab-separated-values
Content-Length: 6598
Last-Modified: Wed, 30 Jun 2021 20:48:31 GMT
```

For all I know there might be a server that does what we want, but I'm not sure we actually want to require a non-standard web server for deployment. Assuming that's not an option, I think we'll be forced to either give up on disk-side compression, or use a third-party library to decompress in JavaScript.

**Comment by elliottslaughter** [comment]
I think this was mostly done via the new UI a long time ago, so closing. If there are further issues, we can open new issues.
