### ISSUE TITLE
Index space launches when some points have a NO_REGION requirement

### ISSUE THREAD

**Issue by hnkolla** [StanfordLegion/legion#95]
I have a test case where I naively launch an Index Space task launch with only one READ_ONLY region requirement through a projection function. The region resolved by the projection function is actually a NO_REGION (or an empty region??) for most points in the Index space launch, except a few. An example is a case where the region corresponds to the domain boundary grid points (a sub region of the partitioned domain) at which boundary conditions need to be implemented in the task. I notice however that the task is instantiated for all the index space points, even though, logically, only the points for which this region is non-empty should be instantiated. The workaround is of course to be aware of this and only launch the task for the end points, but this seems like something the runtime could check and take care of. I verified this using two codes: miniAero and S3D.

**Comment by lightsighter** [comment]
So I pushed a partial fix to this to help cut down on the overhead of the NO_REGION case.  However, the optimization that you raise in this case is an interesting one, but one that I don't think we can ask the runtime to do automatically without some guidance.  Even in the case where all the region requirements for a point task ask for NO_REGION, it is still possible that the task needs to run because it might get arguments through its pass-by-value arguments.  Therefore I think it's only sound for the runtime to do this kind of optimization if all the region requirements are NO_REGION and all the inputs are NULL.  Even then, you might want to have a bunch of random tasks return random values as futures.  @streichler what do you think?

One obvious question for you Hemanth: does this index space task take any arguments, either global arguments, or local arguments passed through an argument map?

Another thing to do would be to modify the projection functors in some way to ask them if they would like to apply this kind of optimization purely based on the region requirements or some combination of the region requirements and input values.

**Comment by hnkolla** [comment]
Thanks for pushing changes Mike. Even as I raised this issue, I've been thinking of scenarios where a NO_REGION requirement might still need the task to run, for instance if there's some output or I/O based on arguments passed in (the scenario you just raised). Although I wonder if that instead should be done from the parent task itself. Also, not sure of you guys plans for collectives, but that's another scenario potentially where a NO_REGION might still need the task instantiation.


My index space task does take arguments (for the moment the direction in the S3D grid, but there might be more), although I'm trying to see if I can avoid that. In my case the direction can actually be inferred inside the task based on the shape of the domain of the physical region.


Thanks,

Hemanth.

________________________________

**Comment by streichler** [comment]
Now that Legion knows how to do an index launch on a sparse index space, I'd argue that's a cleaner way of skipping unneeded work that detecting empty region requirements.  As long as individual point tasks' projection functions can return NO_REGION for the "out of bounds" cases, I think we're good here.

**Comment by lightsighter** [comment]
I agree. I think we can close this issue for now.
