### ISSUE TITLE
legion: `MapTaskInput.valid_instances` not populated for regions with reduction privilege

### ISSUE THREAD

**Issue by rohany** [StanfordLegion/legion#959]
With some logging at the beginning of `map_task`, it appears that the `valid_instances` vector for regions with the reduction privilege is never populated. Given that it's possible to reuse reduction instances now, it seems like this structure should be populated.

**Comment by lightsighter** [comment]
As I explained on slack, this is not a bug. In the circuit simulation example that you showed the reduction instances are invalidated immediately after they are used by the `distribute_charge` task because the `update_voltages` tasks read the data which flushes the changes from the reduction instances thereby invalidating them. Furthermore, the `calculate_new_currents` task writes those fields which also would make the data in those reduction instances stale. It is therefore impossible in the circuit simulation to ever have the reduction instances show up in the list of `valid_instances` as they will never contain valid data. There are cases where reduction instances should show up in the `valid_instances`, but this is not one of them. Come up with a different example that you think doesn't work if you think this is still an issue.

**Comment by rohany** [comment]
If this is the case, why can the default mapper cache the physical instances used and then choose them when mapping a task with a reduction instance again?

**Comment by elliottslaughter** [comment]
A valid instance is one that has valid data, i.e. the data contained in the instance is up to date. You can still reuse an instance that does not have valid data, but the reason to choose such an instance is to avoid additional memory allocations, not to take advantage of the data that is already present in the instance. In other words, reusing a valid instance means you can avoid both the memory allocation and the copy of the data (from another valid instance). If you reuse a non-valid instance you avoid the memory allocation but not the copy (you have to get the data from somewhere else, since the instance you chose is not up to date).

With reductions, obviously you don't do a copy, but there is still a fill required to zero the instance so that it can be used. So like Mike said if you flush a reduction instance, it becomes no longer valid (since the data is no longer up to date in the reduction instance) and you have to reinitialize it to be able to use it again.

Legion tracks valid instances because it's something you can only do reliably with the information that the runtime has to compute the full dependence graph. I.e. this would be difficult or impossible to track yourself even if you wanted to. Whereas keeping a list of cached instances is much easier in a mapper because it requires no special analysis. You can always check if the cache is still valid and re-create the instance if it isn't.

**Comment by rohany** [comment]
OK, thanks for the clarification. I started to do this local instance caching in my mapper, but wasn't sure why it was correct.
