### ISSUE TITLE
Find new source of macOS CI coverage

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/legion#982]
As has been noted elsewhere (https://github.com/terralang/terra/issues/355), there are changes coming for the free Travis CI support. This is not a large impact for us since most of our coverage (that matters) is on Gitlab, but we do get macOS coverage from Travis.

We have three options to continue our macOS CI coverage:

 1. Move from travis-ci.org to travis-ci.com (note the domain extension). After migration, we will have a limit on our build minutes and will need to periodically refresh those (by emailing support) in order to keep going. [Some such requests have been denied](https://news.ycombinator.com/item?id=25338983), so it's unclear if we'd ever be approved for this process.

 2. Buy some Mac hardware to install Gitlab CI runners. The usual caveats for procurement and maintenance will apply.

 3. Move to another CI platform, e.g., Github Actions. For now this is free and seems to provide fairly generous resource limits, but as with any free resource, it could hypothetically change in unforeseen ways in the future.

We have a deadline of December 31 to do this (if we want to maintain continuous macOS coverage) because that's when [travis-ci.org is shutting down](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#frequently-asked-questions).

(I'm not sure I will actually have time to look at this before then, so unless someone else volunteers to pick this up, we may just end up with a coverage gap.)

**Comment by streichler** [comment]
Github Actions is looking promising for being at least as good as Travis ever was, but it won't be ready in the next couple days, and it's not clear that its support for custom runners matches what we need for e.g. cuda tests, so I think I'm still favoring the answer being "(2) and (3)".  However, I think we can rule out option (1) and I've gone ahead and shut off the Travis CI runs since they're full of false positives at this point.

I'm going to look at building some infrastructure for defining tests in an gitlab/github-agnostic way (which was going to be needed for #731 anyway), and we'll use it to generate both the gitlab ci and the github actions stuff.

**Comment by elliottslaughter** [comment]
We ended up buying some Mac hardware to put on our existing Gitlab CI. Testing the MR here: https://gitlab.com/StanfordLegion/legion/-/merge_requests/757

**Comment by elliottslaughter** [comment]
Merged.
